### ISSUE TITLE
Acknowledgement-based throttling support

### ISSUE THREAD

**Issue by bopagama** [lmangani/sentinl#180]
Is their any way to prevent the watch actions from being executed again while the watch condition remains true.
Can ES ACK API be used in sentinl for this purpose? If yes how? or is their any alternative way to do the same.

Ref: [https://www.elastic.co/guide/en/elasticsearch/reference/5.5/watcher-api-ack-watch.html](url)

**Comment by lmangani** [comment]
Only preset Throttle is available at this time, in future versions we'll keep track of Alerts outside of ES to maximize realtime statuses, etc.
