### ISSUE TITLE
Multiple alarms from single watcher

### ISSUE THREAD

**Issue by aquaman2** [lmangani/sentinl#234]
Hi guys! First, thanks for the great product! According to my previous [issue](https://github.com/sirensolutions/sentinl/issues/232) I have another question:
Is it possible to make N separate alarms from one watcher, when N keys in search result match the condition? And if yes, how I can achieve this?

**Comment by lmangani** [comment]
Hi @aquaman2 
Could you make a practical example just to understand  your scenario best and/or how you would use this? We do support multiple actions, and we could add a per-action condition if that's of interest to more users.

**Comment by aquaman2** [comment]
The case: we need separate alerts for the empty topics due to different admins are responsible for them. Our event management system based on syslog messages which received from Sentinl using webhooks->logstash chain. So each alert and syslog message should contain only one topic.
The sample initial payload you can see [here](https://github.com/sirensolutions/sentinl/issues/232).

In that scheme if more than one (N) topic has no records, using recursive processing sub-buckets as result we have one alert with all (N) matched keys in the body message. But we need N alerts with single key. Is this possible?

**Comment by lmangani** [comment]
As a starting point, we're adding an optional ```action``` condition script block you can use to implement sub logic or target fields generated by transform scripts - hopefully this can address your scenario and others - feel free to comment/suggest.

_Current Proposal:_
```
 "actions": {
    "email_positive": {
        "throttle_period": "15m",
        "condition": { "script": "payload.something" },
        "email": {
          . . . 
        }
      },
    "email_negative": {
        "throttle_period": "15m",
        "condition": { "script": "!payload.something" },
        "email": {
          . . . 
        }
      }
```

**Comment by sethyes** [comment]
+1 for this -- in my config I need each event to fire an alert off to a Jira endpoint to update a ticket. This is only doable on a per-ticket basis, thus I'm unable to script a bulk update in the (typical) case I have more than one Jira ticket to update.

**Comment by omarix** [comment]
+1, 
we uses ELK for security analytic , and in our case each event/aggregation bucket references to a separated incident or attacker and should be handled separately , so I think handling this feature by a hard coded condition doesn't serve our use-case. 
Triggering  action per event or per aggregation and compose the actions options from the result (dynamically ) will makes Sentinl very flexible and cover many cases.

Regards.
Omar
Omar

**Comment by lmangani** [comment]
As an easy interim solution, you can write the "actionable" events in a custom ES index, and use a second watcher to trigger and alert on each individually.

**Comment by simrandeep11** [comment]
@lmangani 
The work around that you have mentioned above, is it implemented and available for use?

**Comment by lmangani** [comment]
@simrandeep11 that was a post from 2018, but i admire your optimism
