### ISSUE TITLE
Feature request: Support forcing all webhook traffic through a proxy

### ISSUE THREAD

**Issue by mikejkjr** [lmangani/sentinl#264]
I'd like to use Sentinl webhooks in our Kibana installation, which runs in a Kubernetes cluster. Our Kibana is used by a small group of customers. Since Sentinl webhooks can be changed through the UI to hit any arbitrary host, myself and my security associates are concerned that installing Sentinl would allow our customers to potentially hit our servers from within our own network. 

Kubernetes' network security is still maturing: you can limit traffic between pods, and you can stop traffic from leaving the cluster, but you can't easily limit traffic to predefined hosts outside the cluster. Besides, we'd have to allow traffic to our Elasticsearch server pods anyway; still don't want webhooks hitting that! So, we would like to force Sentinl to use our proxy to control traffic from the webhooks.

I'm aware that Sentinl supports proxies, but that's also configurable from the UI, which does not meet our needs. Would a feature configuring a proxy globally for all webhooks be appropriate here?

This could be configured in the [Sentinl config](https://github.com/sirensolutions/sentinl/wiki/SENTINL-Config-Example), perhaps like this:

```yaml
sentinl:
  webhook:
    active: true
    proxy:
       hostname: "proxy.example.com"
       port: 8888
```

If the `proxy` object is present, it would override any webhook proxy configuration when firing the webhook in [actions.js](https://github.com/sirensolutions/sentinl/blob/master/server/lib/actions/actions.js#L338). That would allow us to force all webhook traffic to our proxy.

How does this proposal sound? I'd be happy to submit a PR for it.

**Comment by lmangani** [comment]
Hi @mikejkjr this type of feature is available in the Enterprise version of Kibi, which includes granular access control to platform features. This being said, feel free to submit a PR and we'll happily consider it.

Thanks!

**Comment by jccq** [comment]
@mikejkjr after conversation , what you're asking is not exacty the same thing as what's available in the http://support.siren.io platform distribution of Sentinl so if you'd like to propose a PR we'll be looking into that for integration. Thanks for your contribution.

**Comment by mikejkjr** [comment]
Ok. I'll get started on it then, and hopefully will have something for ya'll to look at soon!
