### ISSUE TITLE
Idea: Adding query URL to Slack payload

### ISSUE THREAD

**Issue by dm-vc** [lmangani/sentinl#317]
Hi,

Is it possible (I couldn't find a way at least) to have the URL to the watcher query included within the alerts? 

Example: Watcher fires, Slack message gets sent, and in the Slack message is a URL to the query that the notification was generated from.

Thanks!

**Comment by lmangani** [comment]
Hi @dm-vc do you mean dynamically, or statically as part of the Alert? I believe you can already inject pretty much anything you want into the body of the Slack notification. Would you have a "virtual" example in terms of how you would use this?

Thanks!

**Comment by dm-vc** [comment]
Hi @lmangani, I meant dynamically. I'm not sure how to add this to the Slack alert, as I'm assuming it would be something like {{payload.url}}.

If I had a watcher set up to look for failed logins, the Slack notification might look something like:

`@channel: Alert! X login failed within the last Y minutes: https://url-to-elk-query`

Where the `https://url-to-elk-query` would contain all of the failed logins for further investigation. 

Does that make more sense? Let me know if you have any questions.

Thanks.

**Comment by lmangani** [comment]
Well, this is not straightforward unless I'm missing the point. SENTINL doesn't really know much about dashboards where the same data might be displayed, it operates using its own queries (which might be the same as widgets, but not really) - If SENTINL did have access to a URL paramters, it could easily generate a rison URL with adjusted time settings of course. So the point is all about where should we take the URL from, if not from the response or by the user injecting it in the Alert? Ideas welcome!
