### ISSUE TITLE
Multiple email in HA

### ISSUE THREAD

**Issue by varun0002** [lmangani/sentinl#321]
1. Sentinl and Kibana version: 5.4.1 

2. Issue description: Getting multiple emails for scheduled alarms in HA environment.

3. Reproducing the issue step-by-step: Run Kibana in HA (more than 1 Kibana)

4. Expected results vs. actual results: Should send only one mail per alarm/schedule.

5. Additional details
We are running Kibana in HA i.e. more than 2 active Kibana (with ESmaster). Every scheduled alarm in sentinl sends the number mails based on active Kibana. It works fine if user executes alarm manually from kibana i.e. sends only single mail. I can keep email as active on only one Kibana and disable on others. However, that may impact if user try to execute alarm manually from the console. How should we setup email setting for sentinl in HA environment?

**Comment by lmangani** [comment]
Hi @varun0002 HA is currently only available in Siren Alert, the Siren version of SENTINL part of their Siren 10 Stack. I'm not familiar with ESmaster, feel free to share additional details or send a PR/Feature request.

**Comment by varun0002** [comment]
@lmangani: Thanks for quick response. I was referring ESmaster as ElasticSearch master. Can you please provide me any reference link for Siren Alert? 
Are there any config changes we can make in Sentinl so user would get only single mail for each scheduled alarm when Kibana is running in HA?

**Comment by lmangani** [comment]
@varun0002 will check ESmaster and provide some feedback.

Siren Alert is only bundled with The Siren 10 Stack at this time, as it relies on advanced features unavailable in stock Kibana and Elasticsearch.

**Comment by varun0002** [comment]
@lmangani We may not need anything from ESmaster side. I just kept that for more details.
The core problem, we are getting multiple emails for scheduled alarms when Kibana is running as HA. 

Please let me know if I would need to open new issue for HA support or we can consider this as feature request?

**Comment by steve21168** [comment]
Hi this is an issue for me as well.  Is there any recommended advice on how you can have more than 1 Kibana running while avoiding duplicate alerts per Kibana?
