### ISSUE TITLE
Robust Keepalive Monitoring Accounting for 'Index Doesn't Exist'

### ISSUE THREAD

**Issue by sethyes** [lmangani/sentinl#360]
1. Sentinl and Kibana version 5.6.2

2. Issue description
I have a 'keepalive' watcher which monitors an index and reports if keepalive messages don't come through, indicating the data pipeline is broken. This would work great except that if no data is getting published to the expected index, the index doesn't exist and Sentinl doesn't execute the watcher, thus I never receive a keepalive alarm. 

3. Reproducing the issue step-by-step
Create a watcher that reports if data doesn't get ingested into a certain index. Turn off the data ingest into that index, the following day (if you're using daily indices), instead of a getting an alert that data hasn't been ingested, if you look through the Kibana logs, you'll see that alerts fire for the index not existing.

4. Expected results vs. actual results
I'd like to get some sort of alert that Sentinl is broken, perhaps it's a configuration setup that only soft-errors if an index doesn't exist, perhaps it's an administrative email informing me that Sentinl executed a watcher which caused an error. 

5. Sample of data
```
{
  "search": {
    "request": {
      "index": [
        "<keepalive-{now/d}>",
        "<keepalive-{now/d-1d}>"
      ],
      "body": {
        "query": {
          "exists": {
            "field": "keepalive.keyword"
          }
        }
      }
    }
  }
}
```

6. Additional details
I'm asking for advice on how to best-architect a keepalive alert such as this. In the 'Expected vs Actual Results' section, I proposed a couple potential solutions. However I'm sure you'll likely have additional solutions which fit better with the established architecture.

**Comment by lmangani** [comment]
@sethyes trying to understand the scenario. My first attempt would be to detect a missing (daily) index in parallel to this detection not to overload its role, is this something you already attempted?

Could you provide the logs (or better query) resulting from one of those borked executions when the index is not found? It's just a matter of catching the condition and probably adding "error" reporting in the body of a watcher.

Thanks!

**Comment by sethyes** [comment]
I did attempt to detect a missing index on the input, however I received an error as `exists` doesn't support `index` field.
My input:
```
{
  "search": {
    "request": {
      "body": {
        "query": {
          "bool": {
            "must_not": {
              "exists": {
                "index": "keepalive-{now/d}"
              }
            }
          }
        }
      }
    }
  }
}
```
and the response: 
```
Sentinl Watchers: Error 406 Not Acceptable: [parsing_exception] [exists] query does not support [index], with { line=1 & col=49 }
```
I'm not seeing much in the Kibana logs, but I do get a console alert:
```
Sentinl Watchers: Error 406 Not Acceptable: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="keepalive-2018.03.20" & index_uuid="na" & index="keepalive-2018.03.20" }
```

My only issue with just looking for a missing index, is that means I might not be alerted to a down pipeline until the following day. If I could make indices optional somehow, that would allow the watcher to still alert on no keepalive being received. 

Let me know if I can clarify further. Thanks @lmangani

**Comment by lmangani** [comment]
I see - What if we had an `alert on index_not_found` option in general for watchers? I guess its not useless in general....

**Comment by sethyes** [comment]
That'd be great! Either that, or allow for the search to return no results due to the index not existing.

**Comment by lmangani** [comment]
I think the long term solution would be to offer two parsers, for results AND errors so both can be handled. We'll do some brainstorming around this and find a viable path to start with.

**Comment by sethyes** [comment]
Thanks! Your commitment to maturing this standout product is what has my whole company committed to using your products. Let me know if I can provide any assistance.
