### ISSUE TITLE
Copy/Clone to option for Watcher definition

### ISSUE THREAD

**Issue by varun0002** [lmangani/sentinl#365]
Sentinl and Kibana version: 5.4.1

Request for Information:
Do we have any _copy to_ option available. **Use case**: I want to create multiple watchers with slight change in input and condition definition. Currently, I have to copy all screens in notepad and then paste screen by screen to new alert. Copy to option should help me to generate new watcher and make changes where ever required.

**Comment by rrares** [comment]
Hello,

Having the same issue. Is there a way of generating automatically more watchers ?

I have around 20-30 different rules and I want to change the "mail to: " field. 
I hope I don't have to manually go through each watcher and change it.

Thanks

**Comment by sergibondarenko** [comment]
Sentinl doesn't have a possibility to insert multiple watcher via UI. But you can write a simple JS script to insert watcher in Elasticsearch, for example
```
const { exec } = require('child_process');

const watchers = [
  {
    title: 'watcher0'
  },
  {
    title: 'watcher1'
  }
];

for (let i in watchers)
  console.log(`/usr/bin/curl -X POST "localhost:9200/.kibana/doc/" -H 'Content-Type: application/json' -d '${JSON.stringify(watchers[i])}'`);
```
Then execute it `node script.js`

Also, you can use [.bulk()](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-bulk) method from Elasticsearch API.

**Comment by fbaligand** [comment]
I'm also very interested by a "Clone" button available in watcher editor !

**Comment by sergibondarenko** [comment]
@fbaligand clone is a nice enhancement
