### ISSUE TITLE
Issue with the GUI

### ISSUE THREAD

**Issue by masterofcloud1** [lmangani/sentinl#383]
Well it is some really weird issue... But you have some serious GUI problem.
Almost every time I press the help button it is covered by the panel on the side.
Attached picture of example:

![image](https://user-images.githubusercontent.com/35032551/38094158-b6abc98c-3375-11e8-977c-8966c95678e5.png)

**Comment by shrv** [comment]
Hello.
I see the same thing.
ELK - 6.2
sentinl - 6.2.2
Installed according to the instructions to github
```
/opt/kibana/bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.2/sentinl-v6.2.2.zip
```
Allow me another question.
For version 6.2.2, it is important to make changes to the /etc/kibana/kibana.yml ?
As written here
<http://sentinl.readthedocs.io/en/latest/Config-Example/>

**Comment by shrv** [comment]
@lmangani Thanks!
Note, for you install instruction.
For ELK 6.2, path to kibana-plugin is
```
/usr/share/kibana/bin/kibana-plugin
```

**Comment by lmangani** [comment]
@shrv thanks for the heads up, what document are you referring to specifically?

**Comment by shrv** [comment]
Here
<https://github.com/sirensolutions/sentinl/blob/master/README.md>

In the instructions at <http://sentinl.readthedocs.io/en/latest/Installation/#dev-plugin-install> everything is correct
