### ISSUE TITLE
Don't use deprecated indices in docs

### ISSUE THREAD

**Issue by sergibondarenko** [lmangani/sentinl#390]
```
trex@beast:~/Development/siren/sentinl$ grep -rne "indices\"" docs/
docs/Watcher-Examples.md:227:          "indices": [
docs/Watcher-Examples.md:268:          "indices": [
docs/HOWTO-Alerts-in-Nagios-NRDP.md:157:        "indices": [
```

**Comment by lmangani** [comment]
We'll need to do docs per branch in order for this to be consistent unless the new format is backwards compatible?

**Comment by sergibondarenko** [comment]
@lmangani the new format (`index`) is not compatible with Elasticsearch 2.x. I think we need to separate the documentation by version. We already have this but there, for example, the config: http://sentinl.readthedocs.io/en/latest/Config-Example/

But I believe there should be a better mode.
