### ISSUE TITLE
Feature request: CMD action

### ISSUE THREAD

**Issue by danielmotaleite** [lmangani/sentinl#425]
Please consider adding a cmd or shell command action, so we could use custom shell scripts to notify external services or even run auto-fix commands for certain problems.

The action is configured in the kibana.yml and the user UI will only choose one of the CMD actions and parameters. The UI would never change the comand executed nor accept subshells, to avoid security problems

**Comment by lmangani** [comment]
I do not foresee SENTINL taking the responsibility to sanitize and execute potentially dangerous commands, but its quite trivial to build a custom API client to take dangerous jobs.

A very, very insecure example of both arguments, untested:
```
const exec = require('child_process').exec;
const fastify = require('fastify')()

fastify.get('/command', (request, reply) => {
  console.log(request.body)
  exec(cmd, function(error, stdout, stderr) {
    if (error) { reply.code(500); reply.send(stderr) }
	else { reply.code(200); reply.send(stdout); }
  });
})

// Run the server!
fastify.listen(3000, (err) => {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  fastify.log.info(`server listening on ${fastify.server.address().port}`)
})
```

```
/**

	"webhook": {
          "method": "POST",
          "host": "local.service",
          "port": "3000",
          "path": "/command",
          "body": "echo 'received {{payload.hits.total}} hits'",
          "headers": {
            "Content-Type": "application/x-www-form-urlencoded"
          },
          "create_alert" : false
        }

**/
```

**Comment by lmangani** [comment]
Perhaps it would be a cool idea to bundle a small working API receiver example with the Docs, helping anyone bootstrap their own execution back-end for Alerts?

**Comment by danielmotaleite** [comment]
my idea was to have a config file with the allowed commands to execute, the UI would only list then and allowed to select the command to run. 
IF any arguments are passed, it should be a filename, that should store any value neededand the command should take care of reading/parse/whatever

So a example:
send-alert.sh
```
#!/bin/bash
curl http://alert-service:8888/send-alert -XPOST -d @$1
``` 
```
"cmd": {
     "name": "send alert",
     "script": "/path/send-alert.sh",
     "argument": "file"
 },
```

The UI should have then a simple pulldown list with the "send alert"

The API is not a bad workaround, but requires one to build API and manage another service, where scripts are already common on monitoring/alert

Thanks for the feedback
