### ISSUE TITLE
Limit of total fields in index [watcher] has been exceeded

### ISSUE THREAD

**Issue by varun0002** [lmangani/sentinl#445]
1. Sentinl and Kibana version: 5.4.1

2. Issue description: Getting following error:
_Jun  1 09:59:08 <host> kibana: {"type":"error","@timestamp":"XXXXX","tags":[],"pid":DDDD,"level":"error","message":"[illegal_argument_exception] Limit of total fields [1000] in index [watcher] has been exceeded","error":{"message":"[illegal_argument_exception] Limit of total fields [1000] in index [watcher] has been exceeded","name":"Error","stack":"[illegal_argument_exception] Limit of total fields [1000] in index [watcher] has been exceeded :: {\"path\":\"/watcher/sentinl-watcher/-vc514r4b588a-a9jaqg10a933\",\"query\":{},\"body\":\"{\\\"title\\\":\\\"watcher_title\\\",\\\"disable\\\":false,\\\"report\\\":false,\\\"trigger\\\":{\\\"schedule\\\":{\\\"later\\\":\\\"every 5 mins\\\"}},\\\"input\\\":{\\\"search\\\":{\\\"request\\\":{\\\"index\\\":[],\\\"body\\\":{}}}},\\\"condition\\\":{\\\"script\\\":{\\\"script\\\":\\\"payload.hits.total > 100\\\"}},\\\"actions\\\":{\\\"email_admin\\\":{\\\"throttle_period\\\":\\\"0h15m0s\\\",\\\"email\\\":{\\\"to\\\":\\\"alarm@localhost\\\",\\\"from\\\":\\\"sentinl@localhost\\\",\\\"subject\\\":\\\"Sentinl Alarm\\\",\\\"priority\\\":\\\"high\\\",\\\"body\\\":\\\"Found {{payload.hits.total}} Events\\\"}},\\\"New HTML email action bdjzgrztl9bh\\\":{\\\"throttle_period\\\":\\\"0h0m1s\\\",\\\"email_html\\\":{\\\"to\\\":\\\"\\\",\\\"from\\\":\\\"\\\",\\\"subject\\\":\\\"\\\",\\\"body\\\":\\\"\\\",\\\"html\\\":\\\"\\\"}}}}\",\"statusCode\":400,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"illegal_argument_exception\\\",\\\"reason\\\":\\\"Limit of total fields [1000] in index [watcher] has been exceeded\\\"}],\\\"type\\\":\\\"illegal_argument_exception\\\",\\\"reason\\\":\\\"Limit of total fields [1000] in index [watcher] has been exceeded\\\"},\\\"status\\\":400}\"}\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:295:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:254:7)\n    at HttpConnector.<anonymous>_ 

3. Workaround: 
For now we increased field limits to 1500. However, this is not sustainable solution. it appears sentinl doesn't delete index fields even if watcher is deleted. Can you please suggest any possible ways to clean-up fields associated with deleted watchers?

**Comment by lmangani** [comment]
@varun0002 sentinl will manage watcher objects, but it will NOT remove any of the data or logs they might generates - this is up to the user to rotate using curator or any other method. Does this answer your question?

**Comment by varun0002** [comment]
We generally use curator to remove old data. However, this case is special as we are not dealing with old data rather unused fields created in watcher index by Sentinl alarm. 
Is there any way we can figure-out which fields in watcher index are no more in use? Any recommendation would be helpful.
