### ISSUE TITLE
No plugin available for kibana 5.6.9

### ISSUE THREAD

**Issue by koinoyokan17** [lmangani/sentinl#451]
1. Sentinl and Kibana version - 5.6.9

2. No release available to install to kibana 5.6.9

3. Open releases page - there is no version for 5.6.9 kibana

4. Expected results - version available. Actual results - no.

**Comment by koinoyokan17** [comment]
If anyone will need it - https://github.com/koinoyokan17/cake-tool-conf/raw/master/sentinl-v5.6.9.zip

**Comment by lmangani** [comment]
Hi @koinoyokan17 thanks for sharing your version, we'll add one to our builder if its needed @sergibondarenko

**Comment by MrYZD** [comment]
No plugin available for kibana 5.6.910

**Comment by MrYZD** [comment]
No plugin available for kibana 5.6.10 @lmangani

**Comment by lmangani** [comment]
@MrYZD you can build your own version based on the closest branch anytime if needed
