### ISSUE TITLE
Watcher creates alarm at hits > 0 but gives error with hits == 0

### ISSUE THREAD

**Issue by zinefer** [lmangani/sentinl#475]
1. Sentinl and Kibana version 
6.2.3-3

2. Issue description
I am trying to create a flatline alert. I have a ES query that returns 30 hits in the dev tools. If I create an alert with `payload.hits.total == 0` for the condition I get a ```
Watchers: no data was found that match the used "script" conditions```. If I switch the condition to `payload.hits.total > 0` then I get an alarm triggered.

Here is my raw watcher:
```
{
  "actions": {
    "Email X-Men": {
      "throttle_period": "0h15m0s",
      "email": {
        "to": "admin@localhost",
        "from": "sentinl@localhost",
        "subject": "DelayedJob Flatline Alarm",
        "priority": "high",
        "body": "Unable to detect the delayed_job process in the last 5 minutes"
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "metricbeat-*"
        ],
        "body": {
          "query": {
            "bool": {
              "must": [
                {
                  "match_phrase": {
                    "beat.name": {
                      "query": "machinename"
                    }
                  }
                },
                {
                  "query_string": {
                    "query": "system.process.cmdline:delayed_job*",
                    "analyze_wildcard": true,
                    "default_field": "*"
                  }
                },
                {
                  "range": {
                    "@timestamp": {
                      "gte": "now-5m",
                      "lte": "now",
                      "format": "epoch_millis"
                    }
                  }
                }
              ]
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total == 0"
    }
  },
  "transform": {},
  "trigger": {
    "schedule": {
      "later": "every 5 minutes"
    }
  },
  "disable": true,
  "report": false,
  "title": "DelayedJob Flatline Alarm - fleet-portal1.staging"
}
```

**Comment by lmangani** [comment]
Hi @zinefer are  you sure your response has a `payload.hits.total` field when there are no hits?

**Comment by zinefer** [comment]
I am sure of that, actually...

I did some more testing, replacing the query that returned 30 hits with one that specifically returned 0 and found that my watcher is working correctly.

I think the issue here is that the UI was warning me that my watcher condition was returning false when I was running it manually.

**Comment by lmangani** [comment]
That's good to hear. If you can replicate this, please check out the Kibana logs from the sentinl plugin in case there are warnings or errors there as you execute and we'll look into that. Thanks!

**Comment by steve21168** [comment]
I'm experiencing the same thing.  It seems like there is a (confusing) warning message when everything is operating normally.

The condition script should return true or false. However when it returns false there always seems to be the warning message: "no data was found that match the used script conditions".  This is also needlessly logged to Kibana.
