### ISSUE TITLE
Sentinl not working with xpack

### ISSUE THREAD

**Issue by gaurav6041** [lmangani/sentinl#490]
1. sentinl version 6.2.3 , kibana version 6.2.3 , elasticsearch version 6.2.3

2. In sentinl when i add new watcher  , no table is getting displayed. In this instance both xpack and sentinl are installed . When i remove xpack and then run kibana  , sentinl is working properly.

**Comment by havlan** [comment]
Post logs from Kibana. Especially logs from when you create a new watcher.

**Comment by gaurav6041** [comment]
Here are the logs : 
{"type":"response","@timestamp":"2018-07-04T08:44:03Z","tags":[],"pid":1085,"method":"get","statusCode":200,"req":{"url":"/api/saved_objects/?type=sentinl-watcher&per_page=10&search=%22test_watcher1%22&search_fields=title&fields=title&page=1","method":"get","headers":{"host":"192.168.10.121:5602","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"6.2.3","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","referer":"http://192.168.10.121:5602/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8"},"remoteAddress":"192.168.0.130","userAgent":"192.168.0.130","referer":"http://192.168.10.121:5602/app/sentinl"},"res":{"statusCode":200,"responseTime":21,"contentLength":9},"message":"GET /api/saved_objects/?type=sentinl-watcher&per_page=10&search=%22test_watcher1%22&search_fields=title&fields=title&page=1 200 21ms - 9.0B"}
{"type":"response","@timestamp":"2018-07-04T08:44:03Z","tags":[],"pid":1085,"method":"post","statusCode":200,"req":{"url":"/api/saved_objects/sentinl-watcher?overwrite=true","method":"post","headers":{"host":"192.168.10.121:5602","connection":"keep-alive","content-length":"449","accept":"application/json, text/plain, */*","origin":"http://192.168.10.121:5602","kbn-version":"6.2.3","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","content-type":"application/json;charset=UTF-8","referer":"http://192.168.10.121:5602/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8"},"remoteAddress":"192.168.0.130","userAgent":"192.168.0.130","referer":"http://192.168.10.121:5602/app/sentinl"},"res":{"statusCode":200,"responseTime":1205,"contentLength":9},"message":"POST /api/saved_objects/sentinl-watcher?overwrite=true 200 1205ms - 9.0B"}
{"type":"response","@timestamp":"2018-07-04T08:44:04Z","tags":[],"pid":1085,"method":"get","statusCode":200,"req":{"url":"/api/sentinl/time","method":"get","headers":{"host":"192.168.10.121:5602","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"6.2.3","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","referer":"http://192.168.10.121:5602/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8"},"remoteAddress":"192.168.0.130","userAgent":"192.168.0.130","referer":"http://192.168.10.121:5602/app/sentinl"},"res":{"statusCode":200,"responseTime":3,"contentLength":9},"message":"GET /api/sentinl/time 200 3ms - 9.0B"}
{"type":"response","@timestamp":"2018-07-04T08:44:04Z","tags":[],"pid":1085,"method":"get","statusCode":304,"req":{"url":"/ui/favicons/favicon-32x32.png","method":"get","headers":{"host":"192.168.10.121:5602","connection":"keep-alive","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","accept":"image/webp,image/apng,image/*,*/*;q=0.8","referer":"http://192.168.10.121:5602/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8","if-none-match":"\"8e183c2e644fb050707d89402e1f7a120a95e4d2\"","if-modified-since":"Mon, 02 Jul 2018 08:58:20 GMT"},"remoteAddress":"192.168.0.130","userAgent":"192.168.0.130","referer":"http://192.168.10.121:5602/app/sentinl"},"res":{"statusCode":304,"responseTime":2,"contentLength":9},"message":"GET /ui/favicons/favicon-32x32.png 304 2ms - 9.0B"}
{"type":"response","@timestamp":"2018-07-04T08:44:04Z","tags":[],"pid":1085,"method":"get","statusCode":304,"req":{"url":"/ui/favicons/favicon-16x16.png","method":"get","headers":{"host":"192.168.10.121:5602","connection":"keep-alive","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","accept":"image/webp,image/apng,image/*,*/*;q=0.8","referer":"http://192.168.10.121:5602/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8","if-none-match":"\"13b869be5df4bdc56920edc16a28e67a7c08203b\"","if-modified-since":"Mon, 02 Jul 2018 08:58:20 GMT"},"remoteAddress":"192.168.0.130","userAgent":"192.168.0.130","referer":"http://192.168.10.121:5602/app/sentinl"},"res":{"statusCode":304,"responseTime":2,"contentLength":9},"message":"GET /ui/favicons/favicon-16x16.png 304 2ms - 9.0B"}
{"type":"response","@timestamp":"2018-07-04T08:44:04Z","tags":[],"pid":1085,"method":"get","statusCode":200,"req":{"url":"/api/sentinl/config","method":"get","headers":{"host":"192.168.10.121:5602","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"6.2.3","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","referer":"http://192.168.10.121:5602/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8"},"remoteAddress":"192.168.0.130","userAgent":"192.168.0.130","referer":"http://192.168.10.121:5602/app/sentinl"},"res":{"statusCode":200,"responseTime":2,"contentLength":9},"message":"GET /api/sentinl/config 200 2ms - 9.0B"}
{"type":"response","@timestamp":"2018-07-04T08:44:04Z","tags":[],"pid":1085,"method":"get","statusCode":200,"req":{"url":"/api/sentinl/config","method":"get","headers":{"host":"192.168.10.121:5602","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"6.2.3","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","referer":"http://192.168.10.121:5602/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8"},"remoteAddress":"192.168.0.130","userAgent":"192.168.0.130","referer":"http://192.168.10.121:5602/app/sentinl"},"res":{"statusCode":200,"responseTime":8,"contentLength":9},"message":"GET /api/sentinl/config 200 8ms - 9.0B"}
{"type":"response","@timestamp":"2018-07-04T08:44:04Z","tags":[],"pid":1085,"method":"get","statusCode":200,"req":{"url":"/api/sentinl/config","method":"get","headers":{"host":"192.168.10.121:5602","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"6.2.3","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","referer":"http://192.168.10.121:5602/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8"},"remoteAddress":"192.168.0.130","userAgent":"192.168.0.130","referer":"http://192.168.10.121:5602/app/sentinl"},"res":{"statusCode":200,"responseTime":5,"contentLength":9},"message":"GET /api/sentinl/config 200 5ms - 9.0B"}
{"type":"response","@timestamp":"2018-07-04T08:44:04Z","tags":[],"pid":1085,"method":"get","statusCode":200,"req":{"url":"/api/sentinl/config","method":"get","headers":{"host":"192.168.10.121:5602","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"6.2.3","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","referer":"http://192.168.10.121:5602/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8"},"remoteAddress":"192.168.0.130","userAgent":"192.168.0.130","referer":"http://192.168.10.121:5602/app/sentinl"},"res":{"statusCode":200,"responseTime":2,"contentLength":9},"message":"GET /api/sentinl/config 200 2ms - 9.0B"}
{"type":"response","@timestamp":"2018-07-04T08:44:04Z","tags":[],"pid":1085,"method":"get","statusCode":200,"req":{"url":"/api/saved_objects/?type=sentinl-script&search=input*&per_page=50&page=1&search_fields=title%5E3&search_fields=description","method":"get","headers":{"host":"192.168.10.121:5602","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"6.2.3","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","referer":"http://192.168.10.121:5602/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8"},"remoteAddress":"192.168.0.130","userAgent":"192.168.0.130","referer":"http://192.168.10.121:5602/app/sentinl"},"res":{"statusCode":200,"responseTime":29,"contentLength":9},"message":"GET /api/saved_objects/?type=sentinl-script&search=input*&per_page=50&page=1&search_fields=title%5E3&search_fields=description 200 29ms - 9.0B"}
{"type":"response","@timestamp":"2018-07-04T08:44:04Z","tags":[],"pid":1085,"method":"get","statusCode":200,"req":{"url":"/api/saved_objects/?type=sentinl-script&search=condition*&per_page=50&page=1&search_fields=title%5E3&search_fields=description","method":"get","headers":{"host":"192.168.10.121:5602","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"6.2.3","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","referer":"http://192.168.10.121:5602/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8"},"remoteAddress":"192.168.0.130","userAgent":"192.168.0.130","referer":"http://192.168.10.121:5602/app/sentinl"},"res":{"statusCode":200,"responseTime":26,"contentLength":9},"message":"GET /api/saved_objects/?type=sentinl-script&search=condition*&per_page=50&page=1&search_fields=title%5E3&search_fields=description 200 26ms - 9.0B"}
{"type":"response","@timestamp":"2018-07-04T08:44:04Z","tags":[],"pid":1085,"method":"get","statusCode":200,"req":{"url":"/api/saved_objects/?type=sentinl-watcher&per_page=50&page=1&search_fields=title%5E3&search_fields=description","method":"get","headers":{"host":"192.168.10.121:5602","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"6.2.3","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","referer":"http://192.168.10.121:5602/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8"},"remoteAddress":"192.168.0.130","userAgent":"192.168.0.130","referer":"http://192.168.10.121:5602/app/sentinl"},"res":{"statusCode":200,"responseTime":16,"contentLength":9},"message":"GET /api/saved_objects/?type=sentinl-watcher&per_page=50&page=1&search_fields=title%5E3&search_fields=description 200 16ms - 9.0B"}
{"type":"response","@timestamp":"2018-07-04T08:44:04Z","tags":[],"pid":1085,"method":"get","statusCode":200,"req":{"url":"/api/saved_objects/?type=sentinl-script&search=transform*&per_page=50&page=1&search_fields=title%5E3&search_fields=description","method":"get","headers":{"host":"192.168.10.121:5602","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"6.2.3","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","referer":"http://192.168.10.121:5602/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"en-GB,en-US;q=0.9,en;q=0.8"},"remoteAddress":"192.168.0.130","userAgent":"192.168.0.130","referer":"http://192.168.10.121:5602/app/sentinl"},"res":{"statusCode":200,"responseTime":10,"contentLength":9},"message":"GET /api/saved_objects/?type=sentinl-script&search=transform*&per_page=50&page=1&search_fields=title%5E3&search_fields=description 200 10ms - 9.0B"

**Comment by gaurav6041** [comment]
And here is the screenshot
![sentinl](https://user-images.githubusercontent.com/40815733/42266789-01eb8660-7f95-11e8-8ee4-464dda0d9f24.png)

**Comment by havlan** [comment]
@gaurav6041 could you use ``` at the beginning and end of your logs? makes it a pleasure to work with. Can you post the response from the request in the network developer tools?

**Comment by lmangani** [comment]
@gaurav6041 SENTINL is designed for the Open-Source Kibana. In order to use it with xpack you need to account for the authentication aspects first and foremost - did you do so? This being said, Elastic is systematically sabotaging every plugin in the ecosystem so I wouldn't be surprised to find something intentionally placed to break our functionality :)

**Comment by gaurav6041** [comment]
@havlan - Thanks for the correction. I am new to posting on gitgub. Does it look ok now.
 And what are network developer tools?

**Comment by gaurav6041** [comment]
@lmangani - I am not using security features of xpack , using just the basic version.

**Comment by havlan** [comment]
@gaurav6041 in your browser: right click + inspect + network tab, reload the Sentinl page, paste both request and response of the get alarm request. Or are there some errors in he developer Console (console tab) ?
![screenshot from 2018-07-05 08-12-34](https://user-images.githubusercontent.com/18334546/42305467-57c5b65a-802b-11e8-98e6-86d68393fb41.png)
