### ISSUE TITLE
Kibana fails to start on installing sentinl-6.2.4.zip

### ISSUE THREAD

**Issue by bananth2008** [lmangani/sentinl#494]
1. **Sentinl and Kibana version** 

- Kibana version - 6.2.4
- Sentinl Version 6.2.4

2. **Issue description**

- Unable to install sentinl plugin. Kibana does not start and goes into a loop- trying to start and stop
- Find attached part of the stacktrace

_Jul  9 13:25:29 ip-172-31-23-18 systemd[1]: kibana.service: Failed with result 'exit-code'.
Jul  9 13:25:29 ip-172-31-23-18 systemd[1]: kibana.service: Service hold-off time over, scheduling restart.
Jul  9 13:25:29 ip-172-31-23-18 systemd[1]: Stopped Kibana.
Jul  9 13:25:29 ip-172-31-23-18 systemd[1]: Started Kibana.
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]: {"type":"error","@timestamp":"2018-07-09T13:25:31Z","tags":["fatal"],"pid":6062,"level":"fatal","error":{"message":"EPERM: operation not permitted, chmod '/usr/share/kibana/plugins/sentinl/node_modules/phantomjs-prebuilt/bin/phantomjs'","name":"Error","stack":"Error: EPERM: operation not permitted, chmod '/usr/share/kibana/plugins/sentinl/node_modules/phantomjs-prebuilt/bin/phantomjs'\n    at Error (native)\n    at fs.chmodSync (fs.js:1177:18)\n    at PluginPack.exports.default [as _provider] (/usr/share/kibana/plugins/sentinl/index.js:53:3)\n    at PluginPack.getPluginSpecs (/usr/share/kibana/src/plugin_discovery/plugin_pack/plugin_pack.js:50:25)\n    at MergeMapSubscriber.find$.mergeMap [as project] (/usr/share/kibana/src/plugin_discovery/find_plugin_specs.js:47:39)\n    at MergeMapSubscriber._tryNext (/usr/share/kibana/node_modules/rxjs/src/operator/mergeMap.ts:125:21)\n    at MergeMapSubscriber._next (/usr/share/kibana/node_modules/rxjs/src/operator/mergeMap.ts:115:12)\n    at MergeMapSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)\n    at RefCountSubscriber.Subscriber._next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:135:22)\n    at RefCountSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)\n    at Subject.next (/usr/share/kibana/node_modules/rxjs/src/Subject.ts:61:17)\n    at ConnectableSubscriber.Subscriber._next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:135:22)\n    at ConnectableSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)\n    at MergeAllSubscriber.OuterSubscriber.notifyNext (/usr/share/kibana/node_modules/rxjs/src/OuterSubscriber.ts:13:22)\n    at InnerSubscriber._next (/usr/share/kibana/node_modules/rxjs/src/InnerSubscriber.ts:17:17)\n    at InnerSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)\n    at CatchSubscriber.Subscriber._next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:135:22)\n    at CatchSubscrib
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]: er.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)\n    at MergeMapSubscriber.notifyNext (/usr/share/kibana/node_modules/rxjs/src/operator/mergeMap.ts:151:24)\n    at InnerSubscriber._next (/usr/share/kibana/node_modules/rxjs/src/InnerSubscriber.ts:17:17)\n    at InnerSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)\n    at CatchSubscriber.Subscriber._next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:135:22)","code":"EPERM"},"message":"EPERM: operation not permitted, chmod '/usr/share/kibana/plugins/sentinl/node_modules/phantomjs-prebuilt/bin/phantomjs'"}
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]: FATAL { Error: EPERM: operation not permitted, chmod '/usr/share/kibana/plugins/sentinl/node_modules/phantomjs-prebuilt/bin/phantomjs'
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at Error (native)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at fs.chmodSync (fs.js:1177:18)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at PluginPack.exports.default [as _provider] (/usr/share/kibana/plugins/sentinl/index.js:53:3)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at PluginPack.getPluginSpecs (/usr/share/kibana/src/plugin_discovery/plugin_pack/plugin_pack.js:50:25)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at MergeMapSubscriber.find$.mergeMap [as project] (/usr/share/kibana/src/plugin_discovery/find_plugin_specs.js:47:39)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at MergeMapSubscriber._tryNext (/usr/share/kibana/node_modules/rxjs/src/operator/mergeMap.ts:125:21)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at MergeMapSubscriber._next (/usr/share/kibana/node_modules/rxjs/src/operator/mergeMap.ts:115:12)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at MergeMapSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at RefCountSubscriber.Subscriber._next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:135:22)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at RefCountSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at Subject.next (/usr/share/kibana/node_modules/rxjs/src/Subject.ts:61:17)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at ConnectableSubscriber.Subscriber._next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:135:22)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at ConnectableSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at MergeAllSubscriber.OuterSubscriber.notifyNext (/usr/share/kibana/node_modules/rxjs/src/OuterSubscriber.ts:13:22)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at InnerSubscriber._next (/usr/share/kibana/node_modules/rxjs/src/InnerSubscriber.ts:17:17)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at InnerSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at CatchSubscriber.Subscriber._next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:135:22)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at CatchSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at MergeMapSubscriber.notifyNext (/usr/share/kibana/node_modules/rxjs/src/operator/mergeMap.ts:151:24)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at InnerSubscriber._next (/usr/share/kibana/node_modules/rxjs/src/InnerSubscriber.ts:17:17)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at InnerSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:95:12)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:     at CatchSubscriber.Subscriber._next (/usr/share/kibana/node_modules/rxjs/src/Subscriber.ts:135:22)
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:   errno: -1,
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:   code: 'EPERM',
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:   syscall: 'chmod',
Jul  9 13:25:31 ip-172-31-23-18 kibana[6062]:   path: '/usr/share/kibana/plugins/sentinl/node_modules/phantomjs-prebuilt/bin/phantomjs' }
Jul  9 13:25:31 ip-172-31-23-18 systemd[1]: kibana.service: Main process exited, code=exited, status=1/FAILURE
Jul  9 13:25:31 ip-172-31-23-18 systemd[1]: kibana.service: Unit entered failed state.
Jul  9 13:25:31 ip-172-31-23-18 systemd[1]: kibana.service: Failed with result 'exit-code'._

3. **Reproducing the issue step-by-step**

- The configuration is as follows

sentinl:
  settings:
    email:
      active: true
      user: xxxx
      password: xxxx
      host: xxx
      ssl: true
    report:
      active: true
      engine: 'horseman'
      phantomjs_path: '/usr/local/bin/phantomjs'
      chrome_path: '/usr/bin/chromium'

4. **Additional details**

- Tried without phantomjs_path parameter and chrome_path parameter. The same error comes.
- Tried giving all permissions to kibana/plugins folder. Same error comes
- Tried installing pahntomjs_prebuilt seperately with a different value for phantomjs_path parameter (refer above), still the same error comes.
- While installing the plugin,the following is displayed

Extraction complete
Optimizing and caching browser bundles...
[sentinl] fail to make report engine executable: ENOENT: no such file or directry, scandir '/usr/share/kibana/plugins/sentinl/node_modules/puppeteer/.local-chomium'!
Plugin installation complete

We have recently moved from version 6.2.2 to version 6.2.4.  
Thanks in advance for your help!

Regards,
Bhavani

**Comment by lmangani** [comment]
Thanks for your report. The issue is caused by SENTINL attempting to have the Kibana shell change permissions to the phantomjs module. I'm not sure if this is related to the user running kibana and their limitations being inherited, installing SENTINL requires full access. We'll check.

**Comment by havlan** [comment]
I think think the user kibana needs access. I ran into something like this.

```
sudo -u kibana ./bin/kibana-plugin install ...
```
I can't recall if this resolved everything. Maybe add your user to the kibana group, chown the plugin if installing from file.

**Comment by havlan** [comment]
Kibana user needs access to phantomjs I think. 
Try something like this: ```chown -R kibana:kibana plugins/sentinl/node_modules/phantomjs-prebuilt/bin/*```
