### ISSUE TITLE
Resouce Trigger

### ISSUE THREAD

**Issue by mehrdad1985** [lmangani/sentinl#520]
hello
is there template for resource triggers such as CPU-usage , Cpu-Load , memory-Usage or ... ?
i tried to make some of them by metricbeat but not too useful . 
if it's possible it could be a good replacement for zabbix-server or even nagios . 
please is there is any template or something like that ntify me !

**Comment by lmangani** [comment]
Hi @mehrdad1985 the upcoming version of SENTINL ships with a wizard which should help form alarms from timeseries easily. I'm not familiar with metricbeat, but you should be able to create many types of alerts using the SENTINL scripts and options. If you have an example for your failed attempt, we'll help you fix it and add it to the docs examples.

Thanks!
