### ISSUE TITLE
Question and bugs on new Wizard

### ISSUE THREAD

**Issue by bienensenf** [lmangani/sentinl#529]
Hello,

I have a few questions about the new Wizard UI on 6.2.4-4. Thank you for developing it.

I do not get how to do the input query based on field values. Let's say I want to throw an alarm when there are 20 logs with field value  "field": "error" in 15minutes. How would you do that?

What is the attribute in "grouped over" / "over" -> "top" for? Setting it does not seem to change the Watcher Query. 

Bugs:
-When a wizard field is opened and the user clicks somewhere else or clicks on the next wizard field the opened field should be closed in my opinion

-There are also document fields listed that aren't fields but higher JSON levels. E.g. JSON:
{ "field": {
  "subfield": "value } }
Then also "field" is shown as a field

-You could make the wizard fields longer. As of right now some fields for example say: "FOR LAST 3 yea" instead of "FOR LAST 3 years"

-The chart does not always reload and when it does it lags and the page does not react until it has finished loading. Also when I select "months" in "FOR LAST" I always get no data.

You probably know about these bugs but in case you don't this is just a quick notice.

**Comment by bienensenf** [comment]
Also the Action section is just appearing when data could be returned in the chart. I want to set up alarms also on data that is not there yet or does not fulfill the given timeframe. That makes the wizard unfortunately pretty unusable for me

**Comment by sergibondarenko** [comment]
You can access actions if there is no data in the chart.

Save the wizard watcher with a big timeframe, when there is data in the
chart. Then click the wizard watcher in the watchers list. Decrease the
timeframe to a level you need. Actions panel should be still there.

**Comment by sergibondarenko** [comment]
Here is a wizard builder doc

https://docs.google.com/document/d/1Vbi2IBy5TNmCBXpNqmp23Z99AaDZwIero9XTWOvz4kc/edit?usp=drivesdk

It is still under development.

**Comment by bienensenf** [comment]
Still did not find anything about field values. Did I miss something or is it not in there?

**Comment by sergibondarenko** [comment]
I put some comments in the doc above.
