### ISSUE TITLE
Watcher with matching string condition

### ISSUE THREAD

**Issue by elg0ch0** [lmangani/sentinl#531]
Hi guys,

 Is it possible you provide an example for a watcher with a condition to "match a string" (a regular expression would be even better)? Isn't it possible with sentinl?
 I'm trying to send an alert when some strings appear in my application logs.

 1. Sentinl and Kibana version: 6.2.4

 Thanks,

**Comment by rajapaladugula** [comment]
"query": {
            "bool": {
              "filter": [
                {
                  "range": {
                    "@timestamp": {
                      "gte": "now-60m",
                      "lte": "now"
                    }
                  }
                },
                {
                  "term": {
                    "metricset.name": "filesystem"
                  }
                },
                {
                  "wildcard": {
                    "system.filesystem.device_name": "/dev/mapper*"
                  }
                },
                {
                  "range": {
                    "system.filesystem.used.pct": {
                      "gte": "0.10"
                    }
                  }
                }
              ]
            }
          },

I guess your condition "matching a string using Reg Exp" can be achieved by using the "wildcard Query" -> https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html 
Here i am trying to match "system.filesystem.device_name" to "/dev/mapper*"

You can find my watcher at https://github.com/rajapaladugula/DevOps/blob/master/Sentinl_watcher_file-system_alert

**Comment by sergibondarenko** [comment]
@elg0ch0 To search, in the advanced watcher `input` you must have an Elasticsearch query. At first you have to understand Elasticsearch query syntax. I recommend you to read and try the following things in the Kibana dev console:
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-bool-query.html
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-terms-query.html
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-match-query.html
