### ISSUE TITLE
quot change can not send action?

### ISSUE THREAD

**Issue by aabababb** [lmangani/sentinl#539]
{\"transDateTime\":\"2018-09-12 22:51:11\",\"transAcctid\"

\"will change to be
&quot

**Comment by sergibondarenko** [comment]
@aabababb  when you create an issue in this repository you see the following default message, don't you? The goal of the message is to let you know what input data are required. Please include the full watcher doc too.

---
Default message:
```
<!--
Thanks for taking time to report an issue. Please try to:

* Be precise: describe expected results vs. actual results
* Be clear: explain how to reproduce the problem, step by step
* Include only one problem per report
* Include details about your setup/system/os where possible

This section will NOT appear in your Issue report!
-->

1. Sentinl and Kibana version 

2. Issue description

3. Reproducing the issue step-by-step

4. Expected results vs. actual results

5. Sample of data

6. Additional details
```

**Comment by aabababb** [comment]
> 
> 
> @aabababb when you create an issue in this repository you see the following default message, don't you? The goal of the message is to let you know what input data are required. Please include the full watcher doc too.
> 
> Default message:
> 
> ```
> 
> 
> 1. Sentinl and Kibana version 
> 
> 2. Issue description
> 
> 3. Reproducing the issue step-by-step
> 
> 4. Expected results vs. actual results
> 
> 5. Sample of data
> 
> 6. Additional details
> ```

sorry,my english just so so。。。

**Comment by sergibondarenko** [comment]
@aabababb use Google Translator, for example
https://translate.google.com/#auto/zh-CN/Thanks%20for%20taking%20time%20to%20report%20an%20issue.%20Please%20try%20to%3A%0A%0A*%20Be%20precise%3A%20describe%20expected%20results%20vs.%20actual%20results%0A*%20Be%20clear%3A%20explain%20how%20to%20reproduce%20the%20problem%2C%20step%20by%20step%0A*%20Include%20only%20one%20problem%20per%20report%0A*%20Include%20details%20about%20your%20setup%2Fsystem%2Fos%20where%20possible%0A%0AThis%20section%20will%20NOT%20appear%20in%20your%20Issue%20report!%0A--%3E%0A%0A1.%20Sentinl%20and%20Kibana%20version%20%0A%0A2.%20Issue%20description%0A%0A3.%20Reproducing%20the%20issue%20step-by-step%0A%0A4.%20Expected%20results%20vs.%20actual%20results%0A%0A5.%20Sample%20of%20data%0A%0A6.%20Additional%20details

**Comment by lmangani** [comment]
@aabababb try using triple brackets on the affected template object (not guaranteed to be the case but worth a shot)

**Comment by aabababb** [comment]
> 
> 
> @aabababb try using triple brackets on the affected template object (not guaranteed to be the case but worth a shot)

it works! thanks you very much!

how about this
actual results
 message-[2018-09-12 22:51:15.110]-ERROR-[biz:489568705320353792][sys:489568705320353793][com.phfund.aplus.camp.tran.proxy.mq.MqTaskProcess$receiver-227][][处理异常数据：{&quot;transDateTime

raw

`{
  "actions": {
    "errordd": {
      "throttle_period": "0h0m1s",
      "webhook": {
        "method": "POST",
        "host": "oapi.dingtalk.com",
        "port": 443,
        "proxy": false,
        "path": "/robot/send?access_token=ed08e288a604bc15f",
        "body": "{\n     \"msgtype\": \"text\",\n     \"text\": {\n         \"content\": \"test1234\n   {{payload.hits.total}}\\n\n   hostname-{{payload.hits.hits.0._source.beat.hostname}}\\n\n   ip-{{payload.hits.hits.0._source.beat.name}}\\n\n   version-{{payload.hits.hits.0._source.beat.version}}\\n\n   level-{{payload.hits.hits.0._source.level}}\\n\n   source-{{payload.hits.hits.0._source.source}}\\n\n   message-{{payload.hits.hits.0._source.message}}\\n\n         \"\n     }\n }",
        "priority": "high",
        "use_https": true,
        "create_alert": true,
        "save_payload": true,
        "headers": {
          "Content-type": "application/json"
        }
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "*"
        ],
        "body": {
          "query": {
            "bool": {
              "must": [
                {
                  "query_string": {
                    "analyze_wildcard": true,
                    "default_field": "level",
                    "query": "ERROR"
                  }
                },
                {
                  "range": {
                    "@timestamp": {
                      "gte": "now-7d",
                      "lte": "now",
                      "format": "epoch_millis"
                    }
                  }
                }
              ],
              "must_not": []
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total >= 1"
    }
  },
  "transform": {},
  "trigger": {
    "schedule": {
      "later": "every 1 minutes"
    }
  },
  "disable": true,
  "report": false,
  "title": "dd"
}`

**Comment by lmangani** [comment]
@aabababb i can't comment on that without seeing the full response the template handles

**Comment by aabababb** [comment]
> 
> 
> @aabababb try using triple brackets on the affected template object (not guaranteed to be the case but worth a shot)

where is the template handles?

Expected results
{\"transDateTime\":\"2018-09-12}

actual results
{&quot;transDateTime&quot;:&quot;2018-09-12}

**Comment by aabababb** [comment]
> 
> 
> Those two examples appear to be identical.
> The pipeline is `ES QUERY > RESPONSE > CONDITION > TRANSFORM > TEMPLATE > RESULT`
 ok,thanks,I go to try again.

**Comment by lzh-boy** [comment]
> > @aabababb try using triple brackets on the affected template object (not guaranteed to be the case but worth a shot)
> 
> it works! thanks you very much!
> 
> how about this
> actual results
> message-[2018-09-12 22:51:15.110]-ERROR-[biz:489568705320353792][sys:489568705320353793][com.phfund.aplus.camp.tran.proxy.mq.MqTaskProcess$receiver-227][][处理异常数据：{<&quot>;transDateTime
> 
> raw
> 
> `{ "actions": { "errordd": { "throttle_period": "0h0m1s", "webhook": { "method": "POST", "host": "oapi.dingtalk.com", "port": 443, "proxy": false, "path": "/robot/send?access_token=ed08e288a604bc15f", "body": "{\n \"msgtype\": \"text\",\n \"text\": {\n \"content\": \"test1234\n {{payload.hits.total}}\\n\n hostname-{{payload.hits.hits.0._source.beat.hostname}}\\n\n ip-{{payload.hits.hits.0._source.beat.name}}\\n\n version-{{payload.hits.hits.0._source.beat.version}}\\n\n level-{{payload.hits.hits.0._source.level}}\\n\n source-{{payload.hits.hits.0._source.source}}\\n\n message-{{payload.hits.hits.0._source.message}}\\n\n \"\n }\n }", "priority": "high", "use_https": true, "create_alert": true, "save_payload": true, "headers": { "Content-type": "application/json" } } } }, "input": { "search": { "request": { "index": [ "*" ], "body": { "query": { "bool": { "must": [ { "query_string": { "analyze_wildcard": true, "default_field": "level", "query": "ERROR" } }, { "range": { "@timestamp": { "gte": "now-7d", "lte": "now", "format": "epoch_millis" } } } ], "must_not": [] } } } } } }, "condition": { "script": { "script": "payload.hits.total >= 1" } }, "transform": {}, "trigger": { "schedule": { "later": "every 1 minutes" } }, "disable": true, "report": false, "title": "dd" }`

你钉钉可以了吗，我最近也在整合，但总是不成功，也不报错

**Comment by aabababb** [comment]
> 
> 
> > > @aabababb try using triple brackets on the affected template object (not guaranteed to be the case but worth a shot)
> > 
> > 
> > it works! thanks you very much!
> > how about this
> > actual results
> > message-[2018-09-12 22:51:15.110]-ERROR-[biz:489568705320353792][sys:489568705320353793][com.phfund.aplus.camp.tran.proxy.mq.MqTaskProcess$receiver-227][][处理异常数据：{<&quot>;transDateTime
> > raw
> > `{ "actions": { "errordd": { "throttle_period": "0h0m1s", "webhook": { "method": "POST", "host": "oapi.dingtalk.com", "port": 443, "proxy": false, "path": "/robot/send?access_token=ed08e288a604bc15f", "body": "{\n \"msgtype\": \"text\",\n \"text\": {\n \"content\": \"test1234\n {{payload.hits.total}}\\n\n hostname-{{payload.hits.hits.0._source.beat.hostname}}\\n\n ip-{{payload.hits.hits.0._source.beat.name}}\\n\n version-{{payload.hits.hits.0._source.beat.version}}\\n\n level-{{payload.hits.hits.0._source.level}}\\n\n source-{{payload.hits.hits.0._source.source}}\\n\n message-{{payload.hits.hits.0._source.message}}\\n\n \"\n }\n }", "priority": "high", "use_https": true, "create_alert": true, "save_payload": true, "headers": { "Content-type": "application/json" } } } }, "input": { "search": { "request": { "index": [ "*" ], "body": { "query": { "bool": { "must": [ { "query_string": { "analyze_wildcard": true, "default_field": "level", "query": "ERROR" } }, { "range": { "@timestamp": { "gte": "now-7d", "lte": "now", "format": "epoch_millis" } } } ], "must_not": [] } } } } } }, "condition": { "script": { "script": "payload.hits.total >= 1" } }, "transform": {}, "trigger": { "schedule": { "later": "every 1 minutes" } }, "disable": true, "report": false, "title": "dd" }`
> 
> 你钉钉可以了吗，我最近也在整合，但总是不成功，也不报错

钉钉可以，只是发送消息时，quot的转义不了。。。

**Comment by aabababb** [comment]
@lzh-boy 兄弟，麻烦把那个引用回复删除下，谢谢
