### ISSUE TITLE
'/' in the payload data is being printed as '&#x2F;'

### ISSUE THREAD

**Issue by rajapaladugula** [lmangani/sentinl#546]
1. Sentinl and Kibana version :  6.2.4 ; Elastic: 6.4.0

2. Issue description:

a) '/' in the payload data is being printed as "&#x2F;"
Ex:  "/dev/mapper/centos-root is printed as "&#x2F;dev&#x2F;mapper&#x2F;centos-root"

b) {{trigger.triggered_time}} or {{trigger.scheduled_time}} does not produce any thing. I dont find any information from response payload either for the same.

3. Reproducing the issue step-by-step

4. Expected results vs. actual results:

Expected::
```
Watcher Alert - HIGH Disk_Space USAGE!
Hosts with HIGH Disk_Space Usage (>10%):
localhost.localdomain
File_system_names: /dev/mapper/centos-root
Disk_Space is at: 16.37% at xx:xx:xxxx xx:xx:xxxx
```
Actual::
```
Watcher Alert - HIGH Disk_Space USAGE!
Hosts with HIGH Disk_Space Usage (>10%):
localhost.localdomain
File_system_names: .dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root
Disk_Space is at: 16.37%
```

5. Sample of data:
```
{
  "took": 9,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 359,
    "max_score": 0,
    "hits": [
      {
        "_index": "metricbeat-6.4.0-2018.09.26",
        "_type": "doc",
        "_id": "cuVwF2YBQC5dbawBZq4L",
        "_score": 0,
        "_source": {
          "@timestamp": "2018-09-26T19:52:13.073Z",
          "metricset": {
            "name": "filesystem",
            "module": "system",
            "rtt": 535
          },
          "system": {
            "filesystem": {
              "device_name": "/dev/mapper/centos-root",
              "total": 53660876800,
              "free": 44951920640,
              "mount_point": "/",
              "free_files": 26042488,
              "files": 26214400,
              "type": "xfs",
              "available": 44951920640,
              "used": {
                "pct": 0.1623,
                "bytes": 8708956160
              }
            }
          },
          "beat": {
            "name": "localhost.localdomain",
            "hostname": "localhost.localdomain",
            "version": "6.4.0"
          },
          "host": {
            "name": "localhost.localdomain"
          }
        }
      },
"aggregations": {
    "hosts": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "localhost.localdomain",
          "doc_count": 359,
          "values_avg": {
            "value": 0.1625598885793872
          }
        }
      ]
    }
  }
}
```
6. Additional details:
```
"message": "Watcher Alert - HIGH Disk_Space USAGE! \n\n Hosts with HIGH Disk_Space Usage (>10%):\n\n{{payload.hosts}}\n\n File_system_names: {{payload.device_name}}\n\n Disk_Space is at: {{payload.filesystem}} at  {{trigger.triggered_time}} {{trigger.scheduled_time}} \n\n",
```
Can i also know which Temple ting Language is used in SENTINL while retrieving data from payload.

**Comment by sergibondarenko** [comment]
@rajapaladugula 
1. You cant test your mustache here http://mustache.github.io/#demo
2. Do you receive the following message in email after mustache parse?
> Actual::
```
Watcher Alert - HIGH Disk_Space USAGE!
Hosts with HIGH Disk_Space Usage (>10%):
localhost.localdomain
File_system_names: .dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root, &#x2F;dev&#x2F;mapper&#x2F;centos-root
Disk_Space is at: 16.37%
```

**Comment by rajapaladugula** [comment]
@sergibondarenko Thanks for the response.

Yes, it is what i receive in Slack.
I am not sure if i am substituting in the fields correctly:

Mustache: {{payload.aggregations.hosts.buckets.map(bucket => {return bucket.device_name.buckets.map(buck => {return buck.key});})}}

JSON ;
"aggregations": {
    "hosts": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "localhost.localdomain",
          "doc_count": 720,
          "device_name": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "key": "/dev/mapper/centos-root",
                "doc_count": 360
              },
              {
                "key": "/dev/sda1",
                "doc_count": 360
              }
            ]
          },
          "devicespace_avg": {
            "value": 0.1779236111111111
          }
        }
      ]
    }
  }

Please help, i see the following in HTML: SyntaxError: Unexpected token : in JSON at position 14.

**Comment by havlan** [comment]
@rajapaladugula Try to use triple curly brackets to not escape html symbols.
![screenshot from 2018-11-01 20-59-27](https://user-images.githubusercontent.com/18334546/47876211-0a1cac00-de19-11e8-825c-974efc748ada.png)
