### ISSUE TITLE
Sentinl for Kibana 6.4 : impossible to create an "advanced watcher" on Firefox

### ISSUE THREAD

**Issue by fbaligand** [lmangani/sentinl#561]
1. Sentinl and Kibana version 
Sentinel for Kibana 6.4 and Kibana 6.4.0
Browser : Firefox 62.0.2
OS : Windows 10 (but I don't think it is tied to OS)

2. Issue description
Using Firefox browser, when I create a new watcher and choose "advanced watcher", I get a blank screen in Kibana.
I don't reproduce the issue with Chrome and IE11.

3. Reproducing the issue step-by-step
Click on "Watchers"' tab, then "New" link, then "Advanced Watcher" button

4. Additional details
No error log in browser console.
No error log in Kibana server console.

**Comment by fropert** [comment]
Same issue as @fbaligand  with Firefox 62.0.2.
It works with Google Chrome.

**Comment by fbaligand** [comment]
As @fropert, I reproduce the issue only on Firefox.
So I update the title and description to precise that the bug is specific to Firefox.

**Comment by sergibondarenko** [comment]
Get the latest release with fixes here https://github.com/sirensolutions/sentinl/releases/tag/tag-6.4.2-0

**Comment by fbaligand** [comment]
Hi @sergibondarenko 
I just tried this new version, and unfortunately, I still reproduce the issue on Firefox.

**Comment by fbaligand** [comment]
My Firefox version is : 62.0.2
My OS version is : Windows 10

**Comment by camAtGitHub** [comment]
+1 Same issue here. I came to report this.
Windows 10 - Firefox 64bit 63.0.1
Chrome works fine etc. Nothing logged in Kibana logs - Literally nothing on mouse press of link.

**Comment by terenho** [comment]
Under Sentinl version 6.4.2

+1 Same issue with:
OS: Ubuntu 18.04.1
Browser: Firefox 64bit 65.0

No problem with Chromium 71.0.3578.98
