### ISSUE TITLE
 Sentinl for Kibana 6.4+ : migrate "wizzard watcher" to "advanced watcher" link is tricky to find

### ISSUE THREAD

**Issue by fbaligand** [lmangani/sentinl#562]
1. Sentinl and Kibana version 
 Sentinel for Kibana 6.4 and Kibana 6.4.0
OS : Windows 10 (but I don't think it is tied to OS)

2. Issue description
If I create a new watcher using "wizzard" and then save it, when I go to "Watchers" list, I don't see the "convert to advanced watcher" link.
This feature was available in Kibana 6.2 and was greatly useful !

**Comment by rasmusdencker** [comment]
I have never used previous versions of Sentinl, but I use the feature you're describing; if you go to edit the Wizard watcher, then go to Match Condition section => Click "Chart Query" => Just above the textarea you'll find a link that says "convert to advanced". 

Is that what you're looking for?

**Comment by fbaligand** [comment]
Hi @rasmusdencker 

Thanks for the tip, that is what I looked for !
I must admit the link is quite "hidden" and tricky to find, compared to previous version.

**Comment by sergibondarenko** [comment]
Get the latest release with fixes here https://github.com/sirensolutions/sentinl/releases/tag/tag-6.4.2-0

**Comment by fbaligand** [comment]
@sergibondarenko 
After test, I don't see any change for this issue  : 
- in watchers list screen, there is still no link to convert a wizzard to an advanced watcher.
- but there is still the link "Convert to advanced" in the "Watcher query" tab

**Comment by sergibondarenko** [comment]
@fbaligand the link was not moved. I'll do it in the next iteration
