### ISSUE TITLE
Defining TLS certificate when sending webhook over HTTPS.

### ISSUE THREAD

**Issue by AlbertasG** [lmangani/sentinl#563]
1. Sentinl and Kibana version 

**Versions: 6.2.4**

2. Issue description

Sending webhook over HTTPS does not verify certificate. 

3. Reproducing the issue step-by-step

Sending webhook to 443 over HTTPS

4. Expected results vs. actual results

Oct  4 10:17:01 localhost kibana: {"type":"log","@timestamp":"2018-10-04T08:17:01Z","tags":["error","Sentinl","260bc7e0-c71f-11e8-be6a-11f7e362e294"],"pid":23143,"message":"fail to ship webhook, Error: unable to verify the first certificate"}

5. Sample of data

6. Full watcher document

```
{
  "actions": {
    "Webhook_47e5b521-fbf2-48fd-ab2a-88062ad8c60d": {
      "name": "Webhook",
      "throttle_period": "1m",
      "webhook": {
        "priority": "low",
        "stateless": false,
        "method": "POST",
        "host": "ticketingsystem.example.com",
        "port": "443",
        "use_https": true,
        "path": "/api/now/table/em_event",
        "body": "{\"source\": \"ELK_ALARM\",\r\n      \"node\": \"Health\",\r\n      \"metric_name\": \"Service is not running\",\r\n      \"type\": \"Calculate_Availability\",\r\n      \"severity\": \"5\",\r\n      \"message_key\": \"timestamp_123_Testing-REST-Ignore\",\r\n      \"description\": \"{{watcher.title}} {{payload.hits.total}} \"\r\n    \r\n}\r\n",
        "params": {
          "watcher": "{{watcher.title}}",
          "payload_count": "{{payload.hits.total}}"
        },
        "headers": {
          "Content-Type": "application/json",
          "Authorization": "Basic Zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz=="
        },
        "auth": "",
        "message": "AAAAAA bad"
      }
    }
  }
```

7. Additional details

I see there is configuration of TLS for Email, but there is no entry for webhook. I tried to configure 
elasticsearch.ssl.certificateAuthorities and enabling elasticsearch.ssl.verificationMode: none which didn't worked as well.

**Comment by sergibondarenko** [comment]
@AlbertasG you are right, it doesn't work now. We will fix it

**Comment by Martina526** [comment]
@sergibondarenko 
Could you please let me know if this bug got resolved or not? I am also seeing this issue when try to integrate sentinl feature with our ticket system.

**Comment by Martina526** [comment]
@AlbertasG 
Hi Albert, could you share with me if there is a workaround for this issue?

**Comment by AlbertasG** [comment]
@Martina526 workaround could be setting up apache/nginx proxy which encrypts your HTTP traffic and forwards to your HTTPS endpoint.

**Comment by sergibondarenko** [comment]
@Martina526 
Put the following to your kibana.yml
```
sentinl:
  settings:
    webhook:
      active: true
      use_https: true
```

**Comment by Martina526** [comment]
Hi Sergii,

Is sentinl already able to avoid the SSL certificate by this?

Thanks for your reply!

Regards,
Muyun

**Comment by sergibondarenko** [comment]
@Martina526 do you want to accept a self-assigned certificate? It is not supported yet. I'll add support and let you know.

**Comment by sangeethsuseelan** [comment]
Any solutions/workaround for the above issue?

**Comment by MichalM07** [comment]
Hello, 
Is  this still  online ?  as  i also   am  getting this error.  Any  solution  to  fix  this ? 
got  a  valid  SSL  implemented to  my kibana,  but  sentinl  still fails  to  send  webhooks  over  https
