### ISSUE TITLE
Sending reports from websites with proxy authentication

### ISSUE THREAD

**Issue by WolfCastIO** [lmangani/sentinl#568]
**Kibana version:**
6.3
**Elasticsearch version:**
6.3
**Server OS version:**
CentOS / LINUX

**Question**

Hey guys,

How can I create a report from a website which is behind a proxy and needs credentials before access them? Cause my installation of kibana is secured by a proxy with authentication.

Best regards,
Robert

**Comment by sergibondarenko** [comment]
Hi @Grashee 
We don't have the proxy support yet. We will implement it soon.
