### ISSUE TITLE
Elastic Search Client connection is using default requestTimeout value

### ISSUE THREAD

**Issue by smlam** [lmangani/sentinl#569]
**Kibana version:**
5.6.x

**Elasticsearch version:**
5.6.x

**Server OS version:**

**Browser version:**

**Browser OS version:**

**Original install method (e.g. release pkg link, gulp, from source, etc.):**

**Describe the bug:**

**Steps to reproduce:**
1. For some query more than 30s
2. POST http://localhost:XXXX/target_index/_search => socket hang up

**Expected behavior:**

**Sample of data you have in Elasticsearch**

**Full watcher document**

**Screenshots (if relevant):**

**Errors in browser console (if relevant):**

**Provide Kibana logs and/or server output (if relevant):**

**Any additional context:**
In https://github.com/sirensolutions/sentinl/blob/master/server/lib/get_elasticsearch_client.js#L44,
It do not set requestTimeout and always use 30s default value.

Reference:
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html
```

**Comment by sergibondarenko** [comment]
Please provide the following info:
1. Full watcher document
2. A sample of data you have in Elasticsearch
