### ISSUE TITLE
Sentinl and Cross Cluster Search

### ISSUE THREAD

**Issue by IbaiAlonso** [lmangani/sentinl#573]
Hi!

I could not find any kind of documentation to work with Cross Cluster Search. This feature is available?

**Comment by sergibondarenko** [comment]
@IbaiAlonso no, the cross cluster search is not implemented yet.

**Comment by IbaiAlonso** [comment]
Hi @sergibondarenko,
Thank you for you answer. Do you have it in your roadmap in future releases?

**Comment by IbaiAlonso** [comment]
ETA, please? I will be your first lab rat.

**Comment by IbaiAlonso** [comment]
Hi!

I have just found that you have realesed a new beta version. Does this version work with CCS?

Thanks!

**Comment by sergibondarenko** [comment]
Hi. No, but this issue is on the to-do list.

**Comment by alexvvladimirov** [comment]
Actually CCS is already working (at least in 6.6.1).

I specify the following query in input section of the watcher. It searches across both local (filebeat-*) and remote cluster (*:filebeat-*) indices.
```
  "input": {
    "search": {
      "request": {
        "index": [
          "filebeat-*,*:filebeat-*"
        ],
        "body": {
          "query": {
            "ids": {
              "values": [
                "1678550090",
                "4016855981"
              ]
            }
          }
        }
      }
    }
  }
```
To make sure it works, I specially used doc ids from both clusters. This query returns 2 results.
