### ISSUE TITLE
reports: mail subject and content ignored

### ISSUE THREAD

**Issue by lbesuchet** [lmangani/sentinl#577]
**Kibana version:**
6.2.4

**Elasticsearch version:**
6.2.4

**Report engine:**
puppeteer

**Describe the bug:**
when sending a report, Subject & Content fields are ignored

**Steps to reproduce:**
1. Setup a report using wizard, fill Subject & Content fields
2. Generate the report

**Expected behavior:**
Resulting email Subject & Content should match what has been defined.
Actually:
email subject = "SENTINL: " + report "Title"
email content = empty, only the attachment is present

**Comment by xiongzeng** [comment]
I encountered the same problem in 6.3.0,Which version is now working properly?

**Comment by xiongzeng** [comment]
I encountered the same problem in 6.3.0, which version is now working properly.

**Comment by xiongzeng** [comment]
Hello,Sergii Bondarenko
I am a loyal user of sentinl. And  I encountered the same problem in 6.3.0 ,but Report engine is
horseman）, which version is now working properly. I look forward to hearing from you。

**Comment by xiongzeng** [comment]
Hello,Sergii Bondarenko
I am a loyal user of sentinl. And  I encountered the same problem in 6.3.0 ,but Report engine is
horseman）, which version is now working properly. I look forward to hearing from you。

**Comment by sergibondarenko** [comment]
Guys the fix is currently under QA tests in the private repository. I'll let you know when it is available.

**Comment by xiongzeng** [comment]
Thanks,I look forward to your reply as soon as possible.

**Comment by lbesuchet** [comment]
> Actually:
> email subject = "SENTINL: " + report "Title"
> email content = empty, only the attachment is present

Tested with the latest 6.4.2 release:
-> email subject now taken into account
-> email content still empty, only the attachment is present

**Comment by smartrics** [comment]
This issue is also present in 6.5.1
