### ISSUE TITLE
Notification Center and Sentinl doesnot work in version 5.6.4

### ISSUE THREAD

**Issue by anchalarora12** [lmangani/sentinl#586]
Hi Team,

I have been using Sentiln plugin for quite some time. When i installed [notification_center](https://github.com/sw-jung/kibana_notification_center), sentiln plugin is not working with below error 
 
`commons.bundle.js?v=15571:38 Error: [$injector:unpr] Unknown provider: $uibModalProvider <- $uibModal <- WatchersController
http://errors.angularjs.org/1.4.7/$injector/unpr?p0=%24uibModalProvider%20%3C-%20%24uibModal%20%3C-%20WatchersController`
 
Please help me out.

**Comment by sergibondarenko** [comment]
Reinstall Sentinl from the link below and let me know
https://github.com/sirensolutions/sentinl/releases/download/tag-5.6.2/sentinl-v5.6.4.zip

**Comment by sergibondarenko** [comment]
I changed one thing, try the fix https://github.com/sirensolutions/sentinl/releases/download/tag-5.6.2/sentinl-v5.6.4-issue-586.zip

**Comment by bharathphatak** [comment]
I am also facing same issue. Tried with above build.Below error while loading watchers

![image](https://user-images.githubusercontent.com/15992491/47709225-d2b1d200-dc55-11e8-972c-a9e47de496ba.png)

**Comment by sergibondarenko** [comment]
But what happens if you uninstall `notification_center` app. Does Sentinl work without this app?
