### ISSUE TITLE
Support of Elasticsearch SQL for Watcher configuration

### ISSUE THREAD

**Issue by WolfCastIO** [lmangani/sentinl#589]
Hey guys,

I just want to ask you if Elasticsearch SQL is planned for the watcher configuration?
I think this could help many guys to configure there watchers. 

Best regards,
Robert

**Comment by Grashee** [comment]
Hey @lmangani 

The elasticsearch team added the SQL support with version 6.3.0 for all versions (there are special things which are just availlable with XPACK, but its availlable, also the translator). 
As reference follow the release notes of the elasticsearch team: https://www.elastic.co/guide/en/elasticsearch/reference/6.4/release-notes-6.3.0.html

But its good to know that your team has also a variant.

**Comment by lmangani** [comment]
XPACK is licensed in a "free access" manner but it is not open source - there is a big difference in there ;)

**Comment by fbaligand** [comment]
@lmangani
I fully agree with you :)
I don’t master elastic license rights to use : if sentinl provides features based on elastic licensed (free) features, would it be a juridic issue ?

**Comment by lmangani** [comment]
Quite frankly I don't know what using those XPACK API might mean in terms of licensing and cross-linking plus the SIREN stack already offers much greater possibilities on that front (and many others) so this is not a priority. SENTINL comes with its own sample SQL to ES converter and this can sure be extended to provide a similar experience without any dependency if enough people are interested.

**Comment by jccq** [comment]
just my2c If the free version offers a REST api sentinl can call it just
fine
so contributions welcome :) . In Siren we'll evenctually have a SQL with
joins etc for now its an extention to the Elastic DSL .Of course one can go
via other third parties apache open sourced SQL on Elasticsearch
https://github.com/NLPchina/elasticsearch-sql  (seems to be quite
maintained) or heave weight via Dremio.

**Comment by fbaligand** [comment]
@jccq 
Indeed, Elastic XPACK SQL provides a REST API to execute SQL queries.

**Comment by lmangani** [comment]
@fbaligand we do too ;)
