### ISSUE TITLE
Advanced editor should concern only "input query" and "condition" sections

### ISSUE THREAD

**Issue by fbaligand** [lmangani/sentinl#593]
Currently, in the wizzard editor, when we are on "Match condition" section, if we click on "Convert to advanced" link, we globally go from "a full wizzard" mode to "a full json" mode.
it means that we loose ease to edit global watcher settings and actions, which is quite frustrating and painful.

Actually, the only watcher parts that are interesting to convert to "advanced mode" is "input query" and "condition".
These only two watcher parts are implied by "Match Condition" section.

So here's my suggestion : 
When user clicks on "Convert to advanced", it implies : 
- the same global wizzard editor
- in "Match Condition" section, WHEN/FIELDTIME/OVER/... editors are hidden
- in "Match Condition" section, "Chart" tab is hidden
- in "Match Condition" section, "Chart query" tab is hidden
- in "Match Condition" section, a new "Input query" tab is displayed and shows a writable JSON editor to edit watcher "input"
- in "Match Condition" section, a new "Condition" tab is displayed and shows a writable JSON editor to edit watcher "condition"

Doing so, we can fully benefit both "wizzard" ease and "JSON edition" power ! 
This would be greatly useful !

**Comment by lmangani** [comment]
Hi @fbaligand based on your previous suggestions, we're adding more features to the advanced mode and partitioning of its blocks as in the former versions. Watch this space for updates and to help us test!

**Comment by fbaligand** [comment]
Great to hear this @lmangani !
I’m ready to test it and give you feedback !

**Comment by shamil** [comment]
@lmangani count me in as well. Really hard to use advacned watcher at the moment...

**Comment by shamil** [comment]
@lmangani any updates on the subject? This is really holding us to upgrade from older version.

**Comment by sergibondarenko** [comment]
@shamil @fbaligand it is almost ready, one feature and tests are left.

**Comment by shamil** [comment]
@sergibondarenko sorry for nagging. This feature is what holding us from upgrading to new Sentinl and in General to newer versions of Elasticsearch. 

Is this soon to be released? Or is there any old version (without the wizard feature) that supports newer version of Elasticsearch? (6.5+)
