### ISSUE TITLE
Remove "Elastic" action (as it is a duplicate of "Console" action)

### ISSUE THREAD

**Issue by fbaligand** [lmangani/sentinl#594]
Currently, there are both "Console" and "Elastic" available actions, that have the same options, and generate the same output document in "watcher_alarms" index.

As they do the same thing, and "Elastic" action is a confusing action name, I suggest to remove it, which lets to not confuse users.

**Comment by lmangani** [comment]
@fbaligand I generally agree, but would rather repurpose Console to only output in Kibana perhaps, to facilitate CI and the like. Opinions here?

**Comment by fbaligand** [comment]
You mean "console" will only write a Kibana log, with no storage in Elasticsearch ?
It means you can't get it in SENTINL Alarms.
But why not, it would be equivalent to "Logging" action in Elastic Alerting.

Anyway, whatever the chosen way to achieve it, it is important to not have 2 actions that do the same thing.
