### ISSUE TITLE
Watchers: Watcher play: An internal server error occurred

### ISSUE THREAD

**Issue by aabababb** [lmangani/sentinl#601]
<!--
Thanks for taking time to report an issue.
Please fill all the following fields to make sure we have all the data we need to help you.
This section will NOT appear in your Issue report!

#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |   6.2.4      |
| Elasticsearc |     6.2.4    |
| Server OS    |    centos7     |
| Browser      |        firefox56 |

#### Original Install Method

- [ ] Release pkg link

#### Bug Description
Error: Watcher play: An internal server error occurred
_callee/<@http://172.19.0.244/bundles/sentinl.bundle.js?v=16627:20:488296
tryCatch@http://172.19.0.244/bundles/vendors.bundle.js?v=16627:63:99703
makeInvokeMethod/<@http://172.19.0.244/bundles/vendors.bundle.js?v=16627:63:101781
defineIteratorMethods/</prototype[method]@http://172.19.0.244/bundles/vendors.bundle.js?v=16627:63:99985
step@http://172.19.0.244/bundles/sentinl.bundle.js?v=16627:20:484342
step/<@http://172.19.0.244/bundles/sentinl.bundle.js?v=16627:20:484511
notify/</<@http://172.19.0.244/bundles/vendors.bundle.js?v=16627:63:66473
notify/<@http://172.19.0.244/bundles/vendors.bundle.js?v=16627:63:66199
flush@http://172.19.0.244/bundles/vendors.bundle.js?v=16627:63:71214
#### Steps to Reproduce
'input": {
    "search": {
      "request": {
        "index": [
          "metricbeat-*"
        ],
        "body": {
          "query": {
            "bool": {
              "must": [
                {
                  "query": {
                    "query_string": {
                      "query": "system.filesystem.used.pct:[0.9 TO 10]"
                    }
                  }
                },
                {
                  "range": {
                    "@timestamp": {
                      "gte": "now-5m",
                      "lte": "now",
                      "format": "epoch_millis"
                    }
                  }
                }
              ],
              "must_not": []
            }
          }
        }
      }
    }
  },'

this will  have error

but in dev toll

GET metricbeat-*/_search
{
    "query": {
        "query_string": {
            "query": "system.filesystem.used.pct:[0.96  TO 1]"
        }
    }
}

can get data

'hits": {
    "total": 1907,
    "max_score": 1,
    "hits": [
      {
        "_index": "metricbeat-2018.10.29",
        "_type": "doc",
        "_id": "L6MhvWYBuBHUevm5UAxN",
        "_score": 1,
        "_source": {
          "metricset": {
            "rtt": 1724,
            "name": "filesystem",
            "module": "system"
          },
          "beat": {
            "name": "DS-HXSERVER01",
            "version": "6.2.4",
            "hostname": "DS-HXSERVER01"
          },
          "host": "DS-HXSERVER01",
          "@timestamp": "2018-10-29T00:02:47.900Z",
          "system": {
            "filesystem": {
              "files": 0,
              "used": {
                "bytes": 6335075782656,
                "pct": 0.9603
              },
              "mount_point": "/aplus/dw_2_aplus",
              "total": 6596660817920,
              "device_name": "//172.17.70.100/aplus/dw_2_aplus",
              "free_files": 0,
              "type": "cifs",
              "free": 261585035264,
              "available": 261585035264
            }
          },
          "@version": "1",
          "beatType": "metricbeat",
          "tags": [
            "beats_input_raw_event"
          ],
          "remote_ip": "172.19.0.51"
        }
      },
'

**Comment by aabababb** [comment]
GET metricbeat-*/_search
{
    "query": {
        "query_string": {
            "query": "system.filesystem.used.pct:[0.96  TO 1]"
        }
    }
}

**Comment by aabababb** [comment]
hits": {
    "total": 1907,
    "max_score": 1,
    "hits": [
      {
        "_index": "metricbeat-2018.10.29",
        "_type": "doc",
        "_id": "L6MhvWYBuBHUevm5UAxN",
        "_score": 1,
        "_source": {
          "metricset": {
            "rtt": 1724,
            "name": "filesystem",
            "module": "system"
          },
          "beat": {
            "name": "DS-HXSERVER01",
            "version": "6.2.4",
            "hostname": "DS-HXSERVER01"
          },
          "host": "DS-HXSERVER01",
          "@timestamp": "2018-10-29T00:02:47.900Z",
          "system": {
            "filesystem": {
              "files": 0,
              "used": {
                "bytes": 6335075782656,
                "pct": 0.9603
              },
              "mount_point": "/aplus/dw_2_aplus",
              "total": 6596660817920,
              "device_name": "//172.17.70.100/aplus/dw_2_aplus",
              "free_files": 0,
              "type": "cifs",
              "free": 261585035264,
              "available": 261585035264
            }
          },
          "@version": "1",
          "beatType": "metricbeat",
          "tags": [
            "beats_input_raw_event"
          ],
          "remote_ip": "172.19.0.51"
        }
      },

**Comment by aabababb** [comment]
input": {
    "search": {
      "request": {
        "index": [
          "metricbeat-*"
        ],
        "body": {
          "query": {
            "bool": {
              "must": [
                {
                  "query": {
                    "query_string": {
                      "query": "system.filesystem.used.pct:[0.9 TO 10]"
                    }
                  }
                },
                {
                  "range": {
                    "@timestamp": {
                      "gte": "now-5m",
                      "lte": "now",
                      "format": "epoch_millis"
                    }
                  }
                }
              ],
              "must_not": []
            }
          }
        }
      }
    }
  },

**Comment by aabababb** [comment]
Error: Watcher play: An internal server error occurred
_callee/<@http://172.19.0.244/bundles/sentinl.bundle.js?v=16627:20:488296
tryCatch@http://172.19.0.244/bundles/vendors.bundle.js?v=16627:63:99703
makeInvokeMethod/<@http://172.19.0.244/bundles/vendors.bundle.js?v=16627:63:101781
defineIteratorMethods/</prototype[method]@http://172.19.0.244/bundles/vendors.bundle.js?v=16627:63:99985
step@http://172.19.0.244/bundles/sentinl.bundle.js?v=16627:20:484342
step/<@http://172.19.0.244/bundles/sentinl.bundle.js?v=16627:20:484511
notify/</<@http://172.19.0.244/bundles/vendors.bundle.js?v=16627:63:66473
notify/<@http://172.19.0.244/bundles/vendors.bundle.js?v=16627:63:66199
flush@http://172.19.0.244/bundles/vendors.bundle.js?v=16627:63:71214

**Comment by aabababb** [comment]
Dev Tools  can get the data,but sentinl get the error...

**Comment by havlan** [comment]
@aabababb Please use some time to format your posts so that they are readable for us, it becomes much easier to help you.
Could you post some logs from your error? And reformat your previous posts/logs/configs in this issue with github markdown code insertion?
![screenshot from 2018-11-01 20-45-03](https://user-images.githubusercontent.com/18334546/47875520-0a1bac80-de17-11e8-965c-65fe40925407.png)

**Comment by aabababb** [comment]
> 
> 
> @aabababb Please use some time to format your posts so that they are readable for us, it becomes much easier to help you.
> Could you post some logs from your error? And reformat your previous posts/logs/configs in this issue with github markdown code insertion?
> ![screenshot from 2018-11-01 20-45-03](https://user-images.githubusercontent.com/18334546/47875520-0a1bac80-de17-11e8-965c-65fe40925407.png)

sorry,how to format code?
'''
not work
'''
error log is not this?

Error: Watcher play: An internal server error occurred
_callee/<@http://172.19.0.244/bundles/sentinl.bundle.js?v=16627:20:488296

**Comment by sergibondarenko** [comment]
@aabababb Thanks for taking time to report an issue.
Please fill all the following fields to make sure we have all the data we need to help you. 
Also, make sure you use the latest release we issued 3 days ago  https://github.com/sirensolutions/sentinl/releases

**Tips:**

1. If your watcher is not executed, try to query Elasticsearch manually first. Do you receive the results you want for your query?
For example, on Linux, you can query Elasticsearch using `curl`:

curl -X GET "localhost:9200/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": { 
    "match_all": {}
  }
}
'
-->


### System Details
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |         |
| Elasticsearc |         |
| Server OS    |         |
| Browser      |         |

#### Original Install Method

- [ ] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

### Bug Details
#### Bug Description

#### Steps to Reproduce
1.
1.
1.

#### Expected Behavior

#### Sample of data you have in Elasticsearch
```
```

#### Full Watcher JSON
```
```

#### Screenshots (if relevant)

#### Errors in Browser Console (if relevant)
```
```

#### Kibana logs and/or server output (attached if relevant)

#### Any additional information

**Comment by sergibondarenko** [comment]
> and how to find the sentinl log ?
> error log is not this?

Every time you see `An internal server error occurred` un UI, look at Kibana log to find more about the error.

**Comment by sergibondarenko** [comment]
Also, look at the releases https://github.com/sirensolutions/sentinl/releases. We put updated packages with fixes there. And recently we are focused on handling errors better.
