### ISSUE TITLE
Help with watcher , add hostname on message

### ISSUE THREAD

**Issue by victorbuttner** [lmangani/sentinl#606]
Hello guys,

I'm trying to create an alert with the hostname of the service that triggered it. I've created an watch by wizard using metribeat index patern grouped by beat.hostname.
How Can I add the hostname in to the message ? 
There is my watcher

``` 
{
  "actions": {
    "Slack_alarm_108e21e0-813c-409f-ab7d-013f64b819a5": {
      "name": "Slack alarm",
      "throttle_period": "1m",
      "slack": {
        "priority": "high",
        "stateless": false,
        "message": "Atenção {{watcher.title}} em um ?????(SERVERNAME)??? verifique as métricas no Kibana",
        "channel": "#alerts"
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "metricbeat*"
        ],
        "body": {
          "query": {
            "bool": {
              "filter": {
                "range": {
                  "@timestamp": {
                    "gte": "now-15m/m",
                    "lte": "now/m",
                    "format": "epoch_millis"
                  }
                }
              }
            }
          },
          "size": 0,
          "aggs": {
            "bucketAgg": {
              "terms": {
                "field": "beat.name",
                "size": 3,
                "order": {
                  "_count": "desc"
                }
              },
              "aggs": {
                "metricAgg": {
                  "avg": {
                    "field": "system.memory.actual.used.pct"
                  }
                },
                "dateAgg": {
                  "date_histogram": {
                    "field": "@timestamp",
                    "time_zone": "Europe/Amsterdam",
                    "interval": "1m",
                    "min_doc_count": 1
                  },
                  "aggs": {
                    "metricAgg": {
                      "avg": {
                        "field": "system.memory.actual.used.pct"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.aggregations.bucketAgg.buckets.some(b => b.dateAgg.buckets.some(b => b.metricAgg.value>=0.7))"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 2 minutes"
    }
  },
  "disable": false,
  "report": false,
  "title": "Memória acima de 70%",
  "wizard": {
    "chart_query_params": {
      "queryType": "average",
      "scheduleType": "every",
      "over": {
        "field": "beat.name",
        "type": "top",
        "n": 3
      },
      "last": {
        "n": 15,
        "unit": "minutes"
      },
      "interval": {
        "n": 1,
        "unit": "minutes"
      },
      "timezoneName": "Europe/Amsterdam",
      "threshold": {
        "n": 0.7,
        "direction": "above eq"
      },
      "timeField": "@timestamp",
      "field": "system.memory.actual.used.pct"
    }
  },
  "save_payload": false,
  "spy": false,
  "impersonate": false
}
```

**Comment by sergibondarenko** [comment]
Do you have the hostname in the Elasticsearch response? If yes, use mustache syntax to get it for the message. Here is the mustache playground https://mustache.github.io/#demo to try syntax

**Comment by victorbuttner** [comment]
> Do you have the hostname in the Elasticsearch response? If yes, use mustache syntax to get it for the message. Here is the mustache playground https://mustache.github.io/#demo to try syntax

I'm not sure about it, this is  my first time using seninl, did you know if the hostname are in the payload ? and how I can explode this object to see what is comming with it?

**Comment by sergibondarenko** [comment]
To see what wizard watcher returns
1. Go to "Watchers" tab
2. Find your watcher and click "play button" on the right 
![screenshot from 2018-11-13 16-54-36](https://user-images.githubusercontent.com/5389745/48425318-df115100-e764-11e8-9dbf-4fbd9fb5c450.png)
3. Go to "Alarms" tab and expand the alarm. You will see the Elasticsearch data aggregated under "aggregations"
![screenshot from 2018-11-13 16-51-45](https://user-images.githubusercontent.com/5389745/48425415-18e25780-e765-11e8-9bdb-6e01e23df5ef.png)

Basic Sentinl workflow is the following one (look at the watcher doc you posted every time you see a word formatted like code, `code`):
1. You create a watcher, advanced or wizard.
2. Sentinl executes the watcher automatically by the specified `schedule`. Also, you can trigger it manually clicking on the "play button" in "Watchers" tab.
3. Watcher uses [Elasticsearch DSL Query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html) in the `input` to search for data.
4. Watcher checks if the data satisfy the defined `condition`. If the data satisfy the condition, the watcher performs the `actions`, `slack` message in your example. There can be multiple actions: email, slack, webhook etc.

I recommend you to familiarise with the following things first
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html
https://sentinl.readthedocs.io/en/latest/

**Comment by victorbuttner** [comment]
Thank you @sergibondarenko .
 I'm doing the alarm in the wizard but on my watcher details I cant see the same as you sent. 
![image](https://user-images.githubusercontent.com/17817146/48430842-62c44100-e757-11e8-9c36-57f8e453095e.png)
 My conditions are working as I expect and the alarm are being send. I just want to put in the message the hostname that I used on group like the print bellow
![image](https://user-images.githubusercontent.com/17817146/48430988-bcc50680-e757-11e8-9de2-7bf2d6a67b82.png)

**Comment by sergibondarenko** [comment]
The action was throttled. Decrease the throttle period in your action settings. Then trigger the watcher again.

**Comment by victorbuttner** [comment]
I'm using KIbana version 6.4.0 
In my alarms the payload maybe are not being parsed correctly, take a look on the message bellow (it cames with default html template
![image](https://user-images.githubusercontent.com/17817146/48493576-379f2780-e813-11e8-989b-1bdc2ea2ab8f.png)
Check that are missing informations on the message for example `{{in index {{watcher.wizard.chart_query_params.index}}` 
![image](https://user-images.githubusercontent.com/17817146/48493662-67e6c600-e813-11e8-9b29-c34a30cc9f75.png)

**Comment by victorbuttner** [comment]
I'm using KIbana version 6.4.0 
In my alarms the payload maybe are not being parsed correctly, take a look on the message bellow (it cames with default html template
![image](https://user-images.githubusercontent.com/17817146/48493576-379f2780-e813-11e8-989b-1bdc2ea2ab8f.png)
Check that are missing informations on the message for example `{{in index {{watcher.wizard.chart_query_params.index}}`

**Comment by sergibondarenko** [comment]
Please, try to paste the following into the "Content" textarea
```
<p>Hi {{watcher.username}}</p>
<p>There are {{payload.hits.total}} results found by the watcher <i>{{watcher.title}}</i>.</p>

<div style="color:grey;">
  <hr />
  <p>This watcher sends alerts based on the following criteria:</p>
  <ul><li>{{watcher.wizard.chart_query_params.queryType}} of {{watcher.wizard.chart_query_params.over.type}} over the last {{watcher.wizard.chart_query_params.last.n}} {{watcher.wizard.chart_query_params.last.unit}} {{watcher.wizard.chart_query_params.threshold.direction}} {{watcher.wizard.chart_query_params.threshold.n}} in index {{watcher.wizard.chart_query_params.index}}</li></ul>
</div>
```
Do you see this in the "Preview" after you paste the code above
![screenshot from 2018-11-22 10-11-13](https://user-images.githubusercontent.com/5389745/48892729-0049ff80-ee3f-11e8-9315-7dc9db0cb0f2.png)

If yes, there is a mistake in your mustache syntax. 

To-do
1. Look at the [mustache manual](https://mustache.github.io/mustache.5.html).
2. Test your mustache with the data you have here https://mustache.github.io/#demo
