### ISSUE TITLE
Allow lucene query language to create watcher searches.

### ISSUE THREAD

**Issue by camAtGitHub** [lmangani/sentinl#608]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |   6.4.2      |
| Elasticsearc |    6.4.2       |
| Server OS    |     Docker    |
| Browser      |    -     |

#### Original Install Method

- Other:  Docker

#### Bug Description
Allow lucene query language to create watcher searches.
I'd hope that I could use a Kibana / Lucene search like: "program:sshd authresult:failure" to populate the watcher data.

Instead I have to triverse the Elasticsearch documentation, smash my head against a brick wall of trial and error for something that should be trivial.

#### Steps to Reproduce
1. Think of easy Kibana search like "program:sshd authresult:failure"
1. Try to implement trivial alert like "if greater than 3 per minute > email"
1. Make head explode trying to work out the Elasticsearch DSL

#### Expected Behavior
Easy alert syntax.
Head to not explode.

#### Sample of data you have in Elasticsearch
```
{
  "_index": "logstash-2018-11-15",
  "_type": "doc",
  "_id": "dKIAFWcBOO_aW3gBcUcU",
  "_version": 1,
  "_score": null,
  "_source": {
    "ssh_protocol": "ssh2",
    "host": "server-bst1",
    "ssh_authmethod": "password",
    "program": "sshd",
    "pid": "10072",
    "message": "Failed password for invalid user user from 1.2.3.4 port 42932 ssh2",
    "@timestamp": "2018-11-15T01:33:22.748Z",
    "user": "user",
    "logsource": "server-bst1",
    "type": "auth",
    "source": "/var/log/secure",
    "prospector": {},
    "src_ip": "1.2.3.4",
    "src_port": 42932,
    "sourcetype": "linux_secure",
    "authresult": "failure",
    "geoip": {
      "country_name": "China",
      "ip": "1.2.3.4",
      "location": {
        "lon": 116.3883,
        "lat": 39.9289
      },
      "country_code3": "CN",
      "longitude": 116.3883,
      "latitude": 39.9289,
      "region_code": "11",
      "timezone": "Asia/Shanghai",
      "country_code2": "CN",
      "region_name": "Beijing",
      "continent_code": "AS",
      "city_name": "Beijing"
    },
    "beat": {},
    "ssh_failreason": "unknown_user",
    "tags": [
      "rhel7",
      "authentication"
    ]
  },
```

Thanks

**Comment by sergibondarenko** [comment]
Nice feature request. I've added it to the queue.
