### ISSUE TITLE
Schedule mode disapears after saving with "text" mode

### ISSUE THREAD

**Issue by lbesuchet** [lmangani/sentinl#609]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       | 6.4.3        |
| Elasticsearch | 6.4.3        |
| Browser      | Chrome, Firefox        |

#### Original Install Method

- Release pkg link: https://github.com/sirensolutions/sentinl/releases/download/tag-6.4.2-0/sentinl-v6.4.3.zip

#### Steps to Reproduce
1. Create a watcher and set schedule mode: text, text: at 18:00 (or any value other than the default 'at 15:35', which does not reproduce this issue ...)
2.  Save this watcher => INTERVAL correctly shows 'at 18:00'
3. Edit this watcher => Schedule mode dropdown is empty, text input is not there...

**Comment by sergibondarenko** [comment]
I see it. It is a bug. Will be fixed.
