### ISSUE TITLE
How to use sentinl plugin to implement appears “java.lang.OutOfMemoryError” , the content of the send mail show which server has problem ?

### ISSUE THREAD

**Issue by wangyu8460958** [lmangani/sentinl#615]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |     5.5.2    |
| Elasticsearc |   5.5.2      |
| Server OS    |   Amazon Linux AMI release 2018.03      |
| Browser      |    Chrome     |

I use the following metrics and buckets to query which server have "java.lang.OutOfMemoryError" and count the number of events. 

![101](https://user-images.githubusercontent.com/34674414/48831187-46588200-edb1-11e8-869d-db9c1955a76b.png)

![102](https://user-images.githubusercontent.com/34674414/48831217-5a9c7f00-edb1-11e8-95f7-bcf9366dae31.png)

Then I use select "Watcher" , then I click "set alarm" button: 

![103](https://user-images.githubusercontent.com/34674414/48831944-f8dd1480-edb2-11e8-90ba-6ec91ab27ac5.png)

The General of Editor is:

![104](https://user-images.githubusercontent.com/34674414/48831988-114d2f00-edb3-11e8-9f82-5d179d31286a.png)

The Input of Editor is:
```
{
   "search": {
    "request": {
      "index": [
        "<filebeat-{now/d}>",
        "<filebeat-{now/d-1d}>"
      ],
      "body": {
        "size": 0,
        "query": {
          "bool": {
            "must": [
              {
                "query_string": {
                  "query": "\"java.lang.OutOfMemoryError\"",
                  "analyze_wildcard": true
                }
              },
              {
                "range": {
                  "@timestamp": {
                    "from": "now-1h"
                  }
                }
              }
            ],
            "must_not": []
          }
        },
        "_source": {
          "excludes": []
        },
        "aggs": {
          "hostname": {
            "terms": {
              "field": "beat.hostname.keyword",
              "size": 5,
              "order": {
                "_count": "desc"
              }
            }
           }
        }
      }
    }
  }
}
```

According to this link：
https://github.com/sirensolutions/sentinl/issues/277

The content of Condition is :  
![image](https://user-images.githubusercontent.com/34674414/48888326-4e75f780-ee6d-11e8-8253-b443aa289181.png)

The content of  Transform is : 
![image](https://user-images.githubusercontent.com/34674414/48888454-b593ac00-ee6d-11e8-8355-2dc6528bb646.png)

The content of Actions is :
![109](https://user-images.githubusercontent.com/34674414/48886808-45cef280-ee68-11e8-8cc0-afca05570998.png)

Can the above configuration be implemented when "out of memory" appears in Kibana, the name of each server that has "out of memory" will be displayed in the alarm message?

**Comment by sergibondarenko** [comment]
> Can the above configuration be implemented when "out of memory" appears in Kibana, the name of each server that has "out of memory" will be displayed in the alarm message?

Yes, if you have this "out of memory" info in Elasticsearch. What is the problem exactly? Can you get this data from Elasticsearch using DSL query?
