### ISSUE TITLE
Can't get payload.hits.total when one of the indexes is empty

### ISSUE THREAD

**Issue by trujillobrenes** [lmangani/sentinl#618]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |   5.6.3      |
| Elasticsearc |    5.6.3     |

#### Bug Description
In the provided example, if Both indexes have logs, the email is sent, with payload.hits.total containing the total logs from both indexes. But if one of them is empty, running the watcher gives an internal server error. Not sure if this is a bug or that I'm not using it correctly, but I would expect payload.hits.total to contain the total logs from the non empty index or even 0 when both are empty.

Thanks a lot for the help

#### Full Watcher JSON
```
{
  "_index": "watcher",
  "_type": "sentinl-watcher",
  "_id": "rwrrdrq500n-7k4ez4fmyud-imuva27wm6",
  "_version": 1,
  "found": true,
  "_source": {
    "title": "temp",
    "disable": false,
    "report": false,
    "trigger": {
      "schedule": {
        "later": "every 5 mins"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "<my-index-{now/d}>",
            "<my-index-{now/d-1d}>"
          ],
          "body": {}
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 0"
      }
    },
    "actions": {
      "email_admin": {
        "throttle_period": "0h15m0s",
        "email": {
          "to": "alarm@localhost",
          "from": "sentinl@localhost",
          "subject": "Sentinl Alarm",
          "priority": "high",
          "body": "Found {{payload.hits.total}} Events"
        }
      }
    },
    "transform": {}
  }
}
```

#### Kibana logs 
"Condition 'script' error for 400m0b7ymly-gmqh69inyhj-ob8wu59mxf: TypeError: Cannot read property 'total' of undefined"

**Comment by trujillobrenes** [comment]
I can avoid the internal server error with the condition "script": "true" but then the email sends "Found  Events"

**Comment by sergibondarenko** [comment]
I've built a new v5.6.x release with bug fixes, please try it and let me know https://github.com/sirensolutions/sentinl/releases/tag/tag-5.6.x

**Comment by trujillobrenes** [comment]
Thank you very much. Its taking me some time to upgrade the version but I will tell you as soon as it's done.

Meanwhile, I was able to avoid the issue temporary checking every index and then appying a filter

```
...
      "search": {
        "request": {
          "index": [
            "<my-index-*>"
          ],
          "body": {
            "query": {
              "bool": {
                "must": {
                  "range": {
                    "@timestamp": {
                      "gte": "now-1d/d",
                      "lt": "now/d"
                    }
                  }
                }
              }
            }
          }
        }
      }
...  
```

**Comment by sergibondarenko** [comment]
Nice one!
