### ISSUE TITLE
action throttled, watcher id: undefined, action name

### ISSUE THREAD

**Issue by dev-liub** [lmangani/sentinl#640]
HI all,
i want to config a watcher,send alarm with mail or webhoot.
but i Can't receive information，There are some errors in the log，Is that the reason?
kibana Version: 6.4.2
sentinl  Version: 6.4.2
log error：
```
{"type":"log","@timestamp":"2018-12-13T05:37:38Z","tags":["warning","Sentinl","watcher 941ab760-fe14-11e8-85bd-d7e12a93c34f"],"pid":29635,"message":"Siren federate: \"elasticsearch.plugins\" is not available when running from kibana: Error: Unknown config key: investigate_core.clusterplugins"}
{"type":"log","@timestamp":"2018-12-13T05:37:38Z","tags":["info","Sentinl"],"pid":29635,"message":"action throttled, watcher id: undefined, action name: Email_alarm_ae6fdbf1-d3c3-44d4-8067-e9549e151f6e"}
{"type":"log","@timestamp":"2018-12-13T05:37:38Z","tags":["info","Sentinl"],"pid":29635,"message":"action throttled, watcher id: undefined, action name: Webhook_114e21dc-715e-4128-ad2a-34779049843d"}
```

my watcher like this:
```
{
  "actions": {
    "Email_alarm_ae6fdbf1-d3c3-44d4-8067-e9549e151f6e": {
      "name": "Email alarm",
      "throttle_period": "15m",
      "email": {
        "priority": "low",
        "stateless": false,
        "body": "发生了退款失败",
        "to": "liuax01@vanke.com",
        "subject": "退款失败邮件说明",
        "from": "p-vkyykfbwxkfpt@vanke.com"
      }
    },
    "Webhook_114e21dc-715e-4128-ad2a-34779049843d": {
      "name": "Webhook",
      "throttle_period": "1m",
      "webhook": {
        "priority": "high",
        "stateless": false,
        "method": "POST",
        "host": "oapi.dingtalk.com",
        "port": "443",
        "path": "/robot/send?access_token=688b6f8d5c744c4c3dedf0696d7b85cf1351e4b127fac917dfa1158bd1805502",
        "body": "{\n  \"watcher\": \"{{watcher.title}}\",\n  \"payload_count\": \"{{payload.hits.total}}\"\n}",
        "params": {
          "watcher": "{{watcher.title}}",
          "payload_count": "{{payload.hits.total}}"
        },
        "headers": {
          "Content-Type": "application/json"
        },
        "auth": "",
        "message": "",
        "use_https": true
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "fluent.test.eps*"
        ],
        "body": {
          "query": {
            "bool": {
              "must": [
                {
                  "match": {
                    "message": "退款"
                  }
                }
              ],
              "filter": [
                {
                  "range": {
                    "@timestamp": {
                      "gte": "now-1h",
                      "lt": "now"
                    }
                  }
                }
              ]
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total > 1"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 10 minutes"
    }
  },
  "disable": false,
  "report": false,
  "title": "watcher_title2",
  "save_payload": true,
  "spy": false,
  "impersonate": false
}
```

**Comment by sergibondarenko** [comment]
> ["warning","Sentinl","watcher 941ab760-fe14-11e8-85bd-d7e12a93c34f"],"pid":29635,"message":"Siren federate: \"elasticsearch.plugins\" is not available when ...

It is not an error, it is a warning. Please don't pay attention to it. It is related only to Siren Investgate (a Kibana fork). And we are going to deprecate this message in the nearest future.

>  i Can't receive information
Do you have any message in Alarms tab?

Manually execute the watcher, copy **all Kibana log** and paste it here.

**Comment by dev-liub** [comment]
this is log,
"pid":31200,"method":"get","statusCode":200,"req":{"url":"/api/sentinl/time","method":"get","headers":{"host":"10.0.73.20:5601","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"6.4.2","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","referer":"http://10.0.73.20:5601/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.9,en;q=0.8"},"remoteAddress":"10.39.230.122","userAgent":"10.39.230.122","referer":"http://10.0.73.20:5601/app/sentinl"},"res":{"statusCode":200,"responseTime":1,"contentLength":9},"message":"GET /api/sentinl/time 200 1ms - 9.0B"}
{"type":"response","@timestamp":"2018-12-13T10:13:51Z","tags":[],"pid":31200,"method":"get","statusCode":304,"req":{"url":"/ui/favicons/favicon-32x32.png","method":"get","headers":{"host":"10.0.73.20:5601","connection":"keep-alive","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","accept":"image/webp,image/apng,image/*,*/*;q=0.8","referer":"http://10.0.73.20:5601/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.9,en;q=0.8","if-none-match":"\"8e183c2e644fb050707d89402e1f7a120a95e4d2\"","if-modified-since":"Wed, 26 Sep 2018 13:41:31 GMT"},"remoteAddress":"10.39.230.122","userAgent":"10.39.230.122","referer":"http://10.0.73.20:5601/app/sentinl"},"res":{"statusCode":304,"responseTime":1,"contentLength":9},"message":"GET /ui/favicons/favicon-32x32.png 304 1ms - 9.0B"}
{"type":"response","@timestamp":"2018-12-13T10:13:51Z","tags":[],"pid":31200,"method":"get","statusCode":304,"req":{"url":"/ui/favicons/favicon-16x16.png","method":"get","headers":{"host":"10.0.73.20:5601","connection":"keep-alive","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","accept":"image/webp,image/apng,image/*,*/*;q=0.8","referer":"http://10.0.73.20:5601/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.9,en;q=0.8","if-none-match":"\"13b869be5df4bdc56920edc16a28e67a7c08203b\"","if-modified-since":"Wed, 26 Sep 2018 13:41:31 GMT"},"remoteAddress":"10.39.230.122","userAgent":"10.39.230.122","referer":"http://10.0.73.20:5601/app/sentinl"},"res":{"statusCode":304,"responseTime":2,"contentLength":9},"message":"GET /ui/favicons/favicon-16x16.png 304 2ms - 9.0B"}
{"type":"response","@timestamp":"2018-12-13T10:13:51Z","tags":[],"pid":31200,"method":"post","statusCode":200,"req":{"url":"/api/sentinl/list/watchers","method":"post","headers":{"host":"10.0.73.20:5601","connection":"keep-alive","content-length":"0","accept":"application/json, text/plain, */*","origin":"http://10.0.73.20:5601","kbn-version":"6.4.2","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","referer":"http://10.0.73.20:5601/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.9,en;q=0.8"},"remoteAddress":"10.39.230.122","userAgent":"10.39.230.122","referer":"http://10.0.73.20:5601/app/sentinl"},"res":{"statusCode":200,"responseTime":7,"contentLength":9},"message":"POST /api/sentinl/list/watchers 200 7ms - 9.0B"}
{"type":"response","@timestamp":"2018-12-13T10:13:51Z","tags":[],"pid":31200,"method":"get","statusCode":304,"req":{"url":"/ui/favicons/favicon-32x32.png","method":"get","headers":{"host":"10.0.73.20:5601","connection":"keep-alive","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","accept":"image/webp,image/apng,image/*,*/*;q=0.8","referer":"http://10.0.73.20:5601/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.9,en;q=0.8","if-none-match":"\"8e183c2e644fb050707d89402e1f7a120a95e4d2\"","if-modified-since":"Wed, 26 Sep 2018 13:41:31 GMT"},"remoteAddress":"10.39.230.122","userAgent":"10.39.230.122","referer":"http://10.0.73.20:5601/app/sentinl"},"res":{"statusCode":304,"responseTime":0,"contentLength":9},"message":"GET /ui/favicons/favicon-32x32.png 304 0ms - 9.0B"}
{"type":"response","@timestamp":"2018-12-13T10:13:51Z","tags":[],"pid":31200,"method":"get","statusCode":304,"req":{"url":"/ui/favicons/favicon-16x16.png","method":"get","headers":{"host":"10.0.73.20:5601","connection":"keep-alive","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","accept":"image/webp,image/apng,image/*,*/*;q=0.8","referer":"http://10.0.73.20:5601/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.9,en;q=0.8","if-none-match":"\"13b869be5df4bdc56920edc16a28e67a7c08203b\"","if-modified-since":"Wed, 26 Sep 2018 13:41:31 GMT"},"remoteAddress":"10.39.230.122","userAgent":"10.39.230.122","referer":"http://10.0.73.20:5601/app/sentinl"},"res":{"statusCode":304,"responseTime":1,"contentLength":9},"message":"GET /ui/favicons/favicon-16x16.png 304 1ms - 9.0B"}
{"type":"response","@timestamp":"2018-12-13T10:13:53Z","tags":[],"pid":31200,"method":"post","statusCode":200,"req":{"url":"/api/sentinl/watcher/941ab760-fe14-11e8-85bd-d7e12a93c34f","method":"post","headers":{"host":"10.0.73.20:5601","connection":"keep-alive","content-length":"0","accept":"application/json, text/plain, */*","origin":"http://10.0.73.20:5601","kbn-version":"6.4.2","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","referer":"http://10.0.73.20:5601/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.9,en;q=0.8"},"remoteAddress":"10.39.230.122","userAgent":"10.39.230.122","referer":"http://10.0.73.20:5601/app/sentinl"},"res":{"statusCode":200,"responseTime":4,"contentLength":9},"message":"POST /api/sentinl/watcher/941ab760-fe14-11e8-85bd-d7e12a93c34f 200 4ms - 9.0B"}
{"type":"log","@timestamp":"2018-12-13T10:13:53Z","tags":["info","Sentinl","watcher 941ab760-fe14-11e8-85bd-d7e12a93c34f"],"pid":31200,"message":"executing"}
{"type":"log","@timestamp":"2018-12-13T10:13:53Z","tags":["warning","Sentinl","watcher 941ab760-fe14-11e8-85bd-d7e12a93c34f"],"pid":31200,"message":"Siren federate: \"elasticsearch.plugins\" is not available when running from kibana: Error: Unknown config key: investigate_core.clusterplugins"}
{"type":"log","@timestamp":"2018-12-13T10:13:53Z","tags":["info","Sentinl","watcher 941ab760-fe14-11e8-85bd-d7e12a93c34f"],"pid":31200,"message":"successfully applied condition"}
{"type":"log","@timestamp":"2018-12-13T10:13:53Z","tags":["info","Sentinl","watcher 941ab760-fe14-11e8-85bd-d7e12a93c34f"],"pid":31200,"message":"no transform found"}
{"type":"log","@timestamp":"2018-12-13T10:13:53Z","tags":["info","Sentinl","watcher 941ab760-fe14-11e8-85bd-d7e12a93c34f"],"pid":31200,"message":"successfuly executed"}
{"type":"response","@timestamp":"2018-12-13T10:13:53Z","tags":[],"pid":31200,"method":"post","statusCode":200,"req":{"url":"/api/sentinl/watcher/_execute","method":"post","headers":{"host":"10.0.73.20:5601","connection":"keep-alive","content-length":"1332","accept":"application/json, text/plain, */*","origin":"http://10.0.73.20:5601","kbn-version":"6.4.2","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","content-type":"application/json;charset=UTF-8","referer":"http://10.0.73.20:5601/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.9,en;q=0.8"},"remoteAddress":"10.39.230.122","userAgent":"10.39.230.122","referer":"http://10.0.73.20:5601/app/sentinl"},"res":{"statusCode":200,"responseTime":53,"contentLength":9},"message":"POST /api/sentinl/watcher/_execute 200 53ms - 9.0B"}
{"type":"log","@timestamp":"2018-12-13T10:13:53Z","tags":["info","Sentinl"],"pid":31200,"message":"sending email"}
{"type":"log","@timestamp":"2018-12-13T10:14:43Z","tags":["error","Sentinl"],"pid":31200,"message":"watcher_title2: email action : send email : timedout while connecting to smtp server: Error: timedout while connecting to smtp server\n    at module.exports (/home/liuax01/elasticsearch/kibana-6.4.2-linux-x86_64/plugins/sentinl/node_modules/emailjs/smtp/error.js:3:13)\n    at Socket.timedout (/home/liuax01/elasticsearch/kibana-6.4.2-linux-x86_64/plugins/sentinl/node_modules/emailjs/smtp/response.js:32:29)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:106:13)\n    at Socket.emit (events.js:208:7)\n    at Socket._onTimeout (net.js:410:8)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)"}

**Comment by dev-liub** [comment]
This log only has wenhoot,but i Can't receive information
{"type":"log","@timestamp":"2018-12-13T10:19:12Z","tags":["info","Sentinl","watcher 941ab760-fe14-11e8-85bd-d7e12a93c34f"],"pid":31200,"message":"executing"}
{"type":"log","@timestamp":"2018-12-13T10:19:12Z","tags":["warning","Sentinl","watcher 941ab760-fe14-11e8-85bd-d7e12a93c34f"],"pid":31200,"message":"Siren federate: \"elasticsearch.plugins\" is not available when running from kibana: Error: Unknown config key: investigate_core.clusterplugins"}
{"type":"log","@timestamp":"2018-12-13T10:19:12Z","tags":["info","Sentinl","watcher 941ab760-fe14-11e8-85bd-d7e12a93c34f"],"pid":31200,"message":"successfully applied condition"}
{"type":"log","@timestamp":"2018-12-13T10:19:12Z","tags":["info","Sentinl","watcher 941ab760-fe14-11e8-85bd-d7e12a93c34f"],"pid":31200,"message":"no transform found"}
{"type":"log","@timestamp":"2018-12-13T10:19:12Z","tags":["info","Sentinl","watcher 941ab760-fe14-11e8-85bd-d7e12a93c34f"],"pid":31200,"message":"successfuly executed"}
{"type":"response","@timestamp":"2018-12-13T10:19:12Z","tags":[],"pid":31200,"method":"post","statusCode":200,"req":{"url":"/api/sentinl/watcher/_execute","method":"post","headers":{"host":"10.0.73.20:5601","connection":"keep-alive","content-length":"1061","accept":"application/json, text/plain, */*","origin":"http://10.0.73.20:5601","kbn-version":"6.4.2","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","content-type":"application/json;charset=UTF-8","referer":"http://10.0.73.20:5601/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.9,en;q=0.8"},"remoteAddress":"10.39.230.122","userAgent":"10.39.230.122","referer":"http://10.0.73.20:5601/app/sentinl"},"res":{"statusCode":200,"responseTime":50,"contentLength":9},"message":"POST /api/sentinl/watcher/_execute 200 50ms - 9.0B"}

**Comment by sergibondarenko** [comment]
> This log only has webhoot,I think it's a success,but i Can't receive information

Test the webhook server using `curl`, for example
```
curl -XPOST -k https://oapi.dingtalk.com/robot/send?access_token=688b6f8d5c744c4c3dedf0696d7b85cf1351e4b127fac917dfa1158bd1805502 -H 'Content-Type: application/json' -d '{"test":"true"}'
```

**Comment by dev-liub** [comment]
test 
This format is good.
curl -XPOST -k https://oapi.dingtalk.com/robot/send?access_token=688b6f8d5c744c4c3dedf0696d7b85cf1351e4b127cation/json' -d ' {"msgtype": "text",   "text": {  "content": "test2" } }'
{"errmsg":"ok","errcode":0}

curl -XPOST -k https://oapi.dingtalk.com/robot/send?access_token=688b6f8d5c744c4c3dedf0696d7b85cf1351e4b127fac917dfa1158bd1805502 -H 'Content-Type: application/json' -d '{"test":"true"}'                                     
{"errmsg":"msgtype  is null","errcode":300001}
[@iZ94itf91vkZ elasticsearch]$ curl -XPOST -k https://oapi.dingtalk.com/robot/send?access_token=688b6f8d5c744c4c3dedf0696d7b85cf1351e4b127cation/json' -d ' {"msgtype": "text",   "text": {  "content": "test2" } }'

[@iZ94itf91vkZ elasticsearch]$

**Comment by dev-liub** [comment]
Thanks very much!，Webhoot has been resolved，Email, I'll look for the reason again.
