### ISSUE TITLE
Readonlyrestplugin compatibility 

### ISSUE THREAD

**Issue by tobymaro** [lmangani/sentinl#641]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |    6.4.1     |
| Elasticsearc |       6.4.1  |
| Server OS    |  Centos 7   |
| Browser      |    Opera     |

### Bug Details

I'm using ROR to secure my ELK stack. I installed Sentinl plugin. Here is Sentinl configuration:

```sentinl:
  es:
    host: localhost
    port: '9200'
    protocol: https
  settings:
    authentication:
      enabled: true
      password: kibana
      username: kibana
    email:
      active: true
      host: localhost
    report:
      active: true
server.host: 0.0.0.0
```
ROR  kibana:

```  
   - name: kibana
    auth_key: kibana:kibana
    verbosity: error
```

#### Bug Description

When I go to  Sentinl tab from Kibana I got:

> Watchers: list watchers : list watcher : [undefined] Forbidden by ReadonlyREST ES plugin

When I try to save watcher I get the same error. In logs I see message:

> [2018-12-13T10:32:54,827][INFO ][t.b.r.a.ACL              ] FORBIDDEN by default req={ ID:973644401-838243157#51342, TYP:SearchRequest, CGR:N/A, USR:[no basic auth header], BRS:false, KDX:null, ACT:indices:data/read/search, OA:127.0.0.1, DA:127.0.0.1, IDX:.kibana, MET:POST, PTH:/.kibana/_search?size=50&from=0, CNT:<OMITTED, LENGTH=82>, HDR:{Connection=keep-alive, content-type=application/json, Host=localhost:9200, Content-Length=82}, HIS:[kibana->[auth_key->false]], [logstash->[auth_key->false]], [elastic->[auth_key->false]], [developer->[auth_key->false]], [developer2->[auth_key->false]], [developer3->[proxy_auth->false]], [test->[proxy_auth->false]], [workaround->[actions->false]] }

#### Steps to Reproduce

Go to Sentinl tab and try to save watcher

**Comment by sergibondarenko** [comment]
Here is an example for the ReadonlyREST config https://github.com/sirensolutions/sentinl/issues/600#issuecomment-436206452

**Comment by tobymaro** [comment]
The issue here is not related to permissions. Issue is related to problem with header.

 USR:[no basic auth header].
