### ISSUE TITLE
pdf/png dropdown not working

### ISSUE THREAD

**Issue by smartrics** [lmangani/sentinl#643]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |     6.5.1    |
| Elasticsearc |    6.5.1     |
| Server OS    |    Linux     |
| Browser      |     Chrome  71.0.3554.0    |

#### Original Install Method

- [ x] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

### Bug Details
when creating a new report action the dropdown to select the type isn't working. it does expand but when selecting "pdf", the value sticks to "png"

#### Steps to Reproduce
1. create a report action
1. try select "pdf"

#### Expected Behavior
after dropdown expands and user selects pdf, the value selected in the dropdown should change to pdf 

#### Errors in Browser Console (if relevant)
none seen in devtool/console

**Comment by sergibondarenko** [comment]
I can reproduce this.

**Comment by smartrics** [comment]
and this https://github.com/sirensolutions/sentinl/issues/646
