### ISSUE TITLE
How can I add the CC email

### ISSUE THREAD

**Issue by chaishiqi** [lmangani/sentinl#647]
### How can I add the CC email?

Usually when I add a cc item to the action fragment on X-Pack,it worked,like this

```
    "actions": {
      "Email_test": {
        "throttle_period": "0h3m0s",
        "email_html": {
          "to": "aaa@123.com",
          "cc": "bbb@123.com",
          "from": "xxx@123.com",
          "subject": "xxx",
          "body": "nothing to say",
        }
```
But it doesn't work on the sentinl sphere,only the mail aaa@123.com receive the mail.How can I attain my goal?

**Comment by sergibondarenko** [comment]
The is no such possibility for now. But you can have multiple emails in `to`, for example
```
"to": "aaa@123.com, trex@cave.com"
```

**Comment by chaishiqi** [comment]
Thanks for your answer.By now if the current version doesn't support CC item,I have to config like yours
