### ISSUE TITLE
<table  border="1">  No effect

### ISSUE THREAD

**Issue by ithjz** [lmangani/sentinl#664]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |     6.5.3    |
| Elasticsearc |        6.5.3    |

#### Original Install Method

- [ ] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

#### Steps to Reproduce
1.
1.
1.

#### Sample of data you have in Elasticsearch
```I want to configure tables in the template of configuring mail, but I found no wireframe. Did I leave the tables by default?
```
<table  border="1">  No effect

#### Full Watcher JSON
```
```

#### Errors in Browser Console (if relevant)
```
```

**Comment by ithjz** [comment]
![_20190116185506](https://user-images.githubusercontent.com/15103507/51244690-a38f3f00-19c0-11e9-98ea-ca24d8d720b1.png)

**Comment by ithjz** [comment]
<table  border="1">  
<tr>
  <td>{{payload.hits.hits.0._source.srcObj}}</td>
  <td>{{payload.hits.hits.0._source.destObj}}</td>
![_20190116185921](https://user-images.githubusercontent.com/15103507/51244783-e8b37100-19c0-11e9-94e8-c0cf2611ae75.png)

**Comment by sergibondarenko** [comment]
Please add more description in English.
