### ISSUE TITLE
execute wizard watcher: Error: input search: Error: Request Timeout after 60000ms

### ISSUE THREAD

**Issue by aabababb** [lmangani/sentinl#668]
test

**Comment by aabababb** [comment]
> It is essential to look in Kibana log when there is something wrong. Make sure you have `logging.verbose: true` in kibana.yml, execute the watcher and paste the log here.
> 
> Also, query Elasticsearch separately and see if there is any result. Paste the result here too. Try the following query in Linux terminal. Put your own Kibana server name/ip and port.
> 
> ```
> curl -X GET "localhost:9200/_search" -H 'Content-Type: application/json' -d'
> {
>   "query": {
>     "bool": {
>       "must": [
>         {
>           "query_string": {
>             "analyze_wildcard": true,
>             "query": "loglevel:ERROR OR message:*error*"
>           }
>         },
>         {
>           "range": {
>             "@timestamp": {
>               "gte": "now-2m",
>               "lte": "now",
>               "format": "epoch_millis"
>             }
>           }
>         }
>       ],
>       "must_not": []
>     }
>   },
>   "aggs": {
>     "dateAgg": {
>       "date_histogram": {
>         "field": "@timestamp",
>         "time_zone": "Asia/Shanghai",
>         "interval": "1m",
>         "min_doc_count": 1
>       }
>     }
>   }
> }
> '
> ```
> PS
> We develop a new functionality to query watcher and get results in UI, stay tuned.

now
logging.verbose: true

but where is the kibana.log?

query result is
{"took":1724,"timed_out":false,"_shards":{"total":461,"successful":461,"skipped":460,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]},"aggregations":{"dateAgg":{"buckets":[]}}}

**Comment by sergibondarenko** [comment]
Ok, you have no results. But it is not a wizard, it is an advanced watcher, you don't see any chart, you see only a text editor, right? If it is true, delete `"wizard": {}` from the watcher.
How did you create this watcher?

**Comment by aabababb** [comment]
> Ok, you have no results. But it is not a wizard, it is an advanced watcher, you don't see any chart, you see only a text editor, right? If it is true, delete `"wizard": {}` from the watcher.
> How did you create this watcher?

I use this but can't get web data
http://172.19.0.24:5601/app/sentinl#/watcher/raw/advanced/new%20?_g=()

so use 
http://172.19.0.24:5601/app/sentinl#/watcher/wizard/new?_g=()


    Watcher query -> Convert to advanced -> save Watcher
copy the old Watcher JSON on it.
