### ISSUE TITLE
Sentinl Watcher  problem

### ISSUE THREAD

**Issue by Blady123** [lmangani/sentinl#675]
Hello, 
I have a problem with sentinl 6.4.3 
I want create a watcher that allows me to send an email if the value of the "event_ID" field is 8
Can you help me pliz ? :)
I follow the step in #527 for the save watcher but i have this error 

![7](https://user-images.githubusercontent.com/47316018/52347598-9a731a00-2a22-11e9-9286-5c40d528fc15.png)
![8](https://user-images.githubusercontent.com/47316018/52347778-12d9db00-2a23-11e9-9ec6-e32f18f0239a.png)

![error sentinl](https://user-images.githubusercontent.com/47316018/52348717-461d6980-2a25-11e9-978a-527f4a8a4658.png)

**Comment by sergibondarenko** [comment]
Your watcher syntax is wrong, you shouldn't specify `range` outside the condition
The correct syntax:
```
{
  "condition": {
    "script": {
      "script": "payload.hits.total > 0"
    },
    "range": {
      "field_to_check": "Amount",
      "min": 50,
      "max": 150,
      "tolerance": 5
    }
  }
}
```

**Comment by Blady123** [comment]
I see this conf but that's not what I'm looking for
Is it possible to send an email for a specific value of a field ?

thank for your help :)

**Comment by sergibondarenko** [comment]
sure, it is possible, for example, if you want to trigger an alert whenever there are docs with `amount` equal to 10 do this
```
{
  "condition": {
    "script": {
      "script": "payload.hits.hits.filter(doc => doc._source.amount === 10).length > 0"
    }
  }
}
```
In script you can put any JavaScript you want.

Or use `array_compare`
```
"condition": {
  "array_compare": {
    "payload.hits.hits" : { 
      "path": "_source.amount" ,
      "eq": { 
        "value": 10, 
      }
    }
  }
}
```
The docs https://sentinl.readthedocs.io/en/latest/Watcher-Anatomy/#condition

**Comment by Blady123** [comment]
Thank verry much i go test this

**Comment by Blady123** [comment]
I test the 2 "condition" but  for this:
{
  "condition": {
    "script": {
      "script": "payload.hits.hits.filter(doc => doc.MYFIELD.amount === 10).length > 0"
    }
  },
![sentinl3](https://user-images.githubusercontent.com/47316018/52429671-ccf54380-2b04-11e9-8e38-d22bc0d6e79a.png)
and in my alarms 
![sentinl4](https://user-images.githubusercontent.com/47316018/52429704-e1d1d700-2b04-11e9-8bbe-08dd34c8a223.png)

For the second 
  "condition": {
    "array_compare": {
      "payload.hits.hits": {
        "path": "MYFIELD.amount",
        "eq": {
          "value": 10
        }
      }
    }
  },
![sentinl](https://user-images.githubusercontent.com/47316018/52429809-16de2980-2b05-11e9-9b55-1ba12d5800b6.png)

Did i make mistake ?

**Comment by sergibondarenko** [comment]
No mistake. The message says you don't have any doc with MYFIELD === 10
