### ISSUE TITLE
Watcher does not triggered automatically.

### ISSUE THREAD

**Issue by koinoyokan17** [lmangani/sentinl#678]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |5.6.9|
| Elasticsearc |5.6.14|
| Server OS    |Ubuntu 16 x64|
| Browser      |Latest Google Chrome|

#### Original Install Method

- [+] Release pkg link
- [ ] Gulp
- [ ] Source

#### Bug Description
I'm trying to set up some basic watchers, but they are not triggered automatically. Here is some info I have.

#### Steps to Reproduce
1. Set up sentinl to your Kibana instance.
2. Create a new watcher
3. Wait till it will be triggered due to the schedule you've set.

#### Expected Behavior
Action should be triggered.

#### Sample of data you have in Elasticsearch
```
{
  "_index": "dev.mylab.rri-2019.02.06",
  "_type": "kafka_bread",
  "_id": "AWjMyiaIEthqbro13kuT",
  "_version": 1,
  "_score": null,
  "_source": {
    "Timestamp": "2019-02-08T13:07:05.2833337+02:00",
    "Level": "Information",
    "MessageTemplate": "{EntityType} saved. Key={EntityId}, DataVersion={DataVersion}",
    "RenderedMessage": "\"Hello\" saved. Key=16485057, DataVersion=92",
    "Properties": {
      "EntityType": "Frustration",
      "EntityId": 16485057,
      "DataVersion": 92,
      "SourceContext": "Going.MakerBread.Amker.Accumulation.Frustration.Manager",
      "Scope": [
        "c4478002f0ad4b01a6994f408f274810"
      ],
      "ThreadId": 384,
      "MachineName": "MAKERBREAD-TT1",
      "app": "amker",
      "env": "Development",
      "product": "maker-bread"
    },
    "@timestamp": "2019-02-08T11:07:06.177019209+00:00"
  },
  "fields": {
    "Timestamp": [
      1549624025283
    ],
    "@timestamp": [
      1549624026177
    ]
  },
  "sort": [
    1549624026177
  ]
}
```

#### Full Watcher JSON
```
{
  "actions": {
    "Slack_alarm_03bddf45-78c1-4c38-afb9-05b12cca2b88": {
      "name": "Slack alarm",
      "throttle_period": "1m",
      "slack": {
        "priority": "low",
        "stateless": false,
        "message": "test",
        "channel": "#rr_live"
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "dev.mylab.rri-*"
        ],
        "body": {
          "query": {
            "bool": {
              "filter": {
                "range": {
                  "@timestamp": {
                    "gte": "now-15m/m",
                    "lte": "now/m",
                    "format": "epoch_millis"
                  }
                }
              }
            }
          },
          "size": 0,
          "aggs": {
            "dateAgg": {
              "date_histogram": {
                "field": "@timestamp",
                "time_zone": "Europe/Amsterdam",
                "interval": "1m",
                "min_doc_count": 1
              }
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.aggregations.dateAgg.buckets.some(b => b.doc_count>=0)"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 2 minutes"
    }
  },
  "disable": false,
  "report": false,
  "title": "watcher_title",
  "save_payload": true,
  "spy": false,
  "impersonate": false
}
```

#### Kibana logs and/or server output (attached if relevant)
[kibana.txt](https://github.com/sirensolutions/sentinl/files/2844840/kibana.txt)

#### Any additional information
[kibana.config.txt](https://github.com/sirensolutions/sentinl/files/2844842/kibana.config.txt)

Timestamp field is present in the index I'm trying to watch. Similar issues were checked out by me and I still can't find the reason why it doesn't work.

**Comment by cemkuleyin** [comment]
hi,

i installed sentinl 5.6.9. But my alert does not triggered. Can you solve this issue?

Thanks,

Cem

**Comment by sreekanth-ragi** [comment]
Hi Team,

We are seeing a similar issue with the following 

Kibana: 5.6.16
ES: 5.6.16

Alerting is working when manually triggered but auto alerting is not working.

Thanks,
Sreekanth

**Comment by jsRuner** [comment]
Hi Team,

We are seeing a similar issue with the following

kibana:5.6.5
elasticsearch:5.6.5

Alerting is working when manually triggered but auto alerting is not working.

Thanks,
jsrunner

**Comment by mingziV5** [comment]
same problem in kibana 5.6.8
