### ISSUE TITLE
Escaping single quotes in emails?

### ISSUE THREAD

**Issue by DumSkidderik** [lmangani/sentinl#681]
Is there a way to escape single quotes in alert emails?
I've got everything up and running, but would like to include a link to a related Kibana search.
I'll edit the URL to the search to dynamically include _source.host.name, which also works.

But the single quotes (') get replaced with double quotes (") in the HTML body, which is a problem for the Kibana URL as it contains a lot of single quotes.

**Original URL:**
`<p>Please <a href='http://my-kibana/app/kibana#/discover/ec2339a0-2f88-11e9-8a88-41b55f3260b1?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&amp;_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'winlogbeat-*',key:event_id,negate:!f,params:!('1000'),type:phrases,value:'1,000'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(event_id:'1000')))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'winlogbeat-*',key:level,negate:!f,params:(query:Error,type:phrase),type:phrase,value:Error),query:(match:(level:(query:Error,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'winlogbeat-*',key:host.hostname,negate:!f,params:(query:{{payload.hits.hits.0._source.host.name}},type:phrase),type:phrase,value:{{payload.hits.hits.0._source.host.name}}),query:(match:(host.hostname:(query:{{payload.hits.hits.0._source.host.name}},type:phrase))))),index:'winlogbeat-*',interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',desc))'>visit Kibana</a> for more information!</p>`

**And the one in the email generated by sentinl:**
`<p>Please <a href="http://pc-bvh:5601/app/kibana#/discover/ec2339a0-2f88-11e9-8a88-41b55f3260b1?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&amp;_a=(columns:!(_source),filters:!((" $state?:(store:appState),meta:(alias:!n,disabled:!f,index:?winlogbeat-*?,key:event_id,negate:!f,params:!(?1000?),type:phrases,value:?1,000?),query:(bool:(minimum_should_match:1,should:!((match_phrase:(event_id:?1000?)))))),(?$state?:(store:appState),meta:(alias:!n,disabled:!f,index:?winlogbeat-*?,key:level,negate:!f,params:(query:Error,type:phrase),type:phrase,value:Error),query:(match:(level:(query:Error,type:phrase)))),(?$state?:(store:appState),meta:(alias:!n,disabled:!f,index:?winlogbeat-*?,key:host.hostname,negate:!f,params:(query:PC-BVH,type:phrase),type:phrase,value:PC-BVH),query:(match:(host.hostname:(query:PC-BVH,type:phrase))))),index:?winlogbeat-*?,interval:auto,query:(language:lucene,query:??),sort:!(?@timestamp?,desc))?="">visit Kibana</a> for more information!</p>`

**Comment by lmangani** [comment]
Please try using the triple mustaches in your template.

**Comment by DumSkidderik** [comment]
Sorry for my late reply!

**Tried this:**
`</p><table cellspacing='10'><tbody><tr><td>Timestamp:</td><td>{{{payload.hits.hits.0._source.@timestamp}}}</td></tr><tr><td>Hostname:</td><td>{{{payload.hits.hits.0._source.host.name}}}</td></tr><tr><td>OS:</td><td>{{{payload.hits.hits.0._source.host.os.name}}}</td></tr><tr><td>EXE:</td><td>{{{payload.hits.hits.0._source.event_data.param11}}}</td></tr><tr><td>Exception:</td><td>{{{payload.hits.hits.0._source.event_data.param7}}}</td></tr></tbody></table><p>Please <a href='http://my-kibana/app/kibana#/discover/ec2339a0-2f88-11e9-8a88-41b55f3260b1?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&amp;_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'winlogbeat-*',key:event_id,negate:!f,params:!('1000'),type:phrases,value:'1,000'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(event_id:'1000')))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'winlogbeat-*',key:level,negate:!f,params:(query:Error,type:phrase),type:phrase,value:Error),query:(match:(level:(query:Error,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'winlogbeat-*',key:host.hostname,negate:!f,params:(query:{{{payload.hits.hits.0._source.host.name}}},type:phrase),type:phrase,value:{{{payload.hits.hits.0._source.host.name}}}),query:(match:(host.hostname:(query:{{{payload.hits.hits.0._source.host.name}}},type:phrase))))),index:'winlogbeat-*',interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',desc))'>visit Kibana</a> for more information!</p>`

**And the generated mail:**
`<p>Please <a href="http://my-kibana/app/kibana#/discover/ec2339a0-2f88-11e9-8a88-41b55f3260b1?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&amp;_a=(columns:!(_source),filters:!((" $state?:(store:appState),meta:(alias:!n,disabled:!f,index:?winlogbeat-*?,key:event_id,negate:!f,params:!(?1000?),type:phrases,value:?1,000?),query:(bool:(minimum_should_match:1,should:!((match_phrase:(event_id:?1000?)))))),(?$state?:(store:appState),meta:(alias:!n,disabled:!f,index:?winlogbeat-*?,key:level,negate:!f,params:(query:Error,type:phrase),type:phrase,value:Error),query:(match:(level:(query:Error,type:phrase)))),(?$state?:(store:appState),meta:(alias:!n,disabled:!f,index:?winlogbeat-*?,key:host.hostname,negate:!f,params:(query:PC-BVH,type:phrase),type:phrase,value:PC-BVH),query:(match:(host.hostname:(query:PC-BVH,type:phrase))))),index:?winlogbeat-*?,interval:auto,query:(language:lucene,query:??),sort:!(?@timestamp?,desc))?="">visit Kibana</a> for more information!</p>`

**Comment by nyssac** [comment]
Hello! I am having the same issue right now, were you able to find a solution @DumSkidderik @lmangani ? I would appreciate the help

**Comment by DumSkidderik** [comment]
> 
> 
> Hello! I am having the same issue right now, were you able to find a solution @DumSkidderik @lmangani ? I would appreciate the help

Sadly not, couldn't afford to put more time into researching it, so I just went with a simple link to the search in question, but no further filtering.
