### ISSUE TITLE
v6.6.1 installation fails after ELK 6.2.2 to 6.6.1 migration

### ISSUE THREAD

**Issue by GBL87** [lmangani/sentinl#693]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |    6.6.1     |
| Elasticsearch |    6.6.1     |
| Server OS    |    Windows Server 2016    |
| Browser      |    NA    |

#### Original Install Method
`..\bin\kibana-plugin.bat install https://github.com/sirensolutions/sentinl/releases/download/tag-6.6.0-0/sentinl-v6.6.1.zip`

#### Bug Description
Experiencing Sentinl installation issues coming from a previously installed and operational ELK stack 6.2.2 + Sentinl 6.2.2.
After a successful migration of of Elasticsearch and Kibana, the installation of the Sentinl v6.2.2 plugin fails on it's configuration used in v6.2.2.

#### Steps to Reproduce
1. Update Elasticsearch (https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html) and Kibana (https://www.elastic.co/guide/en/kibana/current/upgrade-standard.html) according to the documentation (copy all files to new versions as described, see added lines in kibana.yml which are Sentinl related below)
2. Boot up the new Elasticsearch instance. (successful)
3. Install  Sentinl through entering the following command:
`..\bin\kibana-plugin.bat install https://github.com/sirensolutions/sentinl/releases/download/tag-6.6.0-0/sentinl-v6.6.0.zip`

#### Expected Behavior
The installation of the Sentinl pugin is successful

#### Actual Behavior
The installation of the Sentinl plugin is not successful. It seems like the old configuration lines in the kibana.yml configuration file aren't recognized like in the old (v6.2.2) installation.

#### Sample of data you have in Elasticsearch
```
NA
```

#### Full Watcher JSON
```
NA
```

#### Screenshots (if relevant)
NA

#### Errors in Browser Console (if relevant)
```
NA
```

#### Kibana logs and/or server output (attached if relevant)

```
kibana.yml configuration file additions:
sentinl.es.host: 'localhost'
sentinl.es.port: 9200
sentinl.settings.email.active: true
sentinl.settings.emailactive: true
sentinl.settings.emailhost: smtp.*********
sentinl.settings.emailport: 25
sentinl.settings.emailuser: *********
sentinl.settings.emailpassword: *********
sentinl.settings.emailtls: false
```

Installation process outcome:
```
E:\Kibana\kibana-6.6.1-windows-x86_64\plugins>..\bin\kibana-plugin.bat install https://github.com/sirensolutions/sentinl/releases/download/tag-6.6.0-0/sentinl-v6.6.1.zip
Attempting to transfer from https://github.com/sirensolutions/sentinl/releases/download/tag-6.6.0-0/sentinl-v6.6.1.zip
Transferring 28084765 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Command failed: E:\Kibana\kibana-6.6.1-windows-x86_64\node\node.exe E:\Kibana\kibana-6.6.1-windows-x86_64\src\cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false

 FATAL  ValidationError: child "sentinl" fails because [child "es" fails because ["host" is not allowed], child "settings" fails because ["emailactive" is not allowed, "emailhost" is not allowed, "emailport" is not allowed, "emailuser" is not allowed, "emailpassword" is not allowed, "emailtls" is not allowed]]


{"type":"log","@timestamp":"2019-02-28T08:11:24Z","tags":["info","plugins-service"],"pid":6220,"message":"Plugin initialization disabled."}
{"type":"log","@timestamp":"2019-02-28T08:11:36Z","tags":["plugin","warning"],"pid":6220,"path":"E:\\Kibana\\kibana-6.6.1-windows-x86_64\\src\\legacy\\core_plugins\\ems_util","message":"Skipping non-plugin directory at E:\\Kibana\\kibana-6.6.1-windows-x86_64\\src\\legacy\\core_plugins\\ems_util"}
{"type":"log","@timestamp":"2019-02-28T08:11:37Z","tags":["fatal","root"],"pid":6220,"message":"{ ValidationError: child \"sentinl\" fails because [child \"es\" fails because [\"host\" is not allowed], child \"settings\" fails because [\"emailactive\" is not allowed, \"emailhost\" is not allowed, \"emailport\" is not allowed, \"emailuser\" is not allowed, \"emailpassword\" is not allowed, \"emailtls\" is not allowed]]\n    at Object.exports.process (E:\\Kibana\\kibana-6.6.1-windows-x86_64\\node_modules\\joi\\lib\\errors.js:196:19)\n    at internals.Object._validateWithOptions (E:\\Kibana\\kibana-6.6.1-windows-x86_64\\node_modules\\joi\\lib\\types\\any\\index.js:675:31)\n    at module.exports.internals.Any.root.validate (E:\\Kibana\\kibana-6.6.1-windows-x86_64\\node_modules\\joi\\lib\\index.js:146:23)\n    at Config._commit (E:\\Kibana\\kibana-6.6.1-windows-x86_64\\src\\server\\config\\config.js:139:35)\n    at Config.set (E:\\Kibana\\kibana-6.6.1-windows-x86_64\\src\\server\\config\\config.js:108:10)\n    at Config.extendSchema (E:\\Kibana\\kibana-6.6.1-windows-x86_64\\src\\server\\config\\config.js:81:10)\n    at extendConfigService (E:\\Kibana\\kibana-6.6.1-windows-x86_64\\src\\plugin_discovery\\plugin_config\\extend_config_service.js:45:10) name: 'ValidationError' }"}
```

**Comment by avinchakov** [comment]
I have the same issue

**Comment by tuian** [comment]
same 
```c
FATAL  ValidationError: child "sentinl" fails because [child "es" fails because ["host" is not allowed]]
```


Type | Version
-- | --
sentinl | 6.6.1(docker-compose)
Kibana | 6.6.1
Elasticsearch | 6.6.1
Host Server OS | Ubuntu 16.04

**Comment by avinchakov** [comment]
I simply remove all about elastic connection and it works with default))

**Comment by GBL87** [comment]
> I simply removed all about elastic connection and it works with default))

Confirmed.
Removing the es: .... block solved the issue. Migrated ES and Kibana are now fully operational.
Nonetheless it would come in handy if this would be mentioned somewhere in the docs.

**Comment by Amorik** [comment]
Removing the block does not solve the issue, it hides it. The default value is for localhost so of course removing it will work when running ES on the same node as Kibana, but not when ES is remote.

**Comment by O1dOne** [comment]
According to [this commit](https://github.com/sirensolutions/sentinl/commit/4494079f67bd78cc426491fcd8d07ea85395b3d7) to branch-6.6.0, "es.host" was changed to "es.hosts" with array of "host"s

Too bad it's not reflected in the docs, but the config fix is actually simple - change your 
```sentinl:
  es:
    host: 'eshost'
    port: 9200```
into smth like:
```sentinl:
  es:
    hosts:
    - host: 'eshost'
      port: 9200
```
