### ISSUE TITLE
Can not parse hostname to email

### ISSUE THREAD

**Issue by pr0j3ctz3r0** [lmangani/sentinl#695]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |      6.6.1   |
| Elasticsearc |    6.6.1      |
| Server OS    |     Ubuntu Xenial    |
| Browser      |     Chrome    |

#### Original Install Method

- [ ] Release pkg link - sentinl-v6.6.1.zip
- [ ] Gulp
- [ ] Source
- Other: 

#### Steps to Reproduce
1. Hi. First of all thanks for the great tool. I am trying to take hostname and parse it to email body. I did research for mustache and overall GitHub, still can not find the solution. First I attached the full watcher query. I used dev tools for getting a response and troubleshoot the problem. No luck. I want to take DETSERV01,DETSERV02 and etc. Really appreciate for your help
`  "aggregations" : {
    "bucketAgg" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "DETSERV01"`
1.
1.

#### Sample of data you have in Elasticsearch
``
```

#### Full Watcher JSON
```
`{
  "actions": {
    "Elasticsearch_alarm_96e3e8b4-4a97-4059-b3d7-0b14ba723983": {
      "name": "Elasticsearch alarmsssss",
      "throttle_period": "1s",
      "elastic": {
        "priority": "low",
        "stateless": false,
        "message": "Url\n{{payload.aggregations.bucketAgg.buckets.key}}\nsddsdsd"
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "metricbeat-*"
        ],
        "body": {
          "query": {
            "bool": {
              "filter": {
                "range": {
                  "@timestamp": {
                    "gte": "now-15m/m",
                    "lte": "now/m",
                    "format": "epoch_millis"
                  }
                }
              }
            }
          },
          "size": 0,
          "aggs": {
            "bucketAgg": {
              "terms": {
                "field": "beat.hostname",
                "size": 14,
                "order": {
                  "_count": "desc"
                }
              },
              "aggs": {
                "metricAgg": {
                  "avg": {
                    "field": "system.memory.actual.used.pct"
                  }
                },
                "dateAgg": {
                  "date_histogram": {
                    "field": "@timestamp",
                    "time_zone": "Europe/Amsterdam",
                    "interval": "1m",
                    "min_doc_count": 1
                  },
                  "aggs": {
                    "metricAgg": {
                      "avg": {
                        "field": "system.memory.actual.used.pct"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.aggregations.bucketAgg.buckets.some(b => b.dateAgg.buckets.some(b => b.metricAgg.value>=0.0432))"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 2 minutes"
    }
  },
  "disable": true,
  "report": false,
  "title": "High Memory Consumption",
  "wizard": {
    "chart_query_params": {
      "queryType": "average",
      "scheduleType": "every",
      "over": {
        "field": "beat.hostname",
        "n": 14,
        "type": "top"
      },
      "last": {
        "n": 15,
        "unit": "minutes"
      },
      "interval": {
        "n": 1,
        "unit": "minutes"
      },
      "timezoneName": "America/Detroit",
      "threshold": {
        "n": 0.0432,
        "direction": "above eq"
      },
      "timeField": "@timestamp",
      "field": "system.memory.actual.used.pct"
    }
  },
  "save_payload": false,
  "spy": false,
  "impersonate": false
}`
```

#### Screenshots (if relevant)

#### Errors in Browser Console (if relevant)
```
```

#### Kibana logs and/or server output (attached if relevant)

#### Any additional information
DEV TOOLS REQUEST:
`GET _search
{
  "query": {
    "bool": {
      "filter": {
        "range": {
          "@timestamp": {
            "gte": "now-15m/m",
            "lte": "now/m",
            "format": "epoch_millis"
          }
        }
      }
    }
  },
  "size": 0,
  "aggs": {
    "bucketAgg": {
      "terms": {
        "field": "beat.hostname",
        "size": 14,
        "order": {
          "_count": "desc"
        }
      },
      "aggs": {
        "metricAgg": {
          "avg": {
            "field": "system.memory.actual.used.pct"
          }
        },
        "dateAgg": {
          "date_histogram": {
            "field": "@timestamp",
            "time_zone": "Europe/Amsterdam",
            "interval": "1m",
            "min_doc_count": 1
          },
          "aggs": {
            "metricAgg": {
              "avg": {
                "field": "system.memory.actual.used.pct"
              }
            }
          }
        }
      }
    }
  }
}`
DEV TOOLS RESPONSE:
`{
  "took" : 17,
  "timed_out" : false,
  "_shards" : {
    "total" : 65,
    "successful" : 65,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 77830,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "bucketAgg" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "DETSERV01",
          "doc_count" : 5357,
          "dateAgg" : {
            "buckets" : [
              {
                "key_as_string" : "2019-03-01T00:40:00.000+01:00",
                "key" : 1551397200000,
                "doc_count" : 338,
                "metricAgg" : {
                  "value" : 0.044000000000000004
                }
              },
              {
                "key_as_string" : "2019-03-01T00:41:00.000+01:00",
                "key" : 1551397260000,
                "doc_count" : 337,
                "metricAgg" : {
                  "value" : 0.044000000000000004
                }
              },
              {
                "key_as_string" : "2019-03-01T00:42:00.000+01:00",
                "key" : 1551397320000,
                "doc_count" : 338,
                "metricAgg" : {
                  "value" : 0.044000000000000004
                }
              },
              {
                "key_as_string" : "2019-03-01T00:43:00.000+01:00",
                "key" : 1551397380000,
                "doc_count" : 336,
                "metricAgg" : {
                  "value" : 0.044000000000000004
                }
              },
              {
                "key_as_string" : "2019-03-01T00:44:00.000+01:00",
                "key" : 1551397440000,
                "doc_count" : 337,
                "metricAgg" : {
                  "value" : 0.044000000000000004
                }
              },
              {
                "key_as_string" : "2019-03-01T00:45:00.000+01:00",
                "key" : 1551397500000,
                "doc_count" : 336,
                "metricAgg" : {
                  "value" : 0.044000000000000004
                }
              },
              {
                "key_as_string" : "2019-03-01T00:46:00.000+01:00",
                "key" : 1551397560000,
                "doc_count" : 336,
                "metricAgg" : {
                  "value" : 0.043000000000000003
                }
              },
              {
                "key_as_string" : "2019-03-01T00:47:00.000+01:00",
                "key" : 1551397620000,
                "doc_count" : 335,
                "metricAgg" : {
                  "value" : 0.043000000000000003
                }
              },
              {
                "key_as_string" : "2019-03-01T00:48:00.000+01:00",
                "key" : 1551397680000,
                "doc_count" : 338,
                "metricAgg" : {
                  "value" : 0.043000000000000003
                }
              },
              {
                "key_as_string" : "2019-03-01T00:49:00.000+01:00",
                "key" : 1551397740000,
                "doc_count" : 338,
                "metricAgg" : {
                  "value" : 0.043000000000000003
                }
              },
              {
                "key_as_string" : "2019-03-01T00:50:00.000+01:00",
                "key" : 1551397800000,
                "doc_count" : 338,
                "metricAgg" : {
                  "value" : 0.043000000000000003
                }
              },
              {
                "key_as_string" : "2019-03-01T00:51:00.000+01:00",
                "key" : 1551397860000,
                "doc_count" : 338,
                "metricAgg" : {
                  "value" : 0.043000000000000003
                }
              },
              {
                "key_as_string" : "2019-03-01T00:52:00.000+01:00",
                "key" : 1551397920000,
                "doc_count" : 338,
                "metricAgg" : {
                  "value" : 0.043000000000000003
                }
              },
              {
                "key_as_string" : "2019-03-01T00:53:00.000+01:00",
                "key" : 1551397980000,
                "doc_count" : 338,
                "metricAgg" : {
                  "value" : 0.043000000000000003
                }
              },
              {
                "key_as_string" : "2019-03-01T00:54:00.000+01:00",
                "key" : 1551398040000,
                "doc_count" : 338,
                "metricAgg" : {
                  "value" : 0.043000000000000003
                }
              },
              {
                "key_as_string" : "2019-03-01T00:55:00.000+01:00",
                "key" : 1551398100000,
                "doc_count" : 298,
                "metricAgg" : {
                  "value" : 0.044
                }
              }
            ]
          },
          "metricAgg" : {
            "value" : 0.043425531914893616
          }
        },
        {
          "key" : "DETSERV02",
          "doc_count" : 5351,
          "dateAgg" : {
            "buckets" : [
              {
                "key_as_string" : "2019-03-01T00:40:00.000+01:00",
                "key" : 1551397200000,
                "doc_count" : 337,
                "metricAgg" : {
                  "value" : 0.044000000000000004
                }
              },
              {
                "key_as_string" : "2019-03-01T00:41:00.000+01:00",
                "key" : 1551397260000,
                "doc_count" : 339,
                "metricAgg" : {
                  "value" : 0.044000000000000004
                }
              },
              {
                "key_as_string" : "2019-03-01T00:42:00.000+01:00",
                "key" : 1551397320000,
                "doc_count" : 338,
                "metricAgg" : {
                  "value" : 0.044000000000000004
                }
              },
              {
                "key_as_string" : "2019-03-01T00:43:00.000+01:00",
                "key" : 1551397380000,
                "doc_count" : 336,
                "metricAgg" : {
                  "value" : 0.045000000000000005
                }
              },
              {
                "key_as_string" : "2019-03-01T00:44:00.000+01:00",
                "key" : 1551397440000,
                "doc_count" : 337,
                "metricAgg" : {
                  "value" : 0.045000000000000005
                }
              },
              {
                "key_as_string" : "2019-03-01T00:45:00.000+01:00",
                "key" : 1551397500000,
                "doc_count" : 336,
                "metricAgg" : {
                  "value" : 0.045000000000000005
                }
              },
              {
                "key_as_string" : "2019-03-01T00:46:00.000+01:00",
                "key" : 1551397560000,
                "doc_count" : 336,
                "metricAgg" : {
                  "value" : 0.045000000000000005`

**Comment by pr0j3ctz3r0** [comment]
Prettied version of watcher 
`{
  "actions": {
    "Elasticsearch_alarm_96e3e8b4-4a97-4059-b3d7-0b14ba723983": {
      "name": "Elasticsearch alarmsssss",
      "throttle_period": "1s",
      "elastic": {
        "priority": "low",
        "stateless": false,
        "message": "\n<p>There are {{payload.hits.total}} results found by the watcher <i>{{watcher.title}}</i>.</p>\n{{payload.aggregations.bucketAgg.doc_count_error_upper_bound}} \n"
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "metricbeat-*"
        ],
        "body": {
          "query": {
            "bool": {
              "filter": {
                "range": {
                  "@timestamp": {
                    "gte": "now-15m/m",
                    "lte": "now/m",
                    "format": "epoch_millis"
                  }
                }
              }
            }
          },
          "size": 0,
          "aggs": {
            "bucketAgg": {
              "terms": {
                "field": "beat.hostname",
                "size": 14,
                "order": {
                  "_count": "desc"
                }
              },
              "aggs": {
                "metricAgg": {
                  "avg": {
                    "field": "system.memory.actual.used.pct"
                  }
                },
                "dateAgg": {
                  "date_histogram": {
                    "field": "@timestamp",
                    "time_zone": "Europe/Amsterdam",
                    "interval": "1m",
                    "min_doc_count": 1
                  },
                  "aggs": {
                    "metricAgg": {
                      "avg": {
                        "field": "system.memory.actual.used.pct"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.aggregations.bucketAgg.buckets.some(b => b.dateAgg.buckets.some(b => b.metricAgg.value>=0.0446))"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 2 minutes"
    }
  },
  "disable": true,
  "report": false,
  "title": "High Memory Utilization",
  "wizard": {
    "chart_query_params": {
      "queryType": "average",
      "scheduleType": "every",
      "over": {
        "field": "beat.hostname",
        "n": 14,
        "type": "top"
      },
      "last": {
        "n": 15,
        "unit": "minutes"
      },
      "interval": {
        "n": 1,
        "unit": "minutes"
      },
      "timezoneName": "America/Detroit",
      "threshold": {
        "n": 0.0446,
        "direction": "above eq"
      },
      "timeField": "@timestamp",
      "field": "system.memory.actual.used.pct"
    }
  },
  "save_payload": false,
  "spy": false,
  "impersonate": false
}`

**Comment by pr0j3ctz3r0** [comment]
was able to parse server name with {{#payload.aggregations.bucketAgg.buckets}}Servers:<br>{{key}}{{/payload.aggregations.bucketAgg.buckets}} But it is showing all of the the servers.

**Comment by lmangani** [comment]
You can do multiple iterations within the mustache match

**Comment by pr0j3ctz3r0** [comment]
Please can you give an example? @lmangani
