### ISSUE TITLE
Sentinl and ELK OSS

### ISSUE THREAD

**Issue by arekstuka** [lmangani/sentinl#699]
Hi
Enybody try to install  Sentinl plugin on OSS ELK version ? It is possible ?

**Comment by ankurjha21** [comment]
@arekstuka Yeah go ahead I did that on last week and it's working perfectly fine. I deployed this o on kubernetes see the below link you will get more idea 
https://blog.webischia.com/2017/08/25/installing-kibana-with-sentinl-on-kubernetes/

I know, they didn't use the OSS image but i replace it with OSS image and it works fine


Thanks
