### ISSUE TITLE
"set watcher button kibana 6.5"

### ISSUE THREAD

**Issue by bjacomy** [lmangani/sentinl#701]
Hi,

I'm working with:
- sentinl 6.5 
- with kibana 6.5 
- under ubuntu OS using chrome web browser

My sentinl configuration is the following
  sentinl.es.host=localhost \
  sentinl.es.port=9200 \
  sentinl.settings.email.active=true \
  sentinl.settings.email.host="xxxxxxxxxxxxx"  \
  sentinl.settings.email.port="25"  \
  sentinl.settings.email.domain="xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"  \
  sentinl.settings.email.ssl=false  \
  sentinl.settings.report.active=true  

Is it yet possible to use "set watcher" button from kibana discover, visualize or dashboards like 

------------------------------------------------------------------------------------------------------
**for 4.6 version**

![image](https://user-images.githubusercontent.com/22446862/54343894-1115bf80-4640-11e9-893f-d0d20d348ff8.png)

--------------------------------------------------------------------------------------------------------
**As in 6.5 we have not this features:**

![image](https://user-images.githubusercontent.com/22446862/54344006-5c2fd280-4640-11e9-9551-75eea5084ef3.png)

Then, Can the "set watcher" butoon embbed kibana filters defined by operator action?

thanks

**Comment by AntonTsaberyaby** [comment]
I have the same issue. Is there any other easy way to create a watcher?
