### ISSUE TITLE
Cannot send report email

### ISSUE THREAD

**Issue by scottw425** [lmangani/sentinl#702]
### System Details
Windows 10
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |     6.61    |
| Elasticsearc |     6.61    |
| Server OS    |         |
| Browser      |     firefox    |

#### Original Install Method

- [ ] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: windows command line

#### Bug Description

I am trying to start a watcher to take a screenshot of one of my visualisations and send it in an email. But the email won't send and i get and errror in the reports tab of Sentinl

#### Steps to Reproduce
1. 
1.
1.

#### Expected Behavior

Receive an Email with a screenshot 

#### Sample of data you have in Elasticsearch
```
```

#### Full Watcher JSON
{
  "actions": {
    "Report_screenshot_b4ebda13-4c9c-4c3b-941f-49d3d6e318be": {
      "name": "Report screenshot",
      "throttle_period": "15m",
      "report": {
        "auth": {
          "mode": "basic",
          "active": false
        },
        "priority": "low",
        "stateless": false,
        "body": "You can find the screenshot in the attachment.",
        "save": true,
        "snapshot": {
          "res": "1920x1080",
          "url": "http://localhost:5601/app/kibana#/visualize/edit/55280fb0-4669-11e9-96b3-a3ea505eb58f?embed=true&_g=(refreshInterval:(pause:!f,value:10000),time:(from:now-15m,mode:quick,to:now))&_a=(filters:!(),linked:!f,query:(language:lucene,query:''),uiState:(),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(field:constellation.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!f,otherBucketLabel:Other,size:5),schema:segment,type:terms)),params:(addLegend:!t,addTooltip:!t,isDonut:!t,labels:(last_level:!t,show:!f,truncate:100,values:!t),legendPosition:right,type:pie),title:'Constellation+Pie',type:pie))",
          "params": {
            "delay": 5000,
            "crop": "false"
          },
          "type": "png"
        },
        "to": "******@****.com",
        "subject": "test"
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "testindex"
        ],
        "body": {}
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total >= 0"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 1 minutes"
    }
  },
  "disable": false,
  "report": false,
  "title": "watcher2",
  "wizard": {
    "chart_query_params": {
      "queryType": "count",
      "scheduleType": "every",
      "over": {
        "type": "all docs",
        "n": 1,
        "field": "id.keyword"
      },
      "last": {
        "n": 1,
        "unit": "hours"
      },
      "interval": {
        "n": 1,
        "unit": "minutes"
      },
      "timezoneName": "Europe/Amsterdam",
      "threshold": {
        "n": 1,
        "direction": "above eq"
      }
    }
  },
  "save_payload": false,
  "spy": false,
  "impersonate": false
}

#### Errors in Browser Console (if relevant)
```
```

#### Kibana logs and/or server output (attached if relevant)

  log   [10:55:11.562] [error][Sentinl] watcher2: report action : execute : puppeteer work : Chromium revision is not downloaded. Run "npm install" or "yarn install": Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"

**Comment by scottw425** [comment]
I have added some configurations into the Kibana.Yml which is not displaying the screenshots but still will not send the email.

sentinl:

    settings:
        email:
            active: true
            host: smtp.gmail.com
            user: '*****'
            password: '*****'
            port: ****

        report:
            active: true
            engine: puppeteer
            puppeteer:
                browser_path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

Also i was wondering if there is a way to download the screenshots automatically from the reports tab in Kibana rather than individually clicking 'download report' on each one.

**Comment by runsmeagolrun** [comment]
I checked your watcher but it is not giving me any error. Below is my sentinl settings:

[sentinl:
  settings:
    email:
      active: true
      host: 10.44.226.143
      port: 25
      ssl: false
    report:
      active: true
      engine: horseman # options: horseman, puppeteer](url)

**Comment by runsmeagolrun** [comment]
Let me know if you resolved this issue.

**Comment by scottw425** [comment]
Thanks. Ill try your settings and let you know how it goes

**Comment by shery99** [comment]
Hi,
There is no need of putting username and password in email config.
Just use the below config.
email:
      active: true
      host: 10.44.226.143
      port: 25
      ssl: false

Error may be because of User and password so do not include in config.
Thanks.
