### ISSUE TITLE
Missing sentinl version for Kibana 6.6.2

### ISSUE THREAD

**Issue by clemensloebig** [lmangani/sentinl#706]
Hi,

please add sentinl for Kibana 6.6.2

**Comment by grfneto** [comment]
is there any forecast? I would also like the most up-to-date version of the plugin.

**Comment by clemensloebig** [comment]
please than also for kibana 6.7.0

**Comment by k29killgod** [comment]
1、you can modfiy  package.json of sentinl-v6.6.1.zip 
 "kibana": {
    "version": "6.6.2"
  }
2、bin/kibana-plugin install file:///sentinl-v6.6.1.zip

**Comment by shaunxq** [comment]
> 1、you can modfiy package.json of sentinl-v6.6.1.zip
> "kibana": {
> "version": "6.6.2"
> }
> 2、bin/kibana-plugin install file:///sentinl-v6.6.1.zip

it doesn't work, the plugin installation complete, but it is not appears on the web ui

**Comment by k29killgod** [comment]
do you restart kibana?










At 2019-04-10 16:45:12, "shaunxq" <notifications@github.com> wrote:


1、you can modfiy package.json of sentinl-v6.6.1.zip
"kibana": {
"version": "6.6.2"
}
2、bin/kibana-plugin install file:///sentinl-v6.6.1.zip

it doesn't work, the plugin installation complete, but it is not appears on the web ui

**Comment by jockjiang** [comment]
I can install it successfully by change the version in package.json to 6.6.2, but the UI in Kibana seems wrong
