### ISSUE TITLE
Missing sentinl version for Kibana 5.6.16

### ISSUE THREAD

**Issue by msgtomm** [lmangani/sentinl#719]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |         |
| Elasticsearc |         |
| Server OS    |         |
| Browser      |         |

#### Original Install Method

- [ ] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

#### Steps to Reproduce
1.
1.
1.

#### Sample of data you have in Elasticsearch
```
```

#### Full Watcher JSON
```
```

#### Errors in Browser Console (if relevant)
```
```

**Comment by msgtomm** [comment]
can you please share the sentinl pacakge for kibana 5.6.16

**Comment by sreekanth-ragi** [comment]
+1
