### ISSUE TITLE
sentinl + search guard + kibana page cannot display

### ISSUE THREAD

**Issue by andrewzjut** [lmangani/sentinl#727]
Hi

# my software version is
elasticsearch 6.6.1
kibana 6.6.1
sentinl 6.6.0
search guard 6.6.1

# my  elasticsearch.yml is :

searchguard.enterprise_modules_enabled: true
searchguard.ssl.transport.keystore_filepath: key/node-certificates/CN=IP-172.30.12.247-keystore.jks
searchguard.ssl.transport.keystore_password: d571f5c84856bd1d1cc9
searchguard.ssl.transport.truststore_filepath: key/truststore.jks
searchguard.ssl.transport.truststore_password: 4fc31938243ff46703f0
searchguard.ssl.transport.enforce_hostname_verification: false

searchguard.authcz.admin_dn:
  - CN=sgadmin  
searchguard.audit.type: internal_elasticsearch
searchguard.enable_snapshot_restore_privilege: true
searchguard.check_snapshot_restore_write_privileges: true
searchguard.restapi.roles_enabled: ["sg_all_access"]
cluster.routing.allocation.disk.threshold_enabled: false
node.max_local_storage_nodes: 1
xpack.security.enabled: false

# my kibana.yml is:
server.port: 5601
server.host: "0.0.0.0"
elasticsearch.hosts: ["http://localhost:9200"]
kibana.index: ".kibana"
elasticsearch.ssl.verificationMode: none
elasticsearch.requestHeadersWhitelist: [ "Authorization", "sgtenant" ]
xpack.security.enabled: false

sentinl:
  es:
    protocol: 'http'
    results: 50
    timefield: '@timestamp'
    default_type: 'doc'
    alarm_index: 'watcher_alarms'
    alarm_type: 'sentinl-alarm'
  settings:
    authentication:
      enabled: true 
      impersonate: true
      username: 'admin'
      password: '123456'
    email:
      active: true
      user: ****@163.com
      password: ******
      host: smtp.163.com
      ssl: false

elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"

elasticsearch.ssl.certificateAuthorities: [ "/Users/zhangtong/software/elasticsearch-1/config/key/root-ca.pem" ]
elasticsearch.ssl.verificationMode: none
xpack.security.enabled: false

# my sg_roles.yml is:

sg_kibana_server:
  readonly: true
  cluster:
      - CLUSTER_MONITOR
      - CLUSTER_COMPOSITE_OPS
      - cluster:admin/xpack/monitoring*
      - indices:admin/template*
      - indices:data/read/scroll*
  indices:
    '?kibana':
      '*':
        - INDICES_ALL
    '?kibana-6':
      '*':
        - INDICES_ALL
    '?kibana_*':
      '*':
        - INDICES_ALL
    '?reporting*':
      '*':
        - INDICES_ALL
    '?monitoring*':
      '*':
        - INDICES_ALL
    '?tasks':
      '*':
        - INDICES_ALL
    '?management-beats*':
      '*':
        - INDICES_ALL
    'watcher*':
      '*':
       - indices:data/read/search
       - MANAGE
       - CREATE_INDEX
       - INDEX
       - READ
       - WRITE
       - DELETE
    '*':
      '*':
        - "indices:admin/aliases*"
        - "indices:data/read/search"

# Description of the issue
sentinl install with search guard , the sentinl page cannot display correct , the page is as below:

<img width="1538" alt="屏幕快照 2019-05-06 上午9 10 49" src="https://user-images.githubusercontent.com/6974106/57203103-959d1280-6fdf-11e9-9cf2-0ff0f3a6bf45.png">

when i only install sentinl ,the page is correct

what's wrong with it , can some one help me? thank you

**Comment by andrewzjut** [comment]
does this error matters ?

  log   [01:30:13.208] [debug][legacy-proxy] "getConnections" has been called.
  log   [01:30:13.209] [debug][legacy-proxy] "getConnections" has been called.
  log   [01:30:13.210] [debug][kibana-monitoring][monitoring-ui] Received Kibana Ops event data
  log   [01:30:13.210] [debug][kibana-monitoring][monitoring-ui] Received Kibana Ops event data
  log   [01:30:13.461] [debug][legacy-proxy] "getConnections" has been called.
  log   [01:30:13.566] [debug][legacy-proxy] "getConnections" has been called.
  log   [01:30:13.566] [debug][legacy-proxy] "getConnections" has been called.
  log   [01:30:13.568] [debug][kibana-monitoring][monitoring-ui] Received Kibana Ops event data
  log   [01:30:13.568] [debug][kibana-monitoring][monitoring-ui] Received Kibana Ops event data
  log   [01:30:13.752] [debug][plugin] Checking Elasticsearch version
  log   [01:30:13.771] [debug][stats-collection] Fetching data from kql collector
  log   [01:30:13.772] [debug][stats-collection] Fetching data from kibana_stats collector
  log   [01:30:13.773] [debug][stats-collection] Fetching data from kibana collector
  log   [01:30:13.773] [debug][stats-collection] Fetching data from kibana_settings collector
  log   [01:30:13.774] [debug][stats-collection] Fetching data from rollups collector
  log   [01:30:13.779] [debug][stats-collection] not sending [kibana_settings] monitoring document because [undefined] is null or invalid.
  log   [01:30:13.788] [debug][kibana-monitoring][monitoring-ui] Uploading bulk stats payload to the local cluster
  log   [01:30:14.680] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:14.681] [debug][legacy-service] Request will be handled by proxy GET:/app/sentinl.
  log   [01:30:14.682] [debug][legacy-proxy] Event is being forwarded: connection
respons [01:30:14.681]  GET /app/sentinl 200 63ms - 9.0B
  log   [01:30:14.880] [debug][legacy-service] Request will be handled by proxy GET:/bundles/app/sentinl/bootstrap.js.
respons [01:30:14.881]  GET /bundles/app/sentinl/bootstrap.js **304** 5ms - 9.0B
  log   [01:30:15.019] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.019] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.020] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.020] [debug][legacy-service] Request will be handled by proxy GET:/dlls/vendors.style.dll.css.
  log   [01:30:15.022] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.022] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.022] [debug][legacy-service] Request will be handled by proxy GET:/bundles/commons.style.css.
  log   [01:30:15.023] [debug][legacy-service] Request will be handled by proxy GET:/bundles/sentinl.style.css.
  log   [01:30:15.025] [debug][legacy-service] Request will be handled by proxy GET:/plugins/vega/index.css.
  log   [01:30:15.026] [debug][legacy-service] Request will be handled by proxy GET:/plugins/tile_map/index.css.
  log   [01:30:15.028] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.029] [debug][legacy-service] Request will be handled by proxy GET:/plugins/tagcloud/index.css.
respons [01:30:15.021]  GET /dlls/vendors.style.dll.css **304** 15ms - 9.0B
respons [01:30:15.023]  GET /bundles/commons.style.css ****304**** 14ms - 9.0B
respons [01:30:15.024]  GET /bundles/sentinl.style.css ****304**** 14ms - 9.0B
respons [01:30:15.025]  GET /plugins/vega/index.css ****304**** 14ms - 9.0B
respons [01:30:15.026]  GET /plugins/tile_map/index.css ****304**** 14ms - 9.0B
  log   [01:30:15.042] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.043] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.044] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.044] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.045] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.046] [debug][legacy-service] Request will be handled by proxy GET:/plugins/table_vis/index.css.
respons [01:30:15.030]  GET /plugins/tagcloud/index.css **304** 17ms - 9.0B
  log   [01:30:15.048] [debug][legacy-service] Request will be handled by proxy GET:/plugins/status_page/index.css.
  log   [01:30:15.049] [debug][legacy-service] Request will be handled by proxy GET:/plugins/region_map/index.css.
  log   [01:30:15.050] [debug][legacy-service] Request will be handled by proxy GET:/plugins/metrics/index.css.
  log   [01:30:15.051] [debug][legacy-service] Request will be handled by proxy GET:/plugins/metric_vis/index.css.
  log   [01:30:15.052] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.053] [debug][legacy-service] Request will be handled by proxy GET:/plugins/markdown_vis/index.css.
respons [01:30:15.046]  GET /plugins/table_vis/index.css **304** 10ms - 9.0B
respons [01:30:15.048]  GET /plugins/status_page/index.css **304** 9ms - 9.0B
respons [01:30:15.049]  GET /plugins/region_map/index.css **304** 9ms - 9.0B
respons [01:30:15.050]  GET /plugins/metrics/index.css **304** 8ms - 9.0B
respons [01:30:15.051]  GET /plugins/metric_vis/index.css **304** 8ms - 9.0B
  log   [01:30:15.060] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.060] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.061] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.061] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.062] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.062] [debug][legacy-service] Request will be handled by proxy GET:/plugins/kibana/index.css.
  log   [01:30:15.063] [debug][legacy-service] Request will be handled by proxy GET:/plugins/inspector_views/index.css.
  log   [01:30:15.064] [debug][legacy-service] Request will be handled by proxy GET:/plugins/input_control_vis/index.css.
  log   [01:30:15.065] [debug][legacy-service] Request will be handled by proxy GET:/plugins/console/index.css.
respons [01:30:15.053]  GET /plugins/markdown_vis/index.css **304** 13ms - 9.0B
  log   [01:30:15.068] [debug][legacy-service] Request will be handled by proxy GET:/plugins/upgrade_assistant/index.css.
  log   [01:30:15.070] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.071] [debug][legacy-service] Request will be handled by proxy GET:/plugins/cross_cluster_replication/index.css.
respons [01:30:15.063]  GET /plugins/kibana/index.css **304** 11ms - 9.0B
respons [01:30:15.063]  GET /plugins/inspector_views/index.css **304** 12ms - 9.0B
respons [01:30:15.064]  GET /plugins/input_control_vis/index.css **304** 12ms - 9.0B
respons [01:30:15.065]  GET /plugins/console/index.css **304** 12ms - 9.0B
  log   [01:30:15.078] [debug][legacy-proxy] Event is being forwarded: connection
respons [01:30:15.069]  GET /plugins/upgrade_assistant/index.css **304** 9ms - 9.0B
  log   [01:30:15.079] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.079] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.080] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.081] [debug][legacy-service] Request will be handled by proxy GET:/plugins/remote_clusters/index.css.
  log   [01:30:15.082] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.082] [debug][legacy-service] Request will be handled by proxy GET:/plugins/rollup/index.css.
  log   [01:30:15.083] [debug][legacy-service] Request will be handled by proxy GET:/plugins/index_lifecycle_management/index.css.
  log   [01:30:15.084] [debug][legacy-service] Request will be handled by proxy GET:/plugins/index_management/index.css.
respons [01:30:15.071]  GET /plugins/cross_cluster_replication/index.css **304** 14ms - 9.0B
  log   [01:30:15.086] [debug][legacy-service] Request will be handled by proxy GET:/plugins/license_management/index.css.
  log   [01:30:15.087] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.088] [debug][legacy-service] Request will be handled by proxy GET:/plugins/watcher/index.css.
respons [01:30:15.081]  GET /plugins/remote_clusters/index.css **304** 11ms - 9.0B
respons [01:30:15.083]  GET /plugins/rollup/index.css **304** 10ms - 9.0B
respons [01:30:15.083]  GET /plugins/index_lifecycle_management/index.css **304** 11ms - 9.0B
respons [01:30:15.084]  GET /plugins/index_management/index.css **304** 10ms - 9.0B
  log   [01:30:15.095] [debug][legacy-proxy] Event is being forwarded: connection
respons [01:30:15.086]  GET /plugins/license_management/index.css **304** 10ms - 9.0B
  log   [01:30:15.097] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.097] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.098] [debug][legacy-service] Request will be handled by proxy GET:/plugins/searchprofiler/index.css.
  log   [01:30:15.100] [debug][legacy-service] Request will be handled by proxy GET:/plugins/monitoring/index.css.
  log   [01:30:15.101] [debug][legacy-service] Request will be handled by proxy GET:/ui/favicons/favicon.ico.
  log   [01:30:15.102] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.102] [debug][legacy-proxy] Event is being forwarded: connection
respons [01:30:15.088]  GET /plugins/watcher/index.css **304** 15ms - 9.0B
  log   [01:30:15.104] [debug][legacy-service] Request will be handled by proxy GET:/ui/favicons/manifest.json.
  log   [01:30:15.105] [debug][legacy-service] Request will be handled by proxy GET:/dlls/vendors.bundle.dll.js.
respons [01:30:15.104]  GET /ui/favicons/manifest.json **304** 4ms - 9.0B
respons [01:30:15.098]  GET /plugins/searchprofiler/index.css **304** 13ms - 9.0B
respons [01:30:15.100]  GET /plugins/monitoring/index.css **304** 12ms - 9.0B
respons [01:30:15.101]  GET /ui/favicons/favicon.ico **304** 12ms - 9.0B
respons [01:30:15.105]  GET /dlls/vendors.bundle.dll.js **304** 10ms - 9.0B
  log   [01:30:15.705] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.706] [debug][legacy-service] Request will be handled by proxy GET:/bundles/commons.bundle.js.
respons [01:30:15.706]  GET /bundles/commons.bundle.js **304** 3ms - 9.0B
  log   [01:30:15.953] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:15.954] [debug][legacy-service] Request will be handled by proxy GET:/bundles/sentinl.bundle.js.
respons [01:30:15.954]  GET /bundles/sentinl.bundle.js **304** 3ms - 9.0B
  log   [01:30:16.264] [debug][plugin] Checking Elasticsearch version
  log   [01:30:16.798] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:16.799] [debug][legacy-service] Request will be handled by proxy GET:/plugins/sentinl/style/sentinl.svg.
respons [01:30:16.799]  GET /plugins/sentinl/style/sentinl.svg **304** 2ms - 9.0B
  log   [01:30:16.829] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:16.830] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:16.830] [debug][legacy-service] Request will be handled by proxy GET:/api/v1/auth/authinfo.
  log   [01:30:16.832] [debug][legacy-service] Request will be handled by proxy GET:/api/sentinl/time.
respons [01:30:16.834]  GET /api/sentinl/time 200 7ms - 9.0B
respons [01:30:16.831]  GET /api/v1/auth/authinfo 200 11ms - 9.0B
  log   [01:30:16.860] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:16.860] [debug][legacy-service] Request will be handled by proxy GET:/bundles/af7ae505a9eed503f8b8e6982036873e.woff2.
respons [01:30:16.861]  GET /bundles/af7ae505a9eed503f8b8e6982036873e.woff2 **304** 2ms - 9.0B
  log   [01:30:16.886] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:16.887] [debug][legacy-service] Request will be handled by proxy GET:/ui/favicons/favicon.ico.
  log   [01:30:16.891] [debug][legacy-proxy] Event is being forwarded: connection
  log   [01:30:16.893] [debug][legacy-service] Request will be handled by proxy GET:/plugins/searchguard/assets/searchguard_logo_nav.svg.
respons [01:30:16.887]  GET /ui/favicons/favicon.ico **304** 8ms - 9.0B
respons [01:30:16.893]  GET /plugins/searchguard/assets/searchguard_logo_nav.svg **304** 3ms - 9.0B
  log   [01:30:18.211] [debug][legacy-proxy] "getConnections" has been called.
  log   [01:30:18.212] [debug][legacy-proxy] "getConnections" has been called.
  log   [01:30:18.212] [debug][kibana-monitoring][monitoring-ui] Received Kibana Ops event data
  log   [01:30:18.213] [debug][kibana-monitoring][monitoring-ui] Received Kibana Ops event data
  log   [01:30:18.465] [debug][legacy-proxy] "getConnections" has been called.
  log   [01:30:18.566] [debug][legacy-proxy] "getConnections" has been called.
  log   [01:30:18.567] [debug][legacy-proxy] "getConnections" has been called.
  log   [01:30:18.568] [debug][kibana-monitoring][monitoring-ui] Received Kibana Ops event data
  log   [01:30:18.570] [debug][kibana-monitoring][monitoring-ui] Received Kibana Ops event data
  log   [01:30:18.776] [debug][plugin] Checking Elasticsearch version

**Comment by marwojt** [comment]
Hi,
I have same issue with:
elasticsearch 6.6.1
kibana 6.6.1
sentinl 6.6.1
search guard 6.6.1 (elastic plugin 24.3 and kibana plugin 18.3)

Before i had serchguard plugins version 1 (elastic plugin 24.1 and kibana plugin 18.1) and sentinl navgiation was working fine.

**Comment by andrewzjut** [comment]
> Hi,
> I have same issue with:
> elasticsearch 6.6.1
> kibana 6.6.1
> sentinl 6.6.1
> search guard 6.6.1 (elastic plugin 24.3 and kibana plugin 18.3)
> 
> Before i had serchguard plugins version 1 (elastic plugin 24.1 and kibana plugin 18.1) and sentinl navgiation was working fine.

Have you solved the problem now?  with the version（elastic plugin 24.3 and kibana plugin 18.3）
I have been troubled by this problem for a long time.

**Comment by andrewzjut** [comment]
> Hi,
> I have same issue with:
> elasticsearch 6.6.1
> kibana 6.6.1
> sentinl 6.6.1
> search guard 6.6.1 (elastic plugin 24.3 and kibana plugin 18.3)
> 
> Before i had serchguard plugins version 1 (elastic plugin 24.1 and kibana plugin 18.1) and sentinl navgiation was working fine.

do you have this zip file (search-guard-6-6.6.1-24.1.zip  search-guard-kibana-plugin-6-6.6.1-18.1.zip)
can you sent them to my email (ztzjut@163.com) 
thanks a lot

**Comment by andrewzjut** [comment]
> elastic plugin 24.1 and kibana plugin 18.1

thank you so much , i had to use the older version!

**Comment by marwojt** [comment]
I have updated searchguard plugins to v.3 because i had some problems with Kibana multi tenancy. After update, searchguard is working fine but sentinl had issue.
I didn't solve this problem yet.

**Comment by andrewzjut** [comment]
hi ，I build sentinl zip file from source code，it works，but still very grateful for your advice to me.

> 在 2019年5月7日，下午4:08，marwojt <notifications@github.com <mailto:notifications@github.com>> 写道：
> 
> searchguard

**Comment by marwojt** [comment]
From witch branch did You take code ?

**Comment by marwojt** [comment]
I have build it from branch-6.6.0 and still have issue

**Comment by andrewzjut** [comment]
branch-6.6.0

**Comment by rsingh2411** [comment]
How did we solve the issue,  for 6.6.1 stack.

**Comment by marwojt** [comment]
andrewzjut solution didn't work for me. I still have issue with sentinl 6.6.1 and search guard kibana plugin 18.3. Temporarily i use searchguard plugin in version 18.1

**Comment by Bader972016** [comment]
I too am having the same issue with latest release versions of searchguard (.4 I believe)
Install ELK stack v6.6.0 (from yum repository on CentOS 7) with the corresponding searchguard version for both Elasticsearch and Kibana
Download the sentinl plugin through the releases link: https://github.com/sirensolutions/sentinl/releases/download/tag-6.6.0-0/sentinl-v6.6.0.zip

keep sentinl at default configuration (just want to have it running so I can create watchers and alarms through GUI).

Result: Getting the same "utc Time" and "current Time" instead of the actual values, with none of the buttons to Watcher Report etc available.

Elasticsearch.yml.txt
Kibana.log.txt
kibana.yml.txt
Elasticsearch.log

Please let me know what to do (provide more info etc)
I just didn't want to open a new issue randomly when theres the same case of it right here

**Comment by Bader972016** [comment]
> kibana plugin 18.1 

This solved my issue.. sorry for any inconvenience
