### ISSUE TITLE
If Sentinl Plugin for ELK 7.x

### ISSUE THREAD

**Issue by yangcaixing** [lmangani/sentinl#732]
Hi siren, 
    Now I'm using the ELK 7.0.1, but the sentinl is incompatible with 7.0.x(Plugin installation was unsuccessful due to error "Plugin sentinl [6.6.1] is incompatible with Kibana [7.0.1]"), so if you  consider to update the version to compatible ELK 7.x, thanks in advance.

**Comment by webhead404** [comment]
Does the project maintainers plan on supporting Elastic Stack 7.x-7.2?

**Comment by kedych** [comment]
I have the same question as @yangcaixing and @webhead404. Is there any news about support Elastic Stack 7.x? Thanks.

**Comment by lmangani** [comment]
At this time there are no plans and no sponsors for this macro effort. If anyone wants to step up and help the project get 7.x compatibility with PRs or Sponsorships, feel free to reach out.

**Comment by kedych** [comment]
@lmangani Got it! Thanks for quick reply and your hard work.

**Comment by JnMik** [comment]
Ah damn, support for 7.X would have been nice

**Comment by lmangani** [comment]
@JnMik we're not at all excluding it at all, but we need to make this a community project for that to be effective over time

**Comment by chadfurman** [comment]
@lmangani could you layout a "todo" list for 7.x compatibility?

**Comment by lmangani** [comment]
We're lacking paid contributors and/or funds to sponsor the intensive development and the major efforts required for SENTINL to be ported to 7.x. If anyone in the community wishes to volunteer resources or help out in any other way, feel free to send me a direct message.

**Comment by jccq** [comment]
To clarify, Sentinl (in the form of Siren Alert, therefore not as Kibana
plugin but exclusively working withing Siren Investigate) *will* be working
on ELK 7.x as early as Siren 10.3.2 or 10.4 (10.3 just released , check the
blog )

Lorenzo is referring to Sentinl that also works as  Kibana plugin, for
which those interested should be talking to him personally for a possible
new community project

**Comment by fbaligand** [comment]
Hi @jccq,

Does it mean that when siren alert for siren investigate will be out with Kibana 7.x support, this sentinl repository will also be updated?

**Comment by meriem-ux** [comment]
@jccq  @fbaligand  
hi me too i have same issue i installed kibana 7.3.2 and this sentinel plugin is not compatible pls any help???

**Comment by fbaligand** [comment]
Sentinl is currently not compatible with 7.x. 
A PR is in process. You can follow it.

**Comment by anantkumar123** [comment]
i want install sentinl plugin for kibana 7.9 but its not supported

**Comment by anantkumar123** [comment]
is there any way how can achieve this?
