### ISSUE TITLE
Watchers and custom space

### ISSUE THREAD

**Issue by YuriyMartynov** [lmangani/sentinl#735]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |    6.6.1     |
| Elasticsearc |   6.6.1       |
| Server OS    |    Red Hat Enterprise Linux Server release 7.6     |
| Browser      |         |

#### Original Install Method

- [x] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

### Bug Details
Sentinl version 6.6.1  doesn’t pick up all the watchers if you create them in a space other than default.
#### Bug Description
Watchers were created at custom space.
Watchers are scheduled to run every 5 minutes. Many of these should be triggering an alarm every 5 minutes, however we receive at most 1x trigger every 5 minutes of a random watcher and all other watchers are skipped. 

Watchers work correctly if they moved to DEFAULT space.

**Comment by hvsop** [comment]
does it means ,not all the watchers were triggered in a space other than default ?

+1 for me , 3 watchers in new space other than default but 1 alert were triggered.

@YuriyMartynov
