### ISSUE TITLE
Sentinl Alert Limit

### ISSUE THREAD

**Issue by cemkuleyin** [lmangani/sentinl#740]
Hi everyone,

I have a big problem with sentinl. I'm currently using Version: 6.4.3 of Kibana and Sentinl. I have 50 alerts. But now i dont create new alert. Im creating but not showing on alert list. If i delete one alert and show one new alert.

Can you help me this situation.

Thanks ,

Cem

**Comment by svetasaraeva** [comment]
Could that be the issue described here #729 ?

**Comment by svetasaraeva** [comment]
Having same issue.
Even worse, kibana logs show alert created as normal, it looks like it just doesn't show up on the list, so I expected it to work, but it actually doesn't. Watchers only send alerts if they are visible.

**Comment by TomasKoutek** [comment]
Hi,
just change the settings:

```
sentinl:
  es:
    ...
    results: 150 # (default is 50)
```

**Comment by canertosuner** [comment]
> Hi,
> just change the settings:
> 
> ```
> sentinl:
>   es:
>     ...
>     results: 150 # (default is 50)
> ```
> 
> https://github.com/sirensolutions/sentinl/blob/master/index.js#L85

You mean this right ?
 **results: Joi.number().default(150),**
and any reboot kibana or reinstall the pluging required after config change ?

**Comment by canertosuner** [comment]
> Hi,
> just change the settings:
> 
> ```
> sentinl:
>   es:
>     ...
>     results: 150 # (default is 50)
> ```
> 
> https://github.com/sirensolutions/sentinl/blob/master/index.js#L85

and don't forget to restart kibana
`systemctl restart kibana`
