### ISSUE TITLE
Will it work with ELK 7.2?

### ISSUE THREAD

**Issue by mancharagopan** [lmangani/sentinl#744]
Will it work with ELK 7.2?

**Comment by robertboloc** [comment]
@mancharagopan I tried to set it up on a 7.2 cluster and no it won't work:
```

**Comment by robertboloc** [comment]
@mancharagopan I tried it on a 7.2 cluster and it doesn't work: `Plugin installation was unsuccessful due to error "Plugin sentinl [6.2.2] is incompatible with Kibana [7.2.0]"`

**Comment by ydewinte** [comment]
have you tried with changing the release version?

**Comment by chadfurman** [comment]
https://github.com/sirensolutions/sentinl/issues/732

7.x is a sometime-maybe feature -- needs dev and/or financial support to get there
