### ISSUE TITLE
Fatal Error Kibana 7.2.0

### ISSUE THREAD

**Issue by hackdefendr** [lmangani/sentinl#746]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |  7.2.0  |
| Elasticsearc | 7.2.0  |
| Server OS    | Debian Buster |
| Browser      | Chrome (Latest) |

#### Original Install Method

- [ ] Release pkg link
- [ ] Gulp
- [x] Source
- Other: 

#### Bug Description

`FATAL  Error: [plugin:sentinl] uiExports.app.injectVars has been removed. Use server.injectUiAppVars('sentinl', () => { ... })`

#### Steps to Reproduce
1. npm install
1. gulp package --version=7.2.0
1. kibana-plugin install
1. start kibana

I hope that error means something to someone.

**Comment by hackdefendr** [comment]
So I took a stab at fixing this error.  I edited index.js in the root of sentinl.

Change Line 48

> from injectVars
> to injectUiAppVars

And commenting out the spyModes line (removed in Kibana 6.4?).

Waiting for Kibana to optimize now. Hopefully this fixed it.

**Comment by webhead404** [comment]
@hackdefendr did you have success with this?

**Comment by hackdefendr** [comment]
@webhead404 Unfortunately no. Kibana just won't start, it goes into an optimization phase that is supposed to be only a few minutes. After 28 hours, I gave up.

I guess on the bright side, there were no other errors related to Sentinl. Because after removing Sentinl, Kibana still would not start up without optimization.

**Comment by hackdefendr** [comment]
So I guess the question I have is, Will Sentinl ever support 7.2.0?  If so when?

**Comment by chadfurman** [comment]
https://github.com/sirensolutions/sentinl/issues/732

It's a sometime-maybe feature -- needs dev and/or financial support to get there
