### ISSUE TITLE
can i push the code which i made change in sentinl support for kibana 7.2

### ISSUE THREAD

**Issue by kundan8239** [lmangani/sentinl#750]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |         |
| Elasticsearc |         |
| Server OS    |         |
| Browser      |         |

#### Original Install Method

- [ ] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

#### Steps to Reproduce
1.
1.
1.

#### Sample of data you have in Elasticsearch
```
```

#### Full Watcher JSON
```
```

#### Errors in Browser Console (if relevant)
```
```

**Comment by fbaligand** [comment]
Feel free to open a pull request!

Core team will be really very happy to have such a contribution!

**Comment by lmangani** [comment]
Thanks @kundan8239 feel free to send a PR or contact me directly if you need help doing so - thanks for your contribution!
