### ISSUE TITLE
Deleted watcher from kibana , but still get alerts from previous actions 

### ISSUE THREAD

**Issue by amulyamalla** [lmangani/sentinl#751]
ES - v6.5.4 
Kibana - v6.5.4
Search guard - v6.5.4
sentinl plugin - v6.5.4  

Configure sentinl with some test watcher and action , but when i deleted the watcher from kibana GUI , but still alarm get fired at the regular interval , as i already given required permission at search guard , subsequent index get created at elastic search ,   manually deleted watcher index   but it will auto recreated again . 

No watcher : 
![image](https://user-images.githubusercontent.com/29882428/64233362-a324c380-cf11-11e9-9f3c-98f7cf400e90.png)

Listed alarm : 
![image](https://user-images.githubusercontent.com/29882428/64233475-e67f3200-cf11-11e9-8f34-8e0672daf76c.png)

**Comment by apmalla** [comment]
After debugging found something at kibana logs , thats related to orphan watcher , here the log i found 
![image](https://user-images.githubusercontent.com/29882428/64245894-6fee2e80-cf29-11e9-81e7-dd8bae3ad40b.png)

i just removed sentinl and optimize again , but still issue persist

**Comment by apmalla** [comment]
Hey @lmangani and @sergibondarenko  , could you please respond ?

**Comment by YanekR** [comment]
Hi! 

I got same issue. Did you have any chance to find out where this orphaned watcher is stored?

Thanks,
Jan

**Comment by apmalla** [comment]
@YanekR  
you need to delete mapping of  sentinl  from .kibana index , if you have less priority saved object then just delete it and recreate

still waiting for appropriate response from  @sirensolutions Team
