### ISSUE TITLE
Sentinl Plugin for ELK 7.x

### ISSUE THREAD

**Issue by meriem-ux** [lmangani/sentinl#754]
hi i have issue, i installed kibana 7.3.2 and i installed sentinel plugin [6.6.1] but is not compatible with my kibana version
plz any help???

**Comment by TomasKoutek** [comment]
#732

**Comment by meriem-ux** [comment]
@TomasKoutek thnx for u r reply, i don't found the version of sentinel for kibana 7.3.2

**Comment by fbaligand** [comment]
@TomasKoutek talks about issue #732, not Sentinl for Kibana 7.3.2

**Comment by meriem-ux** [comment]
@fbaligand thnx for u r reply, plz can u suggest me another plugin work with kibana 7.3.2??

**Comment by fbaligand** [comment]
To my known, the only alerting tool that works with Kibana 7.3.2 is elastalert.
There is a kibana plugin here: https://github.com/bitsensor/elastalert-kibana-plugin

But it requires a elastalert server that runs on Docker

**Comment by lmangani** [comment]
I would not compare the two or suggest it as a replacement. I'd wish to see efforts to contribute to Sentinl's survival rather than just mercyless asking for new versions in exchange for nothing, and then turning backs when a meal is not precooked - much of the reason I no longer actively contribute to my own creature until this changes.

**Comment by fbaligand** [comment]
@lmangani 
A encouraging initiative is the community PR to bring Kibana 7.2 support:
https://github.com/sirensolutions/sentinl/pull/752

**Comment by meriem-ux** [comment]
@lmangani  i already sent u a email for asking you about sentinel version compatible with kibana 7.3.2
![1](https://user-images.githubusercontent.com/55734653/66144553-f6695f00-e600-11e9-88f1-ebe6b7260b45.png)

**Comment by lmangani** [comment]
@meriem-ux ... sorry to burst the bubble, but this is not how Open-Source works at all - I hope anyone with any experience here might agree that very message you pasted is a sad symptom of the lack of respect and consideration in this ecosystem. There's a repository for a purpose and I invite you and everyone to use it as much as possible to drive improvements and to inspire others to give more. Demanding stuff and walking into people's personal email is not the way I would suggest using in general ;) Or at the very least, don't brag about it.

If you care to follow the magic rules and act as a community member, You (and others) might discover a fantastic way to reach a bunch of amazing people who are always there to help and cooperate with others willing to contribute our common, humble projects with their time, comments, code or even just kind words of support.
