### ISSUE TITLE
Pagerduty Integrate with Sentinl

### ISSUE THREAD

**Issue by md3danish** [lmangani/sentinl#769]
Currently we do not  see any document to Integrate Pagerduty with Sentinl, 
Do we have that feature ? 
It will be nice to have the feature

Thanks

**Comment by lmangani** [comment]
Nothing planned but the generic API support should allow interaction with Pagerduty. PRs are always welcome.
If you'd like to sponsor this feature, feel free to get in touch or reopen this issue anytime.
