### ISSUE TITLE
Plugin sentinl [6.6.0] is incompatible with Kibana [7.7.0]

### ISSUE THREAD

**Issue by Yeading** [lmangani/sentinl#773]
/usr/share/kibana/bin/kibana-plugin   --allow-root   install file:///root/sentinl-v6.6.0.zip
Found previous install attempt. Deleting...
Attempting to transfer from file:///root/sentinl-v6.6.0.zip
Transferring 134770542 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Plugin sentinl [6.6.0] is incompatible with Kibana [7.7.0]"

**Comment by offspringus** [comment]
It is for  Kibana 6

**Comment by lmangani** [comment]
@offspringus is right - thank you for chiming in! @Yeading Versions are not cross-compatible with elasticsearch. We're trying to merge back patches to allow execution on 7.x next.
