### ISSUE TITLE
When supports Kibana7.6.2?

### ISSUE THREAD

**Issue by JerryZ521** [lmangani/sentinl#782]
Plugin sentinl [7.6.1] is incompatible with Kibana [7.6.2]

Thanks！

**Comment by lmangani** [comment]
Hi @zhangyibao that's expected - versions are locked to a kibana release. As a starter, try change the kibana version in sentinl's `package.json` file and see if it get loaded. If so we'll build a release - otherwise please attach any errors. Thanks!
```
"kibana": {
    "version": "7.6.2"
  },
```

**Comment by ssanthoshkalam19** [comment]
Hi @lmangani , Tried the above settings and getting this exception while starting kibana service.

{"type":"log","@timestamp":"2020-09-01T04:25:36Z","tags":["info","Sentinl","init_indices"],"pid":805339,"message":"creating watcher_alarms-2020.08.31 index ..."}
{"type":"log","@timestamp":"2020-09-01T04:25:36Z","tags":["error","Sentinl","init"],"pid":805339,"message":"start: Error: init indices: Error: create index: [mapper_parsing_exception] Root mapping definition has unsupported parameters:  [sentinl-alarm : {mappings={properties={watcher={type=text}, @timestamp={type=date}, attachment={type=binary}, payload={dynamic=true, type=object}, level={type=text}, report={type=boolean}, action={type=text}, error={type=boolean}, message={type=text}}}}] :: {\"path\":\"/_template/sentinl_watcher_alarms\",\"query\":{},\"body\":\"{\\\"index_patterns\\\":\\\"watcher_alarms*\\\",\\\"mappings\\\":{\\\"sentinl-alarm\\\":{\\\"mappings\\\":{\\\"properties\\\":{\\\"payload\\\":{\\\"type\\\":\\\"object\\\",\\\"dynamic\\\":\\\"true\\\"},\\\"attachment\\\":{\\\"type\\\":\\\"binary\\\"},\\\"error\\\":{\\\"type\\\":\\\"boolean\\\"},\\\"report\\\":{\\\"type\\\":\\\"boolean\\\"},\\\"watcher\\\":{\\\"type\\\":\\\"text\\\"},\\\"action\\\":{\\\"type\\\":\\\"text\\\"},\\\"level\\\":{\\\"type\\\":\\\"text\\\"},\\\"message\\\":{\\\"type\\\":\\\"text\\\"},\\\"@timestamp\\\":{\\\"type\\\":\\\"date\\\"}}}}},\\\"settings\\\":{\\\"index\\\":{\\\"lifecycle\\\":{\\\"name\\\":\\\"watcher-alarms\\\",\\\"rollover_alias\\\":\\\"watcher_alarms\\\"}}}}\",\"statusCode\":400,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"mapper_parsing_exception\\\",\\\"reason\\\":\\\"Root mapping definition has unsupported parameters:  [sentinl-alarm : {mappings={properties={watcher={type=text}, @timestamp={type=date}, attachment={type=binary}, payload={dynamic=true, type=object}, level={type=text}, report={type=boolean}, action={type=text}, error={type=boolean}, message={type=text}}}}]\\\"}],\\\"type\\\":\\\"mapper_parsing_exception\\\",\\\"reason\\\":\\\"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [sentinl-alarm : {mappings={properties={watcher={type=text}, @timestamp={type=date}, attachment={type=binary}, payload={dynamic=true, type=object}, level={type=text}, report={type=boolean}, action={type=text}, error={type=boolean}, message={type=text}}}}]\\\",\\\"caused_by\\\":{\\\"type\\\":\\\"mapper_parsing_exception\\\",\\\"reason\\\":\\\"Root mapping definition has unsupported parameters:  [sentinl-alarm : {mappings={properties={watcher={type=text}, @timestamp={type=date}, attachment={type=binary}, payload={dynamic=true, type=object}, level={type=text}, report={type=boolean}, action={type=text}, error={type=boolean}, message={type=text}}}}]\\\"}},\\\"status\\\":400}\"}"}
