### ISSUE TITLE
click Watchers->[New] button error

### ISSUE THREAD

**Issue by JerryZ521** [lmangani/sentinl#783]
kibana version:7.6.2
sentinl version:7.6.1

web console error:

kbn-ui-shared-deps.js:400 Uncaught TypeError: props.run is not a function
    at handleClick (navigation.bundle.js:3)
    at Object.h (kbn-ui-shared-deps.js:400)
    at M (kbn-ui-shared-deps.js:400)
    at kbn-ui-shared-deps.js:400
    at C (kbn-ui-shared-deps.js:400)
    at x (kbn-ui-shared-deps.js:400)
    at E (kbn-ui-shared-deps.js:400)
    at T (kbn-ui-shared-deps.js:400)
    at wn (kbn-ui-shared-deps.js:400)
    at ue (kbn-ui-shared-deps.js:400)

**Comment by ShiLongTowngrass** [comment]
me too, wo think it is bug.

**Comment by ShiLongTowngrass** [comment]
me too, i think that is bug.

**Comment by zhangyibao** [comment]
> me too, i think that is bug.

Maybe.  In the file [nav_menu.js]:
`
    if (view === 'watchers') {
      nav.unshift({
        key: 'new',
        description: 'Create new watcher',
        template,
        testId: 'sentinlNewWatcher'
      });
      return nav;
    }`
 no run function ，i don't know how to modify it.

**Comment by dahiyashish** [comment]
I am getting the same error.

**Comment by lzj1996121** [comment]
is there any solution now?

**Comment by ShiLongTowngrass** [comment]
@lzj1996121 I used elastalert now.

**Comment by lzj1996121** [comment]
will elastalert have any version requirement for ELK,i am using ELK7.8 now

**Comment by ShiLongTowngrass** [comment]
i am using ELK7.2. The author is still updating, and I guess it is.

**Comment by lmangani** [comment]
We will have a release for 7.x.x if we will have contributions from users in terms of code, time or donations.

**Comment by lzj1996121** [comment]
could elastalert and sentinl be installed together? i'm not going to uninstall sentinl now

**Comment by ShiLongTowngrass** [comment]
I don't think we should talk about elastalert here and respect the author.

**Comment by lzj1996121** [comment]
So sorry

**Comment by lmangani** [comment]
No offense taken :) thank you guys, hopefully sentinl will become again a viable alternative in 2021
