### ISSUE TITLE
When will support kibana7.9.2 ?

### ISSUE THREAD

**Issue by yigeyanse** [lmangani/sentinl#787]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |         |
| Elasticsearc |         |
| Server OS    |         |
| Browser      |         |

#### Original Install Method

- [ ] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

#### Steps to Reproduce
1.
1.
1.

#### Sample of data you have in Elasticsearch
```
```

#### Full Watcher JSON
```
```

#### Errors in Browser Console (if relevant)
```
```

**Comment by lmangani** [comment]
see README
